// Pure helpers for drafting a care plan from an in-home assessment
// transcript. Kept free of React / Supabase so the shaping logic is
// unit-testable — see src/lib/__tests__/assessmentCarePlan.test.js.
//
// These translate the assessment-extract-care-plan edge function's
// per-section claims (the same validated shape as care-plan-voice-extract)
// into the inputs the existing storage.js write path expects.

import { dayNamesToIndices } from '../features/care-plans/voice/voiceTaskSchema';

// Sections we never draft from a spoken assessment:
//   - isAutoGenerated (Snapshot — derived from other sections)
//   - matchCriteria   — admin-only caregiver-match preferences, an
//     operational choice, not something dictated during a clinical visit.
export const EXCLUDED_DRAFT_SECTION_IDS = new Set(['matchCriteria']);

// The sections eligible for assessment-driven drafting, in display order.
// `sections` is the CARE_PLAN_SECTIONS array.
export function eligibleAssessmentSections(sections) {
  return (sections || [])
    .filter((s) => s && !s.isAutoGenerated && !EXCLUDED_DRAFT_SECTION_IDS.has(s.id))
    .slice()
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
}

// Accepted field claims [{ id, value, ... }] → a { [fieldId]: value }
// patch suitable for storage.saveDraft(versionId, sectionId, patch).
// Later claims win on a duplicate id (defensive; validator dedupes).
export function claimsToFieldPatch(extracted) {
  const patch = {};
  for (const claim of extracted || []) {
    if (!claim || typeof claim.id !== 'string') continue;
    patch[claim.id] = claim.value;
  }
  return patch;
}

// A validated task claim (snake_case, from the edge function) → the
// camelCase task input storage.createTask expects.
export function taskClaimToCreateInput(claim) {
  return {
    category: claim.category,
    taskName: claim.task_name,
    description: claim.description ?? null,
    shifts: Array.isArray(claim.shifts) ? claim.shifts : [],
    daysOfWeek: dayNamesToIndices(claim.days_of_week),
    priority: claim.priority ?? 'standard',
    safetyNotes: claim.safety_notes ?? null,
  };
}

// Roll up the edge function's per-section results into counts for the
// success toast: how many sections got data, total fields, total tasks.
export function summarizeDraftResult(sectionResults) {
  let sectionsWithContent = 0;
  let fields = 0;
  let tasks = 0;
  for (const r of sectionResults || []) {
    const f = Array.isArray(r?.extracted) ? r.extracted.length : 0;
    const t = Array.isArray(r?.proposedTasks) ? r.proposedTasks.length : 0;
    if (f > 0 || t > 0) sectionsWithContent += 1;
    fields += f;
    tasks += t;
  }
  return { sectionsWithContent, fields, tasks };
}

// One-line human summary for the toast.
export function describeDraftSummary({ sectionsWithContent, fields, tasks }) {
  if (fields === 0 && tasks === 0) {
    return 'No new care-plan details were found in this assessment.';
  }
  const parts = [];
  parts.push(`${fields} field${fields === 1 ? '' : 's'}`);
  if (tasks > 0) parts.push(`${tasks} task${tasks === 1 ? '' : 's'}`);
  return `Draft updated with ${parts.join(' and ')} across ${sectionsWithContent} section${sectionsWithContent === 1 ? '' : 's'}.`;
}

// Toast describing what was actually APPLIED plus an honest, specific
// account of anything that couldn't be applied (item-isolated draft).
//   applied: { sections, fields, tasks }  — counts that persisted
//   skipped: [{ label, reason }]          — items that did not
// The skipped portion is deliberately loud and specific — isolation is
// only safe if a dropped item is surfaced, not silently swallowed.
export function describeDraftOutcome({ applied, skipped } = {}) {
  const a = applied || { sections: 0, fields: 0, tasks: 0 };
  const skips = Array.isArray(skipped) ? skipped : [];

  let base;
  if (a.fields === 0 && a.tasks === 0) {
    base = skips.length > 0
      ? "No care-plan details could be applied from this assessment."
      : 'No new care-plan details were found in this assessment.';
  } else {
    const parts = [`${a.fields} field${a.fields === 1 ? '' : 's'}`];
    if (a.tasks > 0) parts.push(`${a.tasks} task${a.tasks === 1 ? '' : 's'}`);
    base = `Draft updated with ${parts.join(' and ')} across ${a.sections} section${a.sections === 1 ? '' : 's'}.`;
  }

  if (skips.length === 0) return base;

  const names = skips.map((s) => s && s.label).filter(Boolean);
  const preview = names.slice(0, 3).join(', ');
  const more = names.length > 3 ? ` and ${names.length - 3} more` : '';
  const detail = preview ? ` (${preview}${more})` : '';
  return `${base} ${skips.length} item${skips.length === 1 ? '' : 's'} couldn't be applied automatically${detail} — review the assessment and add them manually.`;
}
