// Follow-up tasks helper — load/update for the Tasks dashboard and
// the inline panels on caregiver/client detail pages.
//
// The schema lives in migration 20260525000000:
//   follow_up_templates  — configurable cadences (org-scoped)
//   follow_up_tasks      — concrete instances generated by triggers
//
// All writes go through Supabase + RLS (staff-only). The DB triggers
// generate instances on shift insert/update; this module only handles
// the read + state-transition path (mark done, snooze, reassign,
// cancel).

import { supabase } from './supabase';

// ─── Mapper ───────────────────────────────────────────────────

export function dbToFollowUpTask(row) {
  if (!row) return null;
  return {
    id: row.id,
    orgId: row.org_id,
    // Source distinguishes template-driven rows from user/ai-created
    // ones (migration 20260527000000). Defaults to 'template' for
    // backwards-compat with any caller that hand-built a fake row.
    source: row.source ?? 'template',
    title: row.title ?? null,
    description: row.description ?? null,
    createdBy: row.created_by ?? null,
    notifiedAt: row.notified_at ?? null,
    templateId: row.template_id ?? null,
    caregiverId: row.caregiver_id ?? null,
    clientId: row.client_id ?? null,
    anchorShiftId: row.anchor_shift_id ?? null,
    dueAt: row.due_at,
    status: row.status,
    urgency: row.urgency,
    assignedTo: row.assigned_to ?? null,
    snoozedUntil: row.snoozed_until ?? null,
    completedAt: row.completed_at ?? null,
    completedBy: row.completed_by ?? null,
    completionNote: row.completion_note ?? null,
    cancellationReason: row.cancellation_reason ?? null,
    generatedAt: row.generated_at,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    // Joined-template fields (when select uses
    //   `*, follow_up_templates(slug, name, guidance, target_type)`).
    template: row.follow_up_templates
      ? {
          slug: row.follow_up_templates.slug,
          name: row.follow_up_templates.name,
          guidance: row.follow_up_templates.guidance ?? null,
          targetType: row.follow_up_templates.target_type,
          recurringIntervalDays: row.follow_up_templates.recurring_interval_days ?? null,
        }
      : null,
  };
}

// Display name for a task across template/user/ai sources. Template
// rows use the joined template name; user/ai rows use the user-entered
// title; falls back to a generic label so the UI never renders blank.
export function followUpDisplayTitle(task) {
  if (!task) return 'Follow-up';
  if (task.template?.name) return task.template.name;
  if (task.title) return task.title;
  return 'Follow-up';
}

// ─── Bucket helpers (pure) ───────────────────────────────────
// Group tasks into the OVERDUE / TODAY / TOMORROW / THIS WEEK / LATER
// sections used by the Tasks dashboard. Pure so the unit tests can
// pin them down without round-tripping the DB.

const MS_PER_DAY = 24 * 60 * 60 * 1000;

export function bucketFollowUps(tasks, { now = Date.now() } = {}) {
  if (!Array.isArray(tasks)) return { overdue: [], today: [], tomorrow: [], thisWeek: [], later: [] };

  const today = startOfLocalDay(now);
  const tomorrow = today + MS_PER_DAY;
  const dayAfter = tomorrow + MS_PER_DAY;
  const weekEnd = today + 7 * MS_PER_DAY;

  const out = { overdue: [], today: [], tomorrow: [], thisWeek: [], later: [] };
  for (const t of tasks) {
    if (!t || !t.dueAt) continue;
    const due = new Date(t.dueAt).getTime();
    if (Number.isNaN(due)) continue;
    if (due < today) out.overdue.push(t);
    else if (due < tomorrow) out.today.push(t);
    else if (due < dayAfter) out.tomorrow.push(t);
    else if (due < weekEnd) out.thisWeek.push(t);
    else out.later.push(t);
  }

  // Sort each bucket by due_at ascending so the most urgent rises first.
  for (const list of Object.values(out)) {
    list.sort((a, b) => new Date(a.dueAt) - new Date(b.dueAt));
  }
  return out;
}

function startOfLocalDay(ms) {
  const d = new Date(ms);
  d.setHours(0, 0, 0, 0);
  return d.getTime();
}

/**
 * Count tasks that should bump the sidebar badge: pending + (overdue
 * OR due today). Used by the navigation chrome.
 */
export function countNavBadge(tasks, { now = Date.now() } = {}) {
  if (!Array.isArray(tasks)) return 0;
  const today = startOfLocalDay(now);
  const tomorrow = today + MS_PER_DAY;
  let n = 0;
  for (const t of tasks) {
    if (!t || t.status !== 'pending' || !t.dueAt) continue;
    const due = new Date(t.dueAt).getTime();
    if (Number.isNaN(due)) continue;
    if (due < tomorrow) n += 1;
  }
  return n;
}

// ─── Reads ───────────────────────────────────────────────────

const FULL_SELECT = `
  *,
  follow_up_templates ( slug, name, guidance, target_type, recurring_interval_days )
`;

/**
 * Load every open (pending or snoozed) follow-up task for the caller's
 * org, plus the most recently completed/cancelled ones for context.
 * RLS scopes by org.
 */
export async function loadOpenFollowUps(client = supabase) {
  if (!client) return [];
  const { data, error } = await client
    .from('follow_up_tasks')
    .select(FULL_SELECT)
    .in('status', ['pending', 'snoozed'])
    .order('due_at', { ascending: true });
  if (error) {
    console.warn('loadOpenFollowUps failed:', error.message);
    return [];
  }
  return (data ?? []).map(dbToFollowUpTask);
}

/**
 * Load follow-ups for a single caregiver, ordered by due_at asc.
 * Used by the inline panel on the caregiver detail page.
 * Limited to the next 90 days plus anything overdue.
 */
export async function loadFollowUpsForCaregiver(caregiverId, client = supabase) {
  if (!client || !caregiverId) return [];
  const { data, error } = await client
    .from('follow_up_tasks')
    .select(FULL_SELECT)
    .eq('caregiver_id', caregiverId)
    .in('status', ['pending', 'snoozed'])
    .order('due_at', { ascending: true });
  if (error) {
    console.warn('loadFollowUpsForCaregiver failed:', error.message);
    return [];
  }
  return (data ?? []).map(dbToFollowUpTask);
}

/**
 * Load follow-ups for a single client. Mirror of the caregiver lookup.
 */
export async function loadFollowUpsForClient(clientId, client = supabase) {
  if (!client || !clientId) return [];
  const { data, error } = await client
    .from('follow_up_tasks')
    .select(FULL_SELECT)
    .eq('client_id', clientId)
    .in('status', ['pending', 'snoozed'])
    .order('due_at', { ascending: true });
  if (error) {
    console.warn('loadFollowUpsForClient failed:', error.message);
    return [];
  }
  return (data ?? []).map(dbToFollowUpTask);
}

/**
 * Load all enabled templates for the org. Used by the (future) admin
 * settings panel; not used by the Tasks dashboard read path itself.
 */
export async function loadFollowUpTemplates(client = supabase) {
  if (!client) return [];
  const { data, error } = await client
    .from('follow_up_templates')
    .select('*')
    .order('sort_order', { ascending: true });
  if (error) {
    console.warn('loadFollowUpTemplates failed:', error.message);
    return [];
  }
  return data ?? [];
}

// ─── Mutations ────────────────────────────────────────────────

/**
 * Mark a task done. `completedBy` is the email/name of the staff
 * member resolving it; `note` is an optional one-liner.
 *
 * Returns the updated row or null on error. Surface errors via the
 * caller's toast so the UI can roll back optimistic updates.
 */
export async function markFollowUpDone(taskId, { completedBy, note = null }, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({
      status: 'done',
      completed_at: new Date().toISOString(),
      completed_by: completedBy ?? null,
      completion_note: (note || '').trim() || null,
    })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

/**
 * Snooze a task. `until` is a Date or ISO string. The dashboard
 * filters snoozed tasks out by default; a future cron may unsnooze
 * automatically by flipping status back to 'pending' when
 * snoozed_until <= now.
 */
export async function snoozeFollowUp(taskId, until, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const iso = until instanceof Date ? until.toISOString() : String(until);
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({ status: 'snoozed', snoozed_until: iso })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

/**
 * Reassign a task to a different staff member (email or name).
 */
export async function reassignFollowUp(taskId, assignee, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const value = (assignee || '').trim() || null;
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({ assigned_to: value })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

/**
 * Cancel a task manually (e.g., "no longer needed"). Distinct from
 * the auto-cancel that fires when an assignment ends — that records
 * cancellation_reason = 'assignment_ended'; this records the reason
 * the user provided.
 */
export async function cancelFollowUp(taskId, reason, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const value = (reason || '').trim() || null;
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({ status: 'cancelled', cancellation_reason: value })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

// ─── User-created tasks (migration 20260527000000) ─────────────

/**
 * Validate + normalize a user-task input. Returns either
 *   { row, error: null } where `row` is the snake_case INSERT payload
 * or
 *   { row: null, error: Error } with a human-readable message.
 *
 * Pure — exported for unit tests. The shape CHECK in the DB is the
 * source of truth; this helper just gives a clean error before the
 * round-trip.
 */
export function buildUserTaskRow(input) {
  if (!input || typeof input !== 'object') {
    return { row: null, error: new Error('Missing task input') };
  }
  const title = String(input.title ?? '').trim();
  if (!title) {
    return { row: null, error: new Error('Title is required') };
  }
  const dueAt = input.dueAt instanceof Date
    ? input.dueAt.toISOString()
    : (typeof input.dueAt === 'string' && input.dueAt) ? input.dueAt : null;
  if (!dueAt) {
    return { row: null, error: new Error('Due date is required') };
  }
  const urgency = (input.urgency || '').toLowerCase();
  if (!['critical', 'warning', 'info'].includes(urgency)) {
    return { row: null, error: new Error('Urgency must be critical, warning, or info') };
  }
  const source = input.source === 'ai' ? 'ai' : 'user';
  const caregiverId = input.caregiverId ?? null;
  const clientId = input.clientId ?? null;
  if (caregiverId && clientId) {
    return { row: null, error: new Error('A task can link to a caregiver or a client, not both') };
  }
  const createdBy = (input.createdBy || '').trim() || null;
  // Owner decision 2026-05-27: creator is the assignee. Caller may
  // override assignedTo explicitly (e.g., a future reassign-on-create
  // affordance) but otherwise we copy createdBy.
  const assignedTo = (input.assignedTo ?? createdBy) || null;
  const description = (input.description || '').trim() || null;

  return {
    row: {
      source,
      title,
      description,
      due_at: dueAt,
      urgency,
      caregiver_id: caregiverId,
      client_id: clientId,
      assigned_to: assignedTo,
      created_by: createdBy,
    },
    error: null,
  };
}

/**
 * Create a user-authored follow-up task. Returns { task, error }
 * where task is the mapped row on success.
 *
 * The shape CHECK in the DB rejects malformed rows (e.g., both
 * caregiver + client linked, or empty title); we surface errors
 * verbatim so the modal can show them to the user.
 *
 * org_id is filled by the column DEFAULT (public.default_org_id()) so
 * the caller doesn't need to pass it. RLS enforces the row goes into
 * the caller's tenant.
 */
export async function createUserTask(input, client = supabase) {
  if (!client) return { task: null, error: new Error('Missing supabase client') };
  const { row, error: validationError } = buildUserTaskRow(input);
  if (validationError) return { task: null, error: validationError };
  const { data, error } = await client
    .from('follow_up_tasks')
    .insert(row)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

/**
 * Update a user task's editable fields (title/description/dueAt/
 * urgency/caregiverId/clientId). Fields not present in `patch` are
 * left untouched. Resets notified_at to NULL whenever dueAt changes
 * so the Phase 2 dispatcher re-notifies for the new time.
 */
export async function updateUserTask(taskId, patch, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  if (!patch || typeof patch !== 'object') {
    return { task: null, error: new Error('Missing patch') };
  }
  const update = {};
  if ('title' in patch) {
    const t = String(patch.title ?? '').trim();
    if (!t) return { task: null, error: new Error('Title cannot be empty') };
    update.title = t;
  }
  if ('description' in patch) {
    update.description = (patch.description || '').trim() || null;
  }
  if ('dueAt' in patch) {
    const iso = patch.dueAt instanceof Date ? patch.dueAt.toISOString() : patch.dueAt;
    if (!iso) return { task: null, error: new Error('Due date cannot be empty') };
    update.due_at = iso;
    // Re-arm the dispatcher for the new due time.
    update.notified_at = null;
  }
  if ('urgency' in patch) {
    const u = (patch.urgency || '').toLowerCase();
    if (!['critical', 'warning', 'info'].includes(u)) {
      return { task: null, error: new Error('Invalid urgency') };
    }
    update.urgency = u;
  }
  if ('caregiverId' in patch || 'clientId' in patch) {
    const cg = 'caregiverId' in patch ? (patch.caregiverId ?? null) : undefined;
    const cl = 'clientId' in patch ? (patch.clientId ?? null) : undefined;
    if (cg !== undefined) update.caregiver_id = cg;
    if (cl !== undefined) update.client_id = cl;
    // The DB shape CHECK will reject both-set; surface a cleaner error
    // upfront so the modal can hint the user.
    const finalCg = cg !== undefined ? cg : null;
    const finalCl = cl !== undefined ? cl : null;
    if (finalCg && finalCl) {
      return { task: null, error: new Error('A task can link to a caregiver or a client, not both') };
    }
  }
  if ('assignedTo' in patch) {
    update.assigned_to = (patch.assignedTo || '').trim() || null;
  }
  if (Object.keys(update).length === 0) {
    return { task: null, error: new Error('Nothing to update') };
  }
  const { data, error } = await client
    .from('follow_up_tasks')
    .update(update)
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

// ─── Event logging (fire-and-forget) ──────────────────────────
// Writes to the unified `events` bus so the AI context assembler
// picks up task activity in its situational-awareness layer. NEVER
// blocks the user's action — failures are swallowed with a console
// warning. Per the existing pattern in supabase/functions/ai-chat
// (and noted in migration 20260523000000), the events table's
// entity_id is uuid; caregivers.id / clients.id are text, so for
// task events we pass entity_id=NULL and stash the text IDs in the
// payload.

const TASK_EVENT_TYPES = new Set([
  'task_created', 'task_completed', 'task_snoozed', 'task_overdue', 'task_due',
]);

export async function logTaskEvent(type, task, actor, client = supabase) {
  try {
    if (!client || !task || !TASK_EVENT_TYPES.has(type)) return;
    const payload = {
      task_id: task.id,
      source: task.source ?? 'template',
      title: followUpDisplayTitle(task),
      due_at: task.dueAt ?? null,
      assigned_to: task.assignedTo ?? null,
      caregiver_id: task.caregiverId ?? null,
      client_id: task.clientId ?? null,
    };
    await client.from('events').insert({
      event_type: type,
      entity_type: task.caregiverId ? 'caregiver' : task.clientId ? 'client' : null,
      entity_id: null,
      actor: actor || null,
      payload,
    });
  } catch (err) {
    // Observability only — never let event-logging break the UI path.
    console.warn('logTaskEvent failed:', err?.message || err);
  }
}
