// Follow-up tasks helper — load/update for the Tasks dashboard and
// the inline panels on caregiver/client detail pages.
//
// The schema lives in migration 20260525000000:
//   follow_up_templates  — configurable cadences (org-scoped)
//   follow_up_tasks      — concrete instances generated by triggers
//
// All writes go through Supabase + RLS (staff-only). The DB triggers
// generate instances on shift insert/update; this module only handles
// the read + state-transition path (mark done, snooze, reassign,
// cancel).

import { supabase } from './supabase';

// ─── Mapper ───────────────────────────────────────────────────

export function dbToFollowUpTask(row) {
  if (!row) return null;
  return {
    id: row.id,
    orgId: row.org_id,
    templateId: row.template_id,
    caregiverId: row.caregiver_id,
    clientId: row.client_id,
    anchorShiftId: row.anchor_shift_id ?? null,
    dueAt: row.due_at,
    status: row.status,
    urgency: row.urgency,
    assignedTo: row.assigned_to ?? null,
    snoozedUntil: row.snoozed_until ?? null,
    completedAt: row.completed_at ?? null,
    completedBy: row.completed_by ?? null,
    completionNote: row.completion_note ?? null,
    cancellationReason: row.cancellation_reason ?? null,
    generatedAt: row.generated_at,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    // Joined-template fields (when select uses
    //   `*, follow_up_templates(slug, name, guidance, target_type)`).
    template: row.follow_up_templates
      ? {
          slug: row.follow_up_templates.slug,
          name: row.follow_up_templates.name,
          guidance: row.follow_up_templates.guidance ?? null,
          targetType: row.follow_up_templates.target_type,
          recurringIntervalDays: row.follow_up_templates.recurring_interval_days ?? null,
        }
      : null,
  };
}

// ─── Bucket helpers (pure) ───────────────────────────────────
// Group tasks into the OVERDUE / TODAY / TOMORROW / THIS WEEK / LATER
// sections used by the Tasks dashboard. Pure so the unit tests can
// pin them down without round-tripping the DB.

const MS_PER_DAY = 24 * 60 * 60 * 1000;

export function bucketFollowUps(tasks, { now = Date.now() } = {}) {
  if (!Array.isArray(tasks)) return { overdue: [], today: [], tomorrow: [], thisWeek: [], later: [] };

  const today = startOfLocalDay(now);
  const tomorrow = today + MS_PER_DAY;
  const dayAfter = tomorrow + MS_PER_DAY;
  const weekEnd = today + 7 * MS_PER_DAY;

  const out = { overdue: [], today: [], tomorrow: [], thisWeek: [], later: [] };
  for (const t of tasks) {
    if (!t || !t.dueAt) continue;
    const due = new Date(t.dueAt).getTime();
    if (Number.isNaN(due)) continue;
    if (due < today) out.overdue.push(t);
    else if (due < tomorrow) out.today.push(t);
    else if (due < dayAfter) out.tomorrow.push(t);
    else if (due < weekEnd) out.thisWeek.push(t);
    else out.later.push(t);
  }

  // Sort each bucket by due_at ascending so the most urgent rises first.
  for (const list of Object.values(out)) {
    list.sort((a, b) => new Date(a.dueAt) - new Date(b.dueAt));
  }
  return out;
}

function startOfLocalDay(ms) {
  const d = new Date(ms);
  d.setHours(0, 0, 0, 0);
  return d.getTime();
}

/**
 * Count tasks that should bump the sidebar badge: pending + (overdue
 * OR due today). Used by the navigation chrome.
 */
export function countNavBadge(tasks, { now = Date.now() } = {}) {
  if (!Array.isArray(tasks)) return 0;
  const today = startOfLocalDay(now);
  const tomorrow = today + MS_PER_DAY;
  let n = 0;
  for (const t of tasks) {
    if (!t || t.status !== 'pending' || !t.dueAt) continue;
    const due = new Date(t.dueAt).getTime();
    if (Number.isNaN(due)) continue;
    if (due < tomorrow) n += 1;
  }
  return n;
}

// ─── Reads ───────────────────────────────────────────────────

const FULL_SELECT = `
  *,
  follow_up_templates ( slug, name, guidance, target_type, recurring_interval_days )
`;

/**
 * Load every open (pending or snoozed) follow-up task for the caller's
 * org, plus the most recently completed/cancelled ones for context.
 * RLS scopes by org.
 */
export async function loadOpenFollowUps(client = supabase) {
  if (!client) return [];
  const { data, error } = await client
    .from('follow_up_tasks')
    .select(FULL_SELECT)
    .in('status', ['pending', 'snoozed'])
    .order('due_at', { ascending: true });
  if (error) {
    console.warn('loadOpenFollowUps failed:', error.message);
    return [];
  }
  return (data ?? []).map(dbToFollowUpTask);
}

/**
 * Load follow-ups for a single caregiver, ordered by due_at asc.
 * Used by the inline panel on the caregiver detail page.
 * Limited to the next 90 days plus anything overdue.
 */
export async function loadFollowUpsForCaregiver(caregiverId, client = supabase) {
  if (!client || !caregiverId) return [];
  const { data, error } = await client
    .from('follow_up_tasks')
    .select(FULL_SELECT)
    .eq('caregiver_id', caregiverId)
    .in('status', ['pending', 'snoozed'])
    .order('due_at', { ascending: true });
  if (error) {
    console.warn('loadFollowUpsForCaregiver failed:', error.message);
    return [];
  }
  return (data ?? []).map(dbToFollowUpTask);
}

/**
 * Load follow-ups for a single client. Mirror of the caregiver lookup.
 */
export async function loadFollowUpsForClient(clientId, client = supabase) {
  if (!client || !clientId) return [];
  const { data, error } = await client
    .from('follow_up_tasks')
    .select(FULL_SELECT)
    .eq('client_id', clientId)
    .in('status', ['pending', 'snoozed'])
    .order('due_at', { ascending: true });
  if (error) {
    console.warn('loadFollowUpsForClient failed:', error.message);
    return [];
  }
  return (data ?? []).map(dbToFollowUpTask);
}

/**
 * Load all enabled templates for the org. Used by the (future) admin
 * settings panel; not used by the Tasks dashboard read path itself.
 */
export async function loadFollowUpTemplates(client = supabase) {
  if (!client) return [];
  const { data, error } = await client
    .from('follow_up_templates')
    .select('*')
    .order('sort_order', { ascending: true });
  if (error) {
    console.warn('loadFollowUpTemplates failed:', error.message);
    return [];
  }
  return data ?? [];
}

// ─── Mutations ────────────────────────────────────────────────

/**
 * Mark a task done. `completedBy` is the email/name of the staff
 * member resolving it; `note` is an optional one-liner.
 *
 * Returns the updated row or null on error. Surface errors via the
 * caller's toast so the UI can roll back optimistic updates.
 */
export async function markFollowUpDone(taskId, { completedBy, note = null }, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({
      status: 'done',
      completed_at: new Date().toISOString(),
      completed_by: completedBy ?? null,
      completion_note: (note || '').trim() || null,
    })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

/**
 * Snooze a task. `until` is a Date or ISO string. The dashboard
 * filters snoozed tasks out by default; a future cron may unsnooze
 * automatically by flipping status back to 'pending' when
 * snoozed_until <= now.
 */
export async function snoozeFollowUp(taskId, until, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const iso = until instanceof Date ? until.toISOString() : String(until);
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({ status: 'snoozed', snoozed_until: iso })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

/**
 * Reassign a task to a different staff member (email or name).
 */
export async function reassignFollowUp(taskId, assignee, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const value = (assignee || '').trim() || null;
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({ assigned_to: value })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}

/**
 * Cancel a task manually (e.g., "no longer needed"). Distinct from
 * the auto-cancel that fires when an assignment ends — that records
 * cancellation_reason = 'assignment_ended'; this records the reason
 * the user provided.
 */
export async function cancelFollowUp(taskId, reason, client = supabase) {
  if (!client || !taskId) return { task: null, error: new Error('Missing task id or client') };
  const value = (reason || '').trim() || null;
  const { data, error } = await client
    .from('follow_up_tasks')
    .update({ status: 'cancelled', cancellation_reason: value })
    .eq('id', taskId)
    .select(FULL_SELECT)
    .single();
  if (error) return { task: null, error };
  return { task: dbToFollowUpTask(data), error: null };
}
