// ═══════════════════════════════════════════════════════════════
// voiceFieldSchema
//
// Translates a CARE_PLAN_SECTIONS entry into a compact, portable
// "extraction schema" the care-plan-voice-extract edge function
// understands. The edge function turns this into a Claude tool's
// JSON-schema input contract so structured extraction is enforced
// at the API level (Claude cannot return field ids that don't exist
// or enum values that aren't allowed).
//
// One source of truth: sections.js defines the form. This file
// projects that definition into the extraction format. Changing a
// field's options/type in sections.js automatically updates what
// voice extraction will accept — no parallel schema to maintain.
//
// Sections excluded from voice capture (computed by
// sectionSupportsVoiceCapture):
//   - isAutoGenerated (Snapshot — readOnly, derived from other
//     sections)
//   - usesTasksTable with groups (Daily Living, Home & Life — tasks
//     live in a separate table, deferred to a later phase)
//
// Fields excluded from the schema (computed by buildVoiceFieldSchema):
//   - readOnly fields (no way to write them anyway)
// ═══════════════════════════════════════════════════════════════

import { FIELD_TYPES } from '../sections';

const ABILITY_LEVELS = [
  'Independent', 'Setup only', 'Partial assist', 'Full assist', 'Dependent',
];


/**
 * Is this section eligible for voice capture in the current phase?
 *
 * Phase 1 rule: section must be editable (not auto-generated) and
 * must not depend on the care_plan_tasks side table for its content
 * (ADLs / IADLs). The auto-generated check covers Snapshot; the
 * tasks/groups check covers Daily Living and Home & Life, which we
 * defer to a follow-up phase.
 */
export function sectionSupportsVoiceCapture(section) {
  if (!section) return false;
  if (section.isAutoGenerated) return false;
  // Grouped + tasks-driven sections (ADLs, IADLs) are out for Phase 1.
  // A section can declare groups OR usesTasksTable; both flags indicate
  // task-list-bearing sections where voice support needs cross-table
  // write logic we haven't built yet.
  const hasGroups = Array.isArray(section.groups) && section.groups.length > 0;
  if (hasGroups || section.usesTasksTable) return false;
  // Match Criteria has many PRN fields with a tri-state {flag, option}
  // shape; we support those but they're admin-only and rare so they're
  // still in scope.
  return true;
}


/**
 * Build the extraction schema for a section, suitable for posting to
 * the care-plan-voice-extract edge function.
 *
 * Output shape:
 *   {
 *     sectionId, sectionLabel, sectionDescription,
 *     fields: [
 *       {
 *         id, label, help?, type, options?, subfields?, multiselect?,
 *         conditionalHint?
 *       }, ...
 *     ],
 *   }
 *
 * `type` is one of the FIELD_TYPES strings, normalized so the edge
 * function can dispatch on a finite set:
 *   text | textarea | date | number | select | multiselect |
 *   boolean | yesno | yn | phone | email | list | prn | levelPick
 *
 * Conditional fields are included with a `conditionalHint` describing
 * the gating rule in plain English — so the extractor knows e.g.
 * "Spouse / partner name only applies when Marital status is Married
 * or Partnered."
 */
export function buildVoiceFieldSchema(section) {
  if (!section) return null;
  return {
    sectionId: section.id,
    sectionLabel: section.label,
    sectionDescription: section.description || '',
    fields: (section.fields || [])
      .filter((f) => !f.readOnly)
      .map((f) => projectField(f, section)),
  };
}


/**
 * Project a single field definition into the extraction-schema shape.
 * Recurses through `subfields` for LIST type.
 */
function projectField(field, section) {
  const out = {
    id: field.id,
    label: field.label,
    type: field.type,
  };

  if (field.help)        out.help = field.help;
  if (field.placeholder) out.placeholder = field.placeholder;

  // Enum-ish fields: pass options through.
  if (
    field.type === FIELD_TYPES.SELECT ||
    field.type === FIELD_TYPES.MULTISELECT ||
    field.type === FIELD_TYPES.PRN
  ) {
    if (Array.isArray(field.options) && field.options.length > 0) {
      out.options = [...field.options];
    }
  }

  // YN: tri-state radio with optional note. Pass the allowed answers.
  if (field.type === FIELD_TYPES.YN) {
    out.options = Array.isArray(field.options) && field.options.length > 0
      ? [...field.options]
      : ['Yes', 'No', 'Unknown'];
  }

  // LEVEL_PICK has a fixed 5-step scale.
  if (field.type === FIELD_TYPES.LEVEL_PICK) {
    out.options = [...ABILITY_LEVELS];
  }

  // AUTOCOMPLETE renders as free text with suggestions; treat as text
  // for the extractor (suggestions are only typing aids).
  if (field.type === FIELD_TYPES.AUTOCOMPLETE) {
    out.type = FIELD_TYPES.TEXT;
    if (field.suggestionsKey) out.suggestionsKey = field.suggestionsKey;
  }

  // LIST: nested rows. Recurse through subfields so the extractor
  // knows the per-row shape and can produce one object per item.
  if (field.type === FIELD_TYPES.LIST) {
    out.subfields = (field.subfields || []).map((sub) => projectField(sub, section));
  }

  // Conditional fields: keep them but explain the gating rule in
  // plain English. The extractor needs to be able to fill the gating
  // field AND its dependent, but should also know which fields are
  // contextually meaningful.
  if (field.conditional) {
    out.conditionalHint = describeConditional(field.conditional, section);
  }

  return out;
}


/**
 * Plain-English description of a `conditional` rule so the LLM can
 * understand contextual gating without us encoding the predicate.
 *
 * Examples:
 *   { field: 'maritalStatus', in: ['Married', 'Partnered'] }
 *     → "Only applies when 'Marital status' is one of: Married, Partnered."
 *   { field: 'canBeLeftAlone', equals: 'Short periods only' }
 *     → "Only applies when 'Can be left alone' is 'Short periods only'."
 *   { field: 'lastHospitalizationDate', notEquals: '' }
 *     → "Only applies when 'Most recent hospitalization — date' is set."
 */
export function describeConditional(conditional, section) {
  if (!conditional) return '';
  const siblingLabel = lookupFieldLabel(section, conditional.field) || conditional.field;

  if (Array.isArray(conditional.in)) {
    return `Only applies when '${siblingLabel}' is one of: ${conditional.in.join(', ')}.`;
  }
  if (conditional.equals !== undefined) {
    return `Only applies when '${siblingLabel}' is '${conditional.equals}'.`;
  }
  if (conditional.notEquals !== undefined) {
    if (conditional.notEquals === '' || conditional.notEquals == null) {
      return `Only applies when '${siblingLabel}' is set.`;
    }
    return `Only applies when '${siblingLabel}' is not '${conditional.notEquals}'.`;
  }
  return '';
}


function lookupFieldLabel(section, fieldId) {
  if (!section || !fieldId) return null;
  const found = (section.fields || []).find((f) => f.id === fieldId);
  return found?.label || null;
}
