// ═══════════════════════════════════════════════════════════════
// voiceFieldSchema
//
// Translates a CARE_PLAN_SECTIONS entry into a compact, portable
// "extraction schema" the care-plan-voice-extract edge function
// understands. The edge function turns this into a Claude tool's
// JSON-schema input contract so structured extraction is enforced
// at the API level (Claude cannot return field ids that don't exist
// or enum values that aren't allowed).
//
// One source of truth: sections.js defines the form. This file
// projects that definition into the extraction format. Changing a
// field's options/type in sections.js automatically updates what
// voice extraction will accept — no parallel schema to maintain.
//
// Sections currently excluded from voice capture:
//   - isAutoGenerated (Snapshot — readOnly, derived from other
//     sections)
//
// Phase 2 added grouped sections (Daily Living ADLs, Home & Life
// IADLs) by tagging each projected field with its `groupId` so the
// prompt and review UI can organize by accordion group. Tasks (the
// rows in care_plan_tasks for those sections) are NOT touched by
// voice capture yet — that's deferred to Phase 3.
//
// Fields excluded from the schema (computed by buildVoiceFieldSchema):
//   - readOnly fields (no way to write them anyway)
//   - For grouped sections, fields not assigned to any group (they
//     don't render in the editor, so voice shouldn't fill them
//     either — usually back-compat fields kept around for old data)
// ═══════════════════════════════════════════════════════════════

import { FIELD_TYPES } from '../sections';

const ABILITY_LEVELS = [
  'Independent', 'Setup only', 'Partial assist', 'Full assist', 'Dependent',
];


/**
 * Is this section eligible for voice capture?
 *
 * Auto-generated sections (Snapshot) are permanently out — they're
 * derived, not authored. Everything else, including grouped sections
 * like Daily Living and Home & Life, is in.
 *
 * Note: even when a grouped section is voice-capable, the
 * accompanying care_plan_tasks rows are NOT filled by voice yet.
 * Voice writes only to the JSONB `data` field for now. Tasks remain
 * a manual operation via the existing TaskEditor.
 */
export function sectionSupportsVoiceCapture(section) {
  if (!section) return false;
  if (section.isAutoGenerated) return false;
  return true;
}


/**
 * Does this section define accordion groups? Mirrors
 * sections.js#sectionHasGroups, copied here to avoid a circular-ish
 * import (sections.js is the upstream module).
 */
function hasGroups(section) {
  return Boolean(
    section && Array.isArray(section.groups) && section.groups.length > 0,
  );
}


/**
 * Build the extraction schema for a section, suitable for posting to
 * the care-plan-voice-extract edge function.
 *
 * Output shape:
 *   {
 *     sectionId, sectionLabel, sectionDescription,
 *     groups?: [{ id, label, description? }, ...],
 *     fields: [
 *       {
 *         id, label, help?, type, options?, subfields?,
 *         conditionalHint?, groupId?, groupLabel?,
 *       }, ...
 *     ],
 *   }
 *
 * For grouped sections (Daily Living ADLs, Home & Life IADLs):
 *   - `groups` is populated in declaration order.
 *   - Each field carries `groupId` and `groupLabel` so the prompt
 *     and review UI can render group context without re-deriving it.
 *   - Fields are emitted in group order, then declaration order
 *     within each group. Matches what the editor renders.
 *   - Fields defined in section.fields but not assigned to any
 *     group are skipped (they're not in the editor either).
 *
 * For non-grouped sections, `groups` is undefined and fields have
 * no `groupId`. Phase 1 sections continue working unchanged.
 */
export function buildVoiceFieldSchema(section) {
  if (!section) return null;

  const out = {
    sectionId: section.id,
    sectionLabel: section.label,
    sectionDescription: section.description || '',
  };

  if (hasGroups(section)) {
    out.groups = section.groups.map((g) => {
      const meta = { id: g.id, label: g.label };
      if (g.description) meta.description = g.description;
      return meta;
    });
    // Walk the section's fields in group order, projecting each
    // with its groupId/groupLabel tag. Fields not in any group are
    // silently dropped — they don't render in the editor and we
    // don't want voice quietly writing fields the user can't see.
    const fieldById = new Map((section.fields || []).map((f) => [f.id, f]));
    const projected = [];
    for (const group of section.groups) {
      const ids = Array.isArray(group.fieldIds) ? group.fieldIds : [];
      for (const id of ids) {
        const field = fieldById.get(id);
        if (!field || field.readOnly) continue;
        projected.push({
          ...projectField(field, section),
          groupId: group.id,
          groupLabel: group.label,
        });
      }
    }
    out.fields = projected;
    return out;
  }

  // Flat (non-grouped) sections — same behavior as Phase 1.
  out.fields = (section.fields || [])
    .filter((f) => !f.readOnly)
    .map((f) => projectField(f, section));
  return out;
}


/**
 * Project a single field definition into the extraction-schema shape.
 * Recurses through `subfields` for LIST type.
 */
function projectField(field, section) {
  const out = {
    id: field.id,
    label: field.label,
    type: field.type,
  };

  if (field.help)        out.help = field.help;
  if (field.placeholder) out.placeholder = field.placeholder;

  // Enum-ish fields: pass options through.
  if (
    field.type === FIELD_TYPES.SELECT ||
    field.type === FIELD_TYPES.MULTISELECT ||
    field.type === FIELD_TYPES.PRN
  ) {
    if (Array.isArray(field.options) && field.options.length > 0) {
      out.options = [...field.options];
    }
  }

  // YN: tri-state radio with optional note. Pass the allowed answers.
  if (field.type === FIELD_TYPES.YN) {
    out.options = Array.isArray(field.options) && field.options.length > 0
      ? [...field.options]
      : ['Yes', 'No', 'Unknown'];
  }

  // LEVEL_PICK has a fixed 5-step scale.
  if (field.type === FIELD_TYPES.LEVEL_PICK) {
    out.options = [...ABILITY_LEVELS];
  }

  // AUTOCOMPLETE renders as free text with suggestions; treat as text
  // for the extractor (suggestions are only typing aids).
  if (field.type === FIELD_TYPES.AUTOCOMPLETE) {
    out.type = FIELD_TYPES.TEXT;
    if (field.suggestionsKey) out.suggestionsKey = field.suggestionsKey;
  }

  // LIST: nested rows. Recurse through subfields so the extractor
  // knows the per-row shape and can produce one object per item.
  if (field.type === FIELD_TYPES.LIST) {
    out.subfields = (field.subfields || []).map((sub) => projectField(sub, section));
  }

  // Conditional fields: keep them but explain the gating rule in
  // plain English. The extractor needs to be able to fill the gating
  // field AND its dependent, but should also know which fields are
  // contextually meaningful.
  if (field.conditional) {
    out.conditionalHint = describeConditional(field.conditional, section);
  }

  return out;
}


/**
 * Plain-English description of a `conditional` rule so the LLM can
 * understand contextual gating without us encoding the predicate.
 *
 * Examples:
 *   { field: 'maritalStatus', in: ['Married', 'Partnered'] }
 *     → "Only applies when 'Marital status' is one of: Married, Partnered."
 *   { field: 'canBeLeftAlone', equals: 'Short periods only' }
 *     → "Only applies when 'Can be left alone' is 'Short periods only'."
 *   { field: 'lastHospitalizationDate', notEquals: '' }
 *     → "Only applies when 'Most recent hospitalization — date' is set."
 */
export function describeConditional(conditional, section) {
  if (!conditional) return '';
  const siblingLabel = lookupFieldLabel(section, conditional.field) || conditional.field;

  if (Array.isArray(conditional.in)) {
    return `Only applies when '${siblingLabel}' is one of: ${conditional.in.join(', ')}.`;
  }
  if (conditional.equals !== undefined) {
    return `Only applies when '${siblingLabel}' is '${conditional.equals}'.`;
  }
  if (conditional.notEquals !== undefined) {
    if (conditional.notEquals === '' || conditional.notEquals == null) {
      return `Only applies when '${siblingLabel}' is set.`;
    }
    return `Only applies when '${siblingLabel}' is not '${conditional.notEquals}'.`;
  }
  return '';
}


function lookupFieldLabel(section, fieldId) {
  if (!section || !fieldId) return null;
  const found = (section.fields || []).find((f) => f.id === fieldId);
  return found?.label || null;
}
