// ═══════════════════════════════════════════════════════════════
// Tremendous Care — Style Theme
// All style objects consolidated in one file.
// ═══════════════════════════════════════════════════════════════

// ─── Main Styles ──────────────────────────────────────────────
export const styles = {
  app: {
    display: "flex",
    minHeight: "100vh",
    fontFamily: "'Plus Jakarta Sans', 'Helvetica Neue', sans-serif",
    background: "#F0F2F5",
    color: "#1A1A1A",
  },
  // Toast
  toast: {
    position: "fixed",
    top: 24,
    left: "50%",
    transform: "translateX(-50%)",
    background: "linear-gradient(135deg, #1B2A4A, #2E4E8D)",
    color: "#F9FAFB",
    padding: "14px 28px",
    borderRadius: 14,
    fontSize: 14,
    fontWeight: 600,
    zIndex: 9999,
    boxShadow: "0 12px 40px rgba(26,26,26,0.35), 0 0 0 1px rgba(41,190,228,0.15)",
    display: "flex",
    alignItems: "center",
    backdropFilter: "blur(12px)",
    letterSpacing: 0.2,
  },
  // Sidebar
  sidebar: {
    width: 260,
    minWidth: 260,
    background: "linear-gradient(180deg, #0F1724 0%, #162036 50%, #1A2744 100%)",
    color: "#F9FAFB",
    display: "flex",
    flexDirection: "column",
    padding: "0",
    overflowY: "auto",
    borderRight: "1px solid rgba(41,190,228,0.08)",
    boxShadow: "4px 0 24px rgba(0,0,0,0.15)",
  },
  logoArea: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "28px 20px 24px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  logoIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    background: "linear-gradient(135deg, #29BEE4 0%, #2E4E8D 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 15,
    color: "#fff",
    letterSpacing: 1,
    boxShadow: "0 4px 12px rgba(41,190,228,0.3)",
  },
  logoTitle: {
    fontWeight: 700,
    fontSize: 15,
    letterSpacing: 0.2,
    fontFamily: "'Outfit', sans-serif",
  },
  logoSub: {
    fontSize: 10,
    color: "#29BEE4",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginTop: 2,
    fontWeight: 600,
  },
  nav: {
    padding: "16px 12px 0",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "11px 14px",
    border: "none",
    borderRadius: 10,
    background: "transparent",
    color: "rgba(255,255,255,0.45)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "inherit",
    transition: "all 0.2s ease",
    letterSpacing: 0.1,
  },
  navActive: {
    background: "rgba(41,190,228,0.12)",
    color: "#29BEE4",
    fontWeight: 600,
    boxShadow: "inset 3px 0 0 #29BEE4",
  },
  navIcon: {
    fontSize: 16,
    width: 20,
    textAlign: "center",
  },
  sidebarSection: {
    padding: "20px 12px",
    borderTop: "1px solid rgba(255,255,255,0.05)",
    marginTop: 4,
  },
  sidebarLabel: {
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1.8,
    color: "rgba(255,255,255,0.25)",
    padding: "0 14px 10px",
    fontWeight: 700,
  },
  pipelineItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "9px 14px",
    border: "none",
    borderRadius: 8,
    background: "transparent",
    color: "rgba(255,255,255,0.45)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  badge: {
    background: "rgba(41,190,228,0.12)",
    borderRadius: 8,
    padding: "2px 9px",
    fontSize: 11,
    fontWeight: 700,
    color: "#29BEE4",
    minWidth: 22,
    textAlign: "center",
  },
  ruleCard: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "7px 14px",
    marginBottom: 2,
  },
  ruleEmoji: { fontSize: 13 },
  ruleText: { fontSize: 11, color: "rgba(255,255,255,0.3)", lineHeight: 1.4, fontWeight: 500 },
  // Main
  main: {
    flex: 1,
    padding: "36px 44px",
    overflowY: "auto",
    maxHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 32,
    flexWrap: "wrap",
    gap: 16,
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: 800,
    margin: 0,
    color: "#0F1724",
    fontFamily: "'Outfit', sans-serif",
    letterSpacing: -0.8,
  },
  pageSubtitle: {
    fontSize: 14,
    color: "#7A8BA0",
    margin: "6px 0 0",
    fontWeight: 500,
  },
  primaryBtn: {
    background: "linear-gradient(135deg, #2E4E8D 0%, #1084C3 100%)",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "11px 22px",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 4px 16px rgba(46,78,141,0.35), inset 0 1px 0 rgba(255,255,255,0.15)",
    transition: "all 0.2s ease",
    letterSpacing: 0.2,
  },
  secondaryBtn: {
    background: "#fff",
    color: "#2E4E8D",
    border: "1px solid #D5DCE6",
    borderRadius: 12,
    padding: "11px 22px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.2s",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  dangerBtn: {
    background: "#FFF5F3",
    color: "#DC4A3A",
    border: "1px solid #FECDC8",
    borderRadius: 12,
    padding: "11px 18px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  // Stats
  statsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: 16,
    marginBottom: 28,
  },
  statCard: {
    background: "#fff",
    borderRadius: 16,
    padding: "20px 22px",
    border: "1px solid rgba(0,0,0,0.05)",
    boxShadow: "0 2px 8px rgba(0,0,0,0.04), 0 0 0 1px rgba(0,0,0,0.02)",
  },
  statValue: {
    fontSize: 30,
    fontWeight: 800,
    fontFamily: "'Outfit', sans-serif",
    letterSpacing: -0.5,
  },
  statLabel: {
    fontSize: 11,
    color: "#7A8BA0",
    marginTop: 6,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  // Search
  searchBar: {
    position: "relative",
    marginBottom: 20,
  },
  searchIcon: {
    position: "absolute",
    left: 18,
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: 15,
    opacity: 0.5,
  },
  searchInput: {
    width: "100%",
    padding: "14px 18px 14px 48px",
    border: "1px solid rgba(0,0,0,0.08)",
    borderRadius: 14,
    fontSize: 14,
    fontFamily: "inherit",
    background: "#fff",
    color: "#1A1A1A",
    outline: "none",
    boxSizing: "border-box",
    boxShadow: "0 1px 4px rgba(0,0,0,0.03)",
    transition: "border-color 0.2s, box-shadow 0.2s",
    fontWeight: 500,
  },
  clearSearch: {
    position: "absolute",
    right: 14,
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    color: "#7A8BA0",
    cursor: "pointer",
    fontSize: 16,
  },
  // Cards Grid
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))",
    gap: 16,
  },
  cgCard: {
    background: "#fff",
    border: "1px solid rgba(0,0,0,0.06)",
    borderRadius: 18,
    padding: 22,
    cursor: "pointer",
    transition: "all 0.25s cubic-bezier(0.4,0,0.2,1)",
    textAlign: "left",
    fontFamily: "inherit",
    width: "100%",
    boxShadow: "0 2px 8px rgba(0,0,0,0.04), 0 0 0 1px rgba(0,0,0,0.02)",
    position: "relative",
  },
  cgCardUrgent: {
    borderColor: "#FECDC8",
    background: "linear-gradient(135deg, #FFFBFA, #FFF5F3)",
  },
  cgCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 16,
  },
  cgAvatar: {
    width: 44,
    height: 44,
    borderRadius: 13,
    background: "linear-gradient(135deg, #1B2A4A, #2E4E8D)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 14,
    color: "#fff",
    letterSpacing: 1,
    flexShrink: 0,
    boxShadow: "0 2px 8px rgba(46,78,141,0.2)",
  },
  cgName: {
    fontWeight: 700,
    fontSize: 15,
    color: "#0F1724",
    fontFamily: "'Outfit', sans-serif",
    letterSpacing: -0.1,
  },
  cgMeta: {
    fontSize: 12,
    color: "#7A8BA0",
    marginTop: 3,
    fontWeight: 500,
  },
  greenLightBadge: {
    background: "linear-gradient(135deg, #ECFDF3, #D1FAE5)",
    color: "#15803D",
    padding: "4px 12px",
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: "nowrap",
    border: "1px solid #BBF7D0",
  },
  urgentBadge: {
    background: "linear-gradient(135deg, #FFF5F3, #FEE2E2)",
    color: "#DC4A3A",
    padding: "4px 12px",
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: "nowrap",
    border: "1px solid #FECDC8",
  },
  cgPhaseRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  phaseBadge: {
    padding: "5px 14px",
    borderRadius: 9,
    fontSize: 12,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    letterSpacing: 0.1,
  },
  cgDays: {
    fontSize: 12,
    color: "#7A8BA0",
    fontWeight: 600,
  },
  miniProgressTrack: {
    display: "flex",
    gap: 3,
    marginBottom: 8,
  },
  miniSegment: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    background: "#EDF0F4",
    overflow: "hidden",
  },
  miniSegmentFill: {
    height: "100%",
    borderRadius: 3,
    transition: "width 0.5s cubic-bezier(0.4,0,0.2,1)",
  },
  miniProgressLabel: {
    fontSize: 11,
    color: "#7A8BA0",
    fontWeight: 600,
  },
  emptyState: {
    textAlign: "center",
    padding: "64px 24px",
    background: "#fff",
    borderRadius: 18,
    border: "1px solid rgba(0,0,0,0.05)",
    boxShadow: "0 2px 8px rgba(0,0,0,0.03)",
  },
  // Form
  formCard: {
    background: "#fff",
    borderRadius: 18,
    border: "1px solid rgba(0,0,0,0.05)",
    padding: "32px 36px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
  },
  formSection: {
    fontSize: 13,
    fontWeight: 700,
    color: "#2E4E8D",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    margin: "28px 0 16px",
    fontFamily: "'Outfit', sans-serif",
    borderBottom: "2px solid #EDF0F4",
    paddingBottom: 10,
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 16,
  },
  field: { marginBottom: 4 },
  fieldLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "#556270",
    marginBottom: 7,
    letterSpacing: 0.2,
  },
  fieldInput: {
    width: "100%",
    padding: "11px 14px",
    border: "1px solid #E0E4EA",
    borderRadius: 11,
    fontSize: 14,
    fontFamily: "inherit",
    background: "#F8F9FB",
    color: "#1A1A1A",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.2s, box-shadow 0.2s",
    fontWeight: 500,
  },
  radioRow: {
    display: "flex",
    gap: 16,
    marginTop: 4,
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "#556270",
    cursor: "pointer",
    fontWeight: 500,
  },
  radio: { accentColor: "#2E4E8D" },
  textarea: {
    width: "100%",
    padding: "11px 14px",
    border: "1px solid #E0E4EA",
    borderRadius: 11,
    fontSize: 14,
    fontFamily: "inherit",
    background: "#F8F9FB",
    color: "#1A1A1A",
    outline: "none",
    boxSizing: "border-box",
    resize: "vertical",
    fontWeight: 500,
  },
  formActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 28,
    paddingTop: 22,
    borderTop: "2px solid #EDF0F4",
  },
  // Detail View
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: 18,
    marginBottom: 28,
    flexWrap: "wrap",
  },
  backBtn: {
    background: "none",
    border: "none",
    color: "#7A8BA0",
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
    padding: "8px 0",
    fontWeight: 600,
    letterSpacing: 0.2,
  },
  detailAvatar: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background: "linear-gradient(135deg, #1B2A4A, #2E4E8D)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 19,
    color: "#fff",
    letterSpacing: 1,
    boxShadow: "0 4px 16px rgba(46,78,141,0.25)",
  },
  detailName: {
    fontSize: 26,
    fontWeight: 800,
    margin: 0,
    fontFamily: "'Outfit', sans-serif",
    letterSpacing: -0.5,
    color: "#0F1724",
  },
  detailMeta: {
    fontSize: 13,
    color: "#7A8BA0",
    marginTop: 4,
    fontWeight: 500,
  },
  greenLightBadgeLg: {
    background: "linear-gradient(135deg, #ECFDF3, #D1FAE5)",
    color: "#15803D",
    padding: "8px 18px",
    borderRadius: 12,
    fontSize: 13,
    fontWeight: 700,
    border: "1px solid #BBF7D0",
  },
  greenLightBtn: {
    background: "#fff",
    border: "1px solid #D5DCE6",
    borderRadius: 12,
    padding: "8px 18px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    color: "#2E4E8D",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  alertCard: {
    background: "linear-gradient(135deg, #FFFBFA, #FFF5F3)",
    border: "1px solid #FECDC8",
    borderRadius: 14,
    padding: 22,
    marginBottom: 20,
    fontSize: 14,
    color: "#1A1A1A",
  },
  greenLightCard: {
    background: "linear-gradient(135deg, #F0FDF4, #ECFDF3)",
    border: "1px solid #BBF7D0",
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
  },
  greenLightRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 0",
    borderBottom: "1px solid #D1FAE5",
    fontSize: 14,
    fontWeight: 500,
  },
  // Profile Card
  profileCard: {
    background: "#fff",
    borderRadius: 18,
    border: "1px solid rgba(0,0,0,0.05)",
    marginBottom: 20,
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
    overflow: "hidden",
  },
  profileCardHeader: {
    padding: "20px 24px 16px",
    borderBottom: "1px solid #EDF0F4",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileCardTitle: {
    fontSize: 17,
    fontWeight: 700,
    margin: 0,
    fontFamily: "'Outfit', sans-serif",
    color: "#0F1724",
    letterSpacing: -0.2,
  },
  editBtn: {
    background: "#fff",
    border: "1px solid #D5DCE6",
    borderRadius: 9,
    padding: "7px 16px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    color: "#2E4E8D",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  selectAllBtn: {
    background: "linear-gradient(135deg, #ECFDF3, #D1FAE5)",
    border: "1px solid #BBF7D0",
    borderRadius: 9,
    padding: "7px 16px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    color: "#15803D",
  },
  deselectAllBtn: {
    background: "linear-gradient(135deg, #FFF5F3, #FEE2E2)",
    border: "1px solid #FECDC8",
    borderRadius: 9,
    padding: "7px 16px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    color: "#DC4A3A",
  },
  // Export
  exportBtn: {
    background: "#fff",
    border: "1px solid #D5DCE6",
    borderRadius: 12,
    padding: "11px 20px",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
    color: "#2E4E8D",
    transition: "all 0.2s",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    letterSpacing: 0.1,
  },
  exportDropdown: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    background: "#fff",
    borderRadius: 14,
    boxShadow: "0 12px 40px rgba(0,0,0,0.15), 0 0 0 1px rgba(0,0,0,0.05)",
    padding: 8,
    minWidth: 270,
    zIndex: 100,
  },
  exportDropdownTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: "#7A8BA0",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    padding: "10px 14px 8px",
  },
  exportDropdownItem: {
    display: "block",
    width: "100%",
    padding: "12px 14px",
    border: "none",
    borderRadius: 10,
    background: "transparent",
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    transition: "background 0.1s",
  },
  exportItemLabel: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0F1724",
    marginBottom: 3,
  },
  exportItemDesc: {
    fontSize: 12,
    color: "#7A8BA0",
    fontWeight: 500,
  },
  profileGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 0,
    padding: "4px 0",
  },
  profileItem: {
    padding: "14px 24px",
    borderBottom: "1px solid #F0F3F7",
  },
  profileLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: "#7A8BA0",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 5,
  },
  profileValue: {
    fontSize: 14,
    color: "#0F1724",
    fontWeight: 600,
    lineHeight: 1.4,
  },
  // Progress
  progressOverview: {
    background: "#fff",
    borderRadius: 18,
    border: "1px solid rgba(0,0,0,0.05)",
    padding: 26,
    marginBottom: 20,
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
  },
  progressHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  progressTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: 700,
    color: "#0F1724",
    fontFamily: "'Outfit', sans-serif",
    letterSpacing: -0.2,
  },
  progressPct: {
    fontSize: 22,
    fontWeight: 800,
    color: "#2E4E8D",
    fontFamily: "'Outfit', sans-serif",
  },
  progressDays: {
    fontSize: 13,
    color: "#556270",
    background: "#EDF0F4",
    padding: "5px 14px",
    borderRadius: 9,
    fontWeight: 600,
  },
  progressTrack: {
    width: "100%",
    height: 10,
    borderRadius: 5,
    background: "#EDF0F4",
    overflow: "hidden",
    marginBottom: 20,
  },
  progressFill: {
    height: "100%",
    borderRadius: 5,
    background: "linear-gradient(90deg, #1B2A4A, #2E4E8D, #29BEE4)",
    transition: "width 0.6s cubic-bezier(0.4,0,0.2,1)",
  },
  // Phase Override
  phaseOverrideRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "14px 18px",
    background: "#F8F9FB",
    borderRadius: 12,
    marginBottom: 16,
    border: "1px solid #EDF0F4",
    flexWrap: "wrap",
  },
  phaseOverrideLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  phaseOverrideLabel: {
    fontSize: 13,
    fontWeight: 700,
    color: "#556270",
    flexShrink: 0,
  },
  phaseOverrideRight: {
    flexShrink: 0,
  },
  phaseOverrideSelect: {
    padding: "7px 14px",
    border: "1px solid #D5DCE6",
    borderRadius: 9,
    fontSize: 13,
    fontFamily: "inherit",
    color: "#1A1A1A",
    background: "#fff",
    cursor: "pointer",
    outline: "none",
    minWidth: 200,
    fontWeight: 500,
  },
  overrideBadge: {
    background: "linear-gradient(135deg, #FFF8ED, #FEF3C7)",
    color: "#B45309",
    padding: "3px 12px",
    borderRadius: 7,
    fontSize: 11,
    fontWeight: 700,
    border: "1px solid #FDE68A",
    flexShrink: 0,
  },
  phaseNav: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  phaseTab: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 16px",
    borderRadius: 11,
    border: "1px solid #EDF0F4",
    background: "#F8F9FB",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 600,
    color: "#556270",
    transition: "all 0.2s ease",
  },
  phaseTabLabel: {
    display: "inline",
  },
  phaseTabPct: {
    fontSize: 11,
    fontWeight: 700,
    opacity: 0.6,
  },
  // Phase Detail
  phaseDetail: {
    background: "#fff",
    borderRadius: 18,
    border: "1px solid rgba(0,0,0,0.05)",
    padding: 26,
    marginBottom: 20,
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
  },
  phaseDetailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 22,
    flexWrap: "wrap",
    gap: 12,
  },
  phaseDetailTitle: {
    fontSize: 19,
    fontWeight: 800,
    margin: 0,
    fontFamily: "'Outfit', sans-serif",
    letterSpacing: -0.3,
    color: "#0F1724",
  },
  phaseDetailSub: {
    fontSize: 13,
    color: "#7A8BA0",
    margin: "5px 0 0",
    fontWeight: 500,
  },
  scriptBtn: {
    background: "#fff",
    border: "1px solid #C6DFF0",
    borderRadius: 11,
    padding: "9px 18px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    color: "#1084C3",
    whiteSpace: "nowrap",
    boxShadow: "0 1px 3px rgba(16,132,195,0.08)",
  },
  scriptsPanel: {
    background: "linear-gradient(135deg, #F0F7FC, #EBF5FB)",
    border: "1px solid #C6DFF0",
    borderRadius: 14,
    padding: 22,
    marginBottom: 20,
  },
  scriptsPanelTitle: {
    margin: "0 0 16px",
    fontSize: 15,
    fontWeight: 700,
    color: "#1084C3",
    fontFamily: "'Outfit', sans-serif",
  },
  scriptRow: {
    display: "flex",
    gap: 16,
    padding: "12px 0",
    borderBottom: "1px solid #C6DFF0",
  },
  scriptDay: {
    fontWeight: 800,
    fontSize: 11,
    color: "#1084C3",
    minWidth: 60,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  scriptAction: {
    fontWeight: 700,
    fontSize: 13,
    color: "#0F1724",
    marginBottom: 4,
  },
  scriptText: {
    fontSize: 13,
    color: "#556270",
    fontStyle: "italic",
    lineHeight: 1.6,
  },
  // Tasks
  taskList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  taskRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "13px 16px",
    borderRadius: 11,
    cursor: "pointer",
    transition: "background 0.15s",
    fontSize: 14,
    color: "#1A1A1A",
    fontWeight: 500,
  },
  taskRowDone: {
    background: "#F8F9FB",
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    border: "2px solid #D5DCE6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
    flexShrink: 0,
    cursor: "pointer",
    transition: "all 0.2s cubic-bezier(0.4,0,0.2,1)",
  },
  checkboxDone: {
    background: "linear-gradient(135deg, #22C55E, #16A34A)",
    borderColor: "#16A34A",
    boxShadow: "0 2px 6px rgba(22,163,74,0.25)",
  },
  criticalBadge: {
    display: "inline-block",
    marginLeft: 8,
    background: "linear-gradient(135deg, #EDF0F8, #E0E7F0)",
    color: "#2E4E8D",
    padding: "2px 9px",
    borderRadius: 6,
    fontSize: 10,
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  // Notes
  notesSection: {
    background: "#fff",
    borderRadius: 18,
    border: "1px solid rgba(0,0,0,0.05)",
    padding: 26,
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
  },
  notesSectionTitle: {
    fontSize: 17,
    fontWeight: 700,
    margin: "0 0 18px",
    fontFamily: "'Outfit', sans-serif",
    color: "#0F1724",
    letterSpacing: -0.2,
  },
  noteInputRow: {
    display: "flex",
    gap: 10,
    marginBottom: 18,
  },
  noteInput: {
    flex: 1,
    padding: "11px 14px",
    border: "1px solid #E0E4EA",
    borderRadius: 11,
    fontSize: 14,
    fontFamily: "inherit",
    background: "#F8F9FB",
    color: "#1A1A1A",
    outline: "none",
    fontWeight: 500,
  },
  notesList: {
    maxHeight: 300,
    overflowY: "auto",
  },
  noteItem: {
    padding: "12px 0",
    borderBottom: "1px solid #EDF1F5",
  },
  noteTimestamp: {
    fontSize: 11,
    color: "#1084C3",
    fontWeight: 700,
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  noteText: {
    fontSize: 14,
    color: "#1A1A1A",
    lineHeight: 1.6,
    fontWeight: 500,
  },
};

// ─── Auth Styles ──────────────────────────────────────────────
export const authStyles = {
  wrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    background: "linear-gradient(135deg, #0F1724 0%, #1B2A4A 40%, #2E4E8D 100%)",
    fontFamily: "'Plus Jakarta Sans', 'Helvetica Neue', sans-serif",
    padding: 20,
  },
  card: {
    background: "#fff",
    borderRadius: 24,
    padding: "52px 44px",
    width: "100%",
    maxWidth: 400,
    textAlign: "center",
    boxShadow: "0 24px 80px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.05)",
  },
  logoIcon: {
    width: 60,
    height: 60,
    borderRadius: 16,
    background: "linear-gradient(135deg, #29BEE4 0%, #2E4E8D 100%)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 22,
    color: "#fff",
    letterSpacing: 1,
    marginBottom: 20,
    boxShadow: "0 8px 24px rgba(41,190,228,0.3)",
  },
  title: {
    fontSize: 28,
    fontWeight: 800,
    margin: "0 0 6px",
    color: "#0F1724",
    letterSpacing: -0.5,
    fontFamily: "'Outfit', sans-serif",
  },
  subtitle: {
    fontSize: 14,
    color: "#7A8BA0",
    margin: 0,
    fontWeight: 500,
  },
  divider: {
    height: 1,
    background: "#EDF0F4",
    margin: "28px 0",
  },
  prompt: {
    fontSize: 14,
    color: "#556270",
    margin: "0 0 16px",
    fontWeight: 500,
  },
  input: {
    width: "100%",
    padding: "14px 18px",
    border: "2px solid #E0E4EA",
    borderRadius: 12,
    fontSize: 16,
    fontFamily: "inherit",
    color: "#0F1724",
    outline: "none",
    boxSizing: "border-box",
    textAlign: "center",
    letterSpacing: 2,
    transition: "border-color 0.2s, box-shadow 0.2s",
    fontWeight: 600,
  },
  error: {
    color: "#DC4A3A",
    fontSize: 13,
    margin: "10px 0 0",
    fontWeight: 600,
  },
  button: {
    width: "100%",
    padding: "14px",
    background: "linear-gradient(135deg, #2E4E8D 0%, #1084C3 100%)",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    marginTop: 18,
    boxShadow: "0 4px 16px rgba(46,78,141,0.35), inset 0 1px 0 rgba(255,255,255,0.15)",
    letterSpacing: 0.3,
  },
  footer: {
    fontSize: 12,
    color: "#7A8BA0",
    margin: "24px 0 0",
    fontWeight: 500,
  },
};

// ─── Board Styles ─────────────────────────────────────────────
export const boardStyles = {
  unassignedBanner: {
    background: "#EBF5FB",
    border: "1px solid #C6DFF0",
    borderRadius: 14,
    padding: 20,
    marginBottom: 24,
  },
  unassignedTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "#1A1A1A",
    marginBottom: 4,
  },
  unassignedDesc: {
    fontSize: 13,
    color: "#556270",
    marginBottom: 14,
  },
  unassignedCards: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  unassignedCard: {
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: 10,
    padding: "12px 14px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  unassignedCardName: {
    fontSize: 14,
    fontWeight: 600,
    color: "#1A1A1A",
  },
  unassignedCardActions: {
    display: "flex",
    gap: 4,
  },
  assignBtn: {
    padding: "4px 8px",
    borderRadius: 6,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.15s",
  },
  columnsContainer: {
    display: "grid",
    gap: 16,
    minHeight: 400,
    overflowX: "auto",
    paddingBottom: 8,
  },
  column: {
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #E2E8F0",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    minHeight: 300,
    minWidth: 240,
    boxShadow: "0 2px 6px rgba(0,0,0,0.06)",
    overflow: "hidden",
    transition: "opacity 0.15s",
  },
  columnHeaderBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 14px",
    cursor: "grab",
    borderRadius: "13px 13px 0 0",
  },
  columnGrip: {
    fontSize: 14,
    color: "rgba(255,255,255,0.5)",
    letterSpacing: 1,
    flexShrink: 0,
    cursor: "grab",
  },
  columnTitleWhite: {
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
    flex: 1,
    letterSpacing: 0.2,
  },
  columnCountWhite: {
    padding: "2px 8px",
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 700,
    background: "rgba(255,255,255,0.25)",
    color: "#fff",
  },
  columnDesc: {
    fontSize: 11,
    color: "#6B7B8F",
    padding: "0 16px 12px",
    borderBottom: "1px solid #E2E8F0",
    lineHeight: 1.3,
  },
  columnBody: {
    flex: 1,
    padding: "6px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    overflowY: "auto",
    background: "#F5F7FA",
  },
  columnEmpty: {
    textAlign: "center",
    padding: "32px 12px",
    color: "#A0AEC0",
    fontSize: 12,
    fontStyle: "italic",
    border: "2px dashed #E2E8F0",
    borderRadius: 10,
    margin: 4,
  },
  card: {
    background: "#fff",
    borderRadius: 8,
    padding: "8px 10px",
    boxShadow: "0 1px 2px rgba(0,0,0,0.08)",
    cursor: "grab",
    transition: "opacity 0.15s, box-shadow 0.15s",
    border: "1px solid #E8ECF0",
  },
  cardTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
    marginBottom: 3,
  },
  cardName: {
    fontSize: 13,
    fontWeight: 700,
    color: "#1A1A1A",
    cursor: "pointer",
    flex: 1,
    lineHeight: 1.3,
    letterSpacing: -0.1,
  },
  cardMoveMenu: {
    flexShrink: 0,
  },
  cardMoveSelect: {
    fontSize: 10,
    border: "1px solid #E2E8F0",
    borderRadius: 4,
    padding: "1px 3px",
    background: "#F5F7FA",
    color: "#6B7B8F",
    fontFamily: "inherit",
    cursor: "pointer",
    maxWidth: 72,
    outline: "none",
  },
  cardDetails: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 2,
  },
  cardDetail: {
    fontSize: 11,
    color: "#8895A7",
    letterSpacing: -0.1,
  },
  cardMoved: {
    fontSize: 10,
    color: "#B0B9C6",
    marginTop: 2,
    letterSpacing: -0.1,
  },
  cardNote: {
    fontSize: 11,
    color: "#556270",
    marginTop: 5,
    padding: "5px 7px",
    background: "#F5F7FA",
    borderRadius: 5,
    cursor: "pointer",
    lineHeight: 1.35,
    minHeight: 16,
  },
  cardNoteEdit: {
    display: "flex",
    gap: 4,
    marginTop: 5,
  },
  cardNoteInput: {
    flex: 1,
    fontSize: 11,
    padding: "4px 7px",
    border: "1px solid #29BEE4",
    borderRadius: 5,
    fontFamily: "inherit",
    color: "#1A1A1A",
    outline: "none",
    background: "#fff",
  },
  cardNoteSave: {
    background: "#2E4E8D",
    color: "#fff",
    border: "none",
    borderRadius: 5,
    padding: "4px 7px",
    fontSize: 11,
    cursor: "pointer",
    fontWeight: 700,
  },
  // Column management
  columnActions: {
    display: "flex",
    gap: 2,
    padding: "4px 12px 2px",
  },
  colActionBtn: {
    background: "none",
    border: "none",
    fontSize: 12,
    cursor: "pointer",
    padding: "2px 6px",
    borderRadius: 4,
    color: "#6B7B8F",
    fontFamily: "inherit",
  },
  colFormOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(26,26,26,0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
    padding: 24,
    backdropFilter: "blur(3px)",
  },
  colFormModal: {
    background: "#fff",
    borderRadius: 16,
    padding: "28px 28px",
    width: "100%",
    maxWidth: 480,
    boxShadow: "0 20px 60px rgba(0,0,0,0.25)",
  },
  iconPicker: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 6,
  },
  iconOption: {
    width: 36,
    height: 36,
    borderRadius: 8,
    border: "2px solid #E2E8F0",
    background: "#F9FAFB",
    fontSize: 18,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.1s",
  },
  colorPicker: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  colorOption: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "none",
    cursor: "pointer",
    transition: "all 0.1s",
  },
  // Card Detail Modal
  modalContainer: {
    background: "#fff",
    borderRadius: 20,
    width: "100%",
    maxWidth: 580,
    maxHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 24px 80px rgba(0,0,0,0.3)",
    overflow: "hidden",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "20px 24px",
    borderBottom: "1px solid #E2E8F0",
    flexShrink: 0,
  },
  modalAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: "linear-gradient(135deg, #2E4E8D, #29BEE4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 16,
    color: "#fff",
    flexShrink: 0,
  },
  modalName: {
    fontSize: 18,
    fontWeight: 700,
    color: "#1A1A1A",
  },
  modalStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  modalStatusLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "#556270",
  },
  modalCloseBtn: {
    background: "#F0F3F7",
    border: "none",
    width: 32,
    height: 32,
    borderRadius: 8,
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#556270",
    flexShrink: 0,
  },
  modalBody: {
    flex: 1,
    overflowY: "auto",
    padding: "8px 24px 16px",
  },
  modalSection: {
    marginBottom: 20,
  },
  modalSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "#6B7B8F",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  modalInfoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
  },
  modalInfoItem: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    padding: "8px 10px",
    background: "#F9FAFB",
    borderRadius: 8,
  },
  modalInfoIcon: {
    fontSize: 14,
    marginTop: 1,
    flexShrink: 0,
  },
  modalInfoLabel: {
    fontSize: 10,
    fontWeight: 600,
    color: "#6B7B8F",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  modalInfoValue: {
    fontSize: 13,
    fontWeight: 500,
    color: "#1A1A1A",
    marginTop: 1,
    wordBreak: "break-word",
  },
  modalProgressRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  modalProgressTrack: {
    flex: 1,
    height: 8,
    background: "#E2E8F0",
    borderRadius: 4,
    overflow: "hidden",
  },
  modalProgressFill: {
    height: "100%",
    background: "linear-gradient(90deg, #2E4E8D, #29BEE4)",
    borderRadius: 4,
    transition: "width 0.3s",
  },
  modalProgressPct: {
    fontSize: 14,
    fontWeight: 700,
    color: "#2E4E8D",
    minWidth: 36,
    textAlign: "right",
  },
  modalProgressMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  modalPhasePill: {
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 8px",
    background: "#F0F3F7",
    borderRadius: 6,
  },
  modalMoveRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  modalMoveBtn: {
    padding: "6px 12px",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    background: "#fff",
    transition: "all 0.1s",
  },
  modalNoteTextarea: {
    width: "100%",
    padding: "10px 12px",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    fontSize: 13,
    fontFamily: "inherit",
    color: "#1A1A1A",
    resize: "vertical",
    outline: "none",
    boxSizing: "border-box",
    minHeight: 48,
  },
  modalActivityInput: {
    display: "flex",
    gap: 6,
    marginBottom: 8,
  },
  modalActivityField: {
    flex: 1,
    padding: "8px 12px",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    fontSize: 13,
    fontFamily: "inherit",
    color: "#1A1A1A",
    outline: "none",
  },
  modalActivityBtn: {
    background: "#2E4E8D",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  modalNotesList: {
    maxHeight: 150,
    overflowY: "auto",
  },
  modalNoteItem: {
    display: "flex",
    gap: 10,
    padding: "6px 0",
    borderBottom: "1px solid #F0F3F7",
    alignItems: "baseline",
  },
  modalNoteTime: {
    fontSize: 11,
    color: "#A0AEC0",
    flexShrink: 0,
    minWidth: 80,
  },
  modalNoteText: {
    fontSize: 13,
    color: "#1A1A1A",
  },
  modalFooter: {
    padding: "14px 24px",
    borderTop: "1px solid #E2E8F0",
    display: "flex",
    justifyContent: "flex-end",
    flexShrink: 0,
  },
};

// ─── Action Item Styles ───────────────────────────────────────
export const actionStyles = {
  panel: {
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #E2E8F0",
    marginBottom: 24,
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    overflow: "hidden",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    borderBottom: "1px solid #E2E8F0",
    flexWrap: "wrap",
    gap: 8,
  },
  panelTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  panelIcon: {
    fontSize: 18,
  },
  panelTitle: {
    fontSize: 15,
    fontWeight: 700,
    margin: 0,
    color: "#1A1A1A",
    fontFamily: "'Outfit', sans-serif",
  },
  panelCount: {
    background: "#2E4E8D",
    color: "#fff",
    padding: "2px 8px",
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 700,
  },
  panelBadges: {
    display: "flex",
    gap: 6,
  },
  criticalCount: {
    background: "#FEF2F0",
    color: "#DC3545",
    padding: "3px 10px",
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 700,
  },
  warningCount: {
    background: "#FFF8ED",
    color: "#D97706",
    padding: "3px 10px",
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 700,
  },
  list: {
    padding: "4px 12px",
  },
  item: {
    padding: "14px 16px",
    borderLeft: "3px solid",
    borderRadius: "0 8px 8px 0",
    margin: "6px 0",
    background: "#F9FAFB",
    cursor: "pointer",
    transition: "background 0.1s",
  },
  itemTop: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  itemIcon: {
    fontSize: 18,
    flexShrink: 0,
  },
  itemTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "#1A1A1A",
  },
  itemName: {
    fontSize: 12,
    color: "#6B7B8F",
    fontWeight: 500,
  },
  urgencyBadge: {
    padding: "3px 10px",
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  },
  itemDetail: {
    fontSize: 13,
    color: "#556270",
    marginLeft: 28,
    lineHeight: 1.4,
  },
  itemAction: {
    fontSize: 12,
    color: "#2E4E8D",
    fontWeight: 600,
    marginLeft: 28,
    marginTop: 6,
  },
  showMore: {
    width: "100%",
    padding: "12px",
    border: "none",
    borderTop: "1px solid #E2E8F0",
    background: "transparent",
    color: "#2E4E8D",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
};

// ─── Task Editor Styles ───────────────────────────────────────
export const taskEditStyles = {
  row: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 8px",
    background: "#F9FAFB",
    borderRadius: 8,
    marginBottom: 4,
    border: "1px solid #E2E8F0",
  },
  handle: {
    fontSize: 12,
    color: "#B0B9C6",
    cursor: "grab",
    flexShrink: 0,
  },
  input: {
    flex: 1,
    padding: "6px 8px",
    border: "1px solid #E2E8F0",
    borderRadius: 6,
    fontSize: 13,
    fontFamily: "inherit",
    color: "#1A1A1A",
    outline: "none",
    background: "#fff",
  },
  criticalToggle: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    flexShrink: 0,
    cursor: "pointer",
    fontSize: 11,
  },
  criticalLabel: {
    fontSize: 10,
    fontWeight: 600,
    color: "#6B7B8F",
  },
  moveBtn: {
    background: "none",
    border: "1px solid #E2E8F0",
    borderRadius: 4,
    padding: "2px 6px",
    fontSize: 11,
    cursor: "pointer",
    color: "#6B7B8F",
    fontFamily: "inherit",
    flexShrink: 0,
  },
  deleteBtn: {
    background: "none",
    border: "none",
    fontSize: 14,
    cursor: "pointer",
    color: "#DC3545",
    padding: "2px 4px",
    flexShrink: 0,
  },
  addBtn: {
    width: "100%",
    padding: "10px",
    border: "2px dashed #D0D9E4",
    borderRadius: 8,
    background: "transparent",
    color: "#2E4E8D",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    marginTop: 4,
  },
};

// ─── Bulk Action Styles ───────────────────────────────────────
export const bulkStyles = {
  // Selection bar above cards
  selectionBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    padding: "0 4px",
  },
  selectionLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  selectionCount: {
    fontSize: 13,
    fontWeight: 700,
    color: "#2E4E8D",
  },
  selectAllLink: {
    background: "none",
    border: "none",
    color: "#1084C3",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    padding: 0,
    textDecoration: "underline",
  },
  clearLink: {
    background: "none",
    border: "none",
    color: "#6B7B8F",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
    padding: 0,
    textDecoration: "underline",
  },
  selectHint: {
    fontSize: 12,
    color: "#A0AEC0",
    fontStyle: "italic",
  },
  // Card checkbox
  cardCheckbox: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 22,
    height: 22,
    borderRadius: 6,
    border: "2px solid #D0D9E4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 700,
    color: "#fff",
    cursor: "pointer",
    background: "#fff",
    transition: "all 0.15s",
    opacity: 0,
    zIndex: 2,
  },
  cardCheckboxChecked: {
    background: "#2E4E8D",
    borderColor: "#2E4E8D",
    opacity: 1,
  },
  cgCardSelected: {
    borderColor: "#2E4E8D",
    boxShadow: "0 0 0 2px rgba(46,78,141,0.2)",
    background: "#F0F4FA",
  },
  // Floating action bar
  actionBar: {
    position: "fixed",
    bottom: 0,
    left: 260,
    right: 0,
    zIndex: 9000,
    padding: "0 20px 20px",
    pointerEvents: "none",
  },
  actionBarInner: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "14px 20px",
    background: "#1A1A1A",
    borderRadius: 14,
    boxShadow: "0 8px 40px rgba(0,0,0,0.35)",
    pointerEvents: "auto",
    flexWrap: "wrap",
  },
  actionBarLeft: {
    flexShrink: 0,
  },
  actionBarCount: {
    fontSize: 14,
    fontWeight: 600,
    color: "#fff",
  },
  actionBarActions: {
    display: "flex",
    gap: 6,
    flex: 1,
    flexWrap: "wrap",
  },
  actionGroup: {
    position: "relative",
  },
  actionBtn: {
    background: "rgba(255,255,255,0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 600,
    color: "#fff",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.1s",
    whiteSpace: "nowrap",
  },
  actionBtnActive: {
    background: "#2E4E8D",
    borderColor: "#29BEE4",
  },
  actionDropdown: {
    position: "absolute",
    bottom: "calc(100% + 8px)",
    left: 0,
    background: "#fff",
    borderRadius: 10,
    boxShadow: "0 8px 32px rgba(0,0,0,0.2)",
    border: "1px solid #E2E8F0",
    padding: 6,
    minWidth: 200,
    zIndex: 10,
  },
  dropdownItem: {
    display: "block",
    width: "100%",
    padding: "10px 12px",
    border: "none",
    borderRadius: 6,
    background: "transparent",
    fontSize: 13,
    fontWeight: 500,
    color: "#1A1A1A",
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    transition: "background 0.1s",
  },
  dropdownInput: {
    width: "100%",
    padding: "10px 12px",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    fontSize: 13,
    fontFamily: "inherit",
    color: "#1A1A1A",
    outline: "none",
    marginBottom: 8,
    boxSizing: "border-box",
  },
  dropdownApply: {
    width: "100%",
    padding: "8px",
    background: "linear-gradient(135deg, #2E4E8D, #1084C3)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  dropdownWarning: {
    fontSize: 13,
    color: "#E85D4A",
    fontWeight: 500,
    marginBottom: 10,
    lineHeight: 1.4,
  },
  dropdownDanger: {
    flex: 1,
    padding: "8px",
    background: "#E85D4A",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  dropdownCancel: {
    flex: 1,
    padding: "8px",
    background: "#EEF2F7",
    color: "#1A1A1A",
    border: "1px solid #D0D9E4",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  actionBarClose: {
    background: "rgba(255,255,255,0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: 8,
    width: 36,
    height: 36,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    color: "#fff",
    cursor: "pointer",
    flexShrink: 0,
    marginLeft: "auto",
  },
};

// ─── Orientation Styles ───────────────────────────────────────
export const orientStyles = {
    banner: {
      background: "linear-gradient(135deg, #0EA5C9 0%, #2E4E8D 100%)",
      borderRadius: 12,
      padding: 0,
      marginBottom: 16,
      overflow: "hidden",
      color: "#fff",
    },
    bannerTop: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
      padding: "18px 20px 14px",
      gap: 12,
      flexWrap: "wrap",
    },
    bannerLabel: {
      fontSize: 11,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: 1,
      opacity: 0.7,
      marginBottom: 4,
    },
    bannerDate: {
      fontSize: 22,
      fontWeight: 700,
      lineHeight: 1.2,
    },
    bannerTime: {
      fontSize: 13,
      opacity: 0.8,
      marginTop: 2,
    },
    bannerLocation: {
      fontSize: 12,
      opacity: 0.7,
      marginTop: 2,
    },
    countdownBox: {
      textAlign: "right",
    },
    countdownValue: {
      fontSize: 20,
      fontWeight: 800,
      lineHeight: 1.2,
    },
    countdownSub: {
      fontSize: 11,
      opacity: 0.7,
      marginTop: 2,
    },
    editBtnWhite: {
      background: "rgba(255,255,255,0.2)",
      border: "1px solid rgba(255,255,255,0.3)",
      borderRadius: 6,
      padding: "4px 10px",
      fontSize: 11,
      fontWeight: 600,
      color: "#fff",
      cursor: "pointer",
      fontFamily: "inherit",
      marginTop: 6,
    },
    bannerBottom: {
      background: "rgba(0,0,0,0.15)",
      padding: "12px 20px",
      display: "flex",
      alignItems: "center",
      gap: 14,
    },
    goalLabel: {
      fontSize: 12,
      fontWeight: 600,
      flexShrink: 0,
    },
    goalTrack: {
      flex: 1,
      height: 8,
      background: "rgba(255,255,255,0.2)",
      borderRadius: 4,
      overflow: "hidden",
    },
    goalFill: {
      height: "100%",
      borderRadius: 4,
      transition: "width 0.3s",
    },
    goalCount: {
      fontSize: 13,
      fontWeight: 700,
      flexShrink: 0,
    },
    noDate: {
      padding: "20px",
      textAlign: "center",
    },
    noDateTitle: {
      fontSize: 15,
      fontWeight: 600,
      marginBottom: 4,
    },
    noDateSub: {
      fontSize: 12,
      opacity: 0.7,
      marginBottom: 12,
    },
    editOverlay: {
      background: "rgba(0,0,0,0.15)",
      padding: "16px 20px",
    },
    editGrid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 10,
      marginBottom: 12,
    },
    editLabel: {
      fontSize: 11,
      fontWeight: 600,
      opacity: 0.8,
      marginBottom: 4,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    editInput: {
      width: "100%",
      padding: "7px 10px",
      border: "1px solid rgba(255,255,255,0.3)",
      borderRadius: 6,
      fontSize: 13,
      fontFamily: "inherit",
      color: "#fff",
      background: "rgba(255,255,255,0.1)",
      outline: "none",
      boxSizing: "border-box",
    },
    editActions: {
      display: "flex",
      gap: 8,
      justifyContent: "flex-end",
    },
    saveBtnWhite: {
      background: "#fff",
      color: "#2E4E8D",
      border: "none",
      borderRadius: 6,
      padding: "6px 16px",
      fontSize: 12,
      fontWeight: 700,
      cursor: "pointer",
      fontFamily: "inherit",
    },
    cancelBtnWhite: {
      background: "rgba(255,255,255,0.15)",
      color: "#fff",
      border: "1px solid rgba(255,255,255,0.3)",
      borderRadius: 6,
      padding: "6px 14px",
      fontSize: 12,
      fontWeight: 600,
      cursor: "pointer",
      fontFamily: "inherit",
    },
};

// ─── Chat Widget Styles ──────────────────────────────────────
export const chatStyles = {
  fab: {
    position: "fixed",
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 16,
    background: "linear-gradient(135deg, #2E4E8D 0%, #29BEE4 100%)",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    boxShadow: "0 8px 32px rgba(46,78,141,0.4), 0 0 0 1px rgba(41,190,228,0.2)",
    zIndex: 9900,
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  panel: {
    position: "fixed",
    bottom: 92,
    right: 24,
    width: 400,
    maxHeight: "70vh",
    background: "#fff",
    borderRadius: 20,
    boxShadow: "0 20px 60px rgba(0,0,0,0.2), 0 0 0 1px rgba(0,0,0,0.05)",
    zIndex: 9900,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    fontFamily: "'Plus Jakarta Sans', 'Helvetica Neue', sans-serif",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "18px 20px",
    background: "linear-gradient(135deg, #0F1724 0%, #1B2A4A 100%)",
    color: "#fff",
    flexShrink: 0,
  },
  headerIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: "linear-gradient(135deg, #29BEE4 0%, #2E4E8D 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: 700,
    fontFamily: "'Outfit', sans-serif",
  },
  headerSub: {
    fontSize: 11,
    color: "rgba(255,255,255,0.6)",
    marginTop: 1,
  },
  closeBtn: {
    marginLeft: "auto",
    background: "rgba(255,255,255,0.1)",
    border: "none",
    color: "#fff",
    width: 30,
    height: 30,
    borderRadius: 8,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    padding: "16px 16px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minHeight: 200,
    maxHeight: "50vh",
  },
  msgUser: {
    alignSelf: "flex-end",
    background: "linear-gradient(135deg, #2E4E8D, #1084C3)",
    color: "#fff",
    padding: "10px 14px",
    borderRadius: "14px 14px 4px 14px",
    maxWidth: "80%",
    fontSize: 14,
    lineHeight: 1.5,
    fontWeight: 500,
    wordBreak: "break-word",
  },
  msgAssistant: {
    alignSelf: "flex-start",
    background: "#F0F2F5",
    color: "#1A1A1A",
    padding: "10px 14px",
    borderRadius: "14px 14px 14px 4px",
    maxWidth: "85%",
    fontSize: 14,
    lineHeight: 1.6,
    fontWeight: 500,
    wordBreak: "break-word",
  },
  typing: {
    alignSelf: "flex-start",
    background: "#F0F2F5",
    padding: "12px 18px",
    borderRadius: "14px 14px 14px 4px",
    fontSize: 14,
    color: "#7A8BA0",
    fontStyle: "italic",
  },
  inputArea: {
    display: "flex",
    gap: 8,
    padding: "12px 16px 16px",
    borderTop: "1px solid #EDF0F4",
    background: "#fff",
    flexShrink: 0,
  },
  input: {
    flex: 1,
    padding: "10px 14px",
    border: "1px solid #E0E4EA",
    borderRadius: 12,
    fontSize: 14,
    fontFamily: "inherit",
    color: "#1A1A1A",
    outline: "none",
    background: "#F8F9FB",
    fontWeight: 500,
  },
  sendBtn: {
    background: "linear-gradient(135deg, #2E4E8D, #1084C3)",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "10px 16px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    flexShrink: 0,
  },
  sendBtnDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  welcome: {
    textAlign: "center",
    padding: "8px 12px",
    fontSize: 13,
    color: "#7A8BA0",
    lineHeight: 1.5,
  },
  errorMsg: {
    alignSelf: "center",
    background: "#FFF5F3",
    color: "#DC4A3A",
    padding: "8px 14px",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 600,
    border: "1px solid #FECDC8",
  },
};
