import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { FieldRenderer } from './FieldRenderer';
import { useAutosave } from './useAutosave';
import { saveDraft } from './storage';
import { sectionUsesTasks } from './sections';
import { TaskEditor } from './TaskEditor';
import btn from '../../styles/buttons.module.css';
import s from './SectionEditor.module.css';

// ═══════════════════════════════════════════════════════════════
// SectionEditor
//
// Slide-in drawer for editing a single care plan section. Every
// field change is debounced (1s) and persisted via saveDraft.
// An auto-dismissing "Saved" indicator tells the user the latest
// change landed without requiring an explicit Save button.
//
// Closing the drawer flushes any pending save so we don't lose the
// last keystroke.
//
// For ADL / IADL sections, the TaskEditor component is rendered
// below the structured fields to manage the task list.
// ═══════════════════════════════════════════════════════════════

export function SectionEditor({
  section,
  version,
  currentUser,
  onClose,
  onSaved,
  showToast,
}) {
  // Local editing state — seeded from the version's saved data.
  const initialSectionData = (version?.data && version.data[section.id]) || {};
  const [values, setValues] = useState(initialSectionData);
  // Reset local state if the user switches sections without closing.
  useEffect(() => {
    setValues(initialSectionData);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [section?.id, version?.id]);

  // Keep a ref of the latest accumulated patch so batched saves see
  // everything the user's typed since the last successful save.
  const pendingPatchRef = useRef({});

  const saveFn = useCallback(async (patch) => {
    const userId = currentUser?.displayName || currentUser?.email || null;
    const updated = await saveDraft(version.id, section.id, patch, { userId });
    pendingPatchRef.current = {};
    onSaved?.(updated);
    return updated;
  }, [currentUser, section?.id, version?.id, onSaved]);

  const { trigger, flush, state, error } = useAutosave(saveFn, { delay: 1000 });

  // Flush pending saves on unmount / close so the last change lands.
  useEffect(() => () => { flush(); }, [flush]);

  const handleFieldChange = useCallback((fieldId, newValue) => {
    setValues((prev) => ({ ...prev, [fieldId]: newValue }));
    pendingPatchRef.current = { ...pendingPatchRef.current, [fieldId]: newValue };
    trigger({ ...pendingPatchRef.current });
  }, [trigger]);

  const handleClose = useCallback(async () => {
    await flush();
    onClose?.();
  }, [flush, onClose]);

  const readOnly = version?.status !== 'draft';
  const disabled = readOnly;

  const indicator = useMemo(() => {
    if (error) return { label: 'Couldn\'t save — try again', tone: 'error' };
    switch (state) {
      case 'idle':    return { label: null,            tone: 'idle' };
      case 'pending': return { label: 'Change queued', tone: 'pending' };
      case 'saving':  return { label: 'Saving…',       tone: 'saving' };
      case 'saved':   return { label: 'Saved',         tone: 'saved' };
      case 'error':   return { label: 'Save failed',   tone: 'error' };
      default:        return { label: null,            tone: 'idle' };
    }
  }, [state, error]);

  const usesTasks = sectionUsesTasks(section);

  return (
    <div className={s.backdrop} onClick={handleClose}>
      <aside
        className={s.drawer}
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-label={`Edit ${section.label}`}
      >
        <header className={s.header}>
          <div>
            <div className={s.eyebrow}>
              Editing v{version?.versionNumber ?? '?'} draft
              {section.isAutoGenerated && ' · AI-generated'}
            </div>
            <h2 className={s.title}>{section.label}</h2>
            <p className={s.description}>{section.description}</p>
          </div>
          <button
            className={s.closeBtn}
            onClick={handleClose}
            aria-label="Close drawer"
          >
            ✕
          </button>
        </header>

        <div className={s.body}>
          {readOnly && (
            <div className={s.readOnlyBanner}>
              This version is {version?.status}. To make changes, start a new draft.
            </div>
          )}

          {error && (
            <div className={s.errorBanner}>
              Save failed: {error.message || 'Unknown error'}. Your changes are still in this drawer — try editing any field to retry.
            </div>
          )}

          {/* Structured fields */}
          <div className={s.fields}>
            {section.fields
              .filter((f) => !f.readOnly || usesTasks /* snapshot's readOnly field still renders */)
              .map((field) => (
                <FieldRenderer
                  key={field.id}
                  field={field}
                  value={values[field.id]}
                  onChange={(v) => handleFieldChange(field.id, v)}
                  disabled={disabled}
                  siblingValues={values}
                />
              ))}
          </div>

          {/* Task editor for ADL / IADL sections */}
          {usesTasks && (
            <div className={s.tasksRegion}>
              <h3 className={s.tasksTitle}>Tasks</h3>
              <p className={s.tasksDescription}>
                Specific shift-by-shift tasks the caregiver performs for this activity area.
              </p>
              <TaskEditor
                sectionId={section.id}
                version={version}
                disabled={disabled}
                currentUser={currentUser}
                showToast={showToast}
              />
            </div>
          )}
        </div>

        <footer className={s.footer}>
          <div className={`${s.indicator} ${s[`tone_${indicator.tone}`] || ''}`}>
            {indicator.label && <span>{indicator.label}</span>}
          </div>
          <button className={btn.primaryBtn} onClick={handleClose}>
            Done
          </button>
        </footer>
      </aside>
    </div>
  );
}
