// ═══════════════════════════════════════════════════════════════
// Care Plan — Section Metadata
//
// Canonical definition of the clinical care plan's structure. Every
// piece of UI (read-only panel, editor drawers, iPad intake wizard,
// caregiver app, AI context layer) reads section structure from this
// file — changing a label or order here propagates everywhere.
//
// Section shape:
//   {
//     id:               string, machine id (matches keys in version.data)
//     label:            string, human-readable section title
//     description:      string, one-line hint shown under the title
//     order:            number, display order (stable, low-first)
//     isAutoGenerated:  bool,   if true, filled by AI (no manual entry)
//     fields:           [],     field list. Populated in Phase 2b as we
//                               build each section's editor.
//   }
//
// Data storage:
//   `care_plan_versions.data` JSONB is shaped as
//     { [sectionId]: { narrative: string, ...fieldValues } }
//   Sections that aren't populated yet are simply missing from `data`.
//
// CMS-485 compliance:
//   Field-level `cms485Required` flags live on individual fields once
//   Phase 2b fleshes them out. No field-level data here yet — this
//   file only pins the section taxonomy.
// ═══════════════════════════════════════════════════════════════


export const CARE_PLAN_SECTIONS = [
  {
    id: 'snapshot',
    label: 'Snapshot',
    description:
      'AI-generated one-paragraph summary of this client. Refreshed when the plan is published.',
    order: 1,
    isAutoGenerated: true,
    fields: [],
  },
  {
    id: 'demographics',
    label: 'Demographics & Household',
    description:
      'DOB, marital status, living situation, pets, languages, religion, cultural notes, past profession.',
    order: 2,
    fields: [],
  },
  {
    id: 'decisionMaking',
    label: 'Emergency & Decision-Making',
    description:
      'Emergency contacts, decision-making hierarchy, POAs (medical & financial), HIPAA releases, advance directives (DNR / POLST), family dynamics notes.',
    order: 3,
    fields: [],
  },
  {
    id: 'healthcareProviders',
    label: 'Healthcare Providers',
    description:
      'Primary care physician, specialists, preferred hospital, home health agency, hospice, pharmacy.',
    order: 4,
    fields: [],
  },
  {
    id: 'medicalProfile',
    label: 'Medical Profile',
    description:
      'Diagnoses, allergies, baseline vitals, recent hospitalizations, functional limitations.',
    order: 5,
    fields: [],
  },
  {
    id: 'medications',
    label: 'Medications',
    description:
      'Current medications with dose, route, frequency, prescriber, refill info, and who administers.',
    order: 6,
    fields: [],
  },
  {
    id: 'functionalStatus',
    label: 'Functional Status',
    description:
      'Sensory (vision / hearing / speech / swallowing), mobility, ambulation, transfers, fall risk, assistive devices.',
    order: 7,
    fields: [],
  },
  {
    id: 'cognitiveBehavioral',
    label: 'Cognitive & Behavioral',
    description:
      'Orientation baseline, memory patterns, mood baseline, behavioral triggers, de-escalation strategies, dementia stage, communication style.',
    order: 8,
    fields: [],
  },
  {
    id: 'adlTasks',
    label: 'ADL Tasks',
    description:
      'Per-activity tasks the caregiver performs: bathing, dressing, toileting, transfers, ambulation, feeding. Stored in care_plan_tasks.',
    order: 9,
    fields: [],
    usesTasksTable: true,
  },
  {
    id: 'iadlTasks',
    label: 'IADL Tasks',
    description:
      'Housework, meal prep, laundry, errands, transportation, medication management, caregiver-side observation/documentation tasks.',
    order: 10,
    fields: [],
    usesTasksTable: true,
  },
  {
    id: 'nutrition',
    label: 'Nutrition & Meals',
    description:
      'Diet restrictions, textures, favorite foods, mealtimes, appetite, fluid goals, swallowing precautions.',
    order: 11,
    fields: [],
  },
  {
    id: 'routines',
    label: 'Routines & Preferences',
    description:
      'Structured morning / afternoon / evening blocks, sleep pattern, TV / music preferences, conversation style, hobbies, activities at home and away.',
    order: 12,
    fields: [],
  },
  {
    id: 'homeSafety',
    label: 'Home & Safety',
    description:
      'Environmental hazards, clutter, lighting, grab bars, smoke / CO detectors, security system, equipment in home, evacuation plan.',
    order: 13,
    fields: [],
  },
  {
    id: 'goalsOfCare',
    label: 'Goals of Care',
    description:
      'Short-term and long-term goals, quality-of-life priorities, review cadence.',
    order: 14,
    fields: [],
  },
  {
    id: 'servicePlan',
    label: 'Service Plan',
    description:
      'Payor source, billing, hours per week, proposed schedule, rates. Cross-references the scheduling service_plans table.',
    order: 15,
    fields: [],
  },
  {
    id: 'matchCriteria',
    label: 'Caregiver Match Criteria',
    description:
      'Preferred / Required / Not-Needed flags for gender, certifications, experience types, pet and smoking tolerance, vehicle, weight-handling.',
    order: 16,
    fields: [],
  },
];


/**
 * Look up a section definition by id. Returns undefined if the id
 * isn't known — callers should handle this (likely means stale data).
 */
export function getSectionById(id) {
  if (!id) return undefined;
  return CARE_PLAN_SECTIONS.find((s) => s.id === id);
}


/**
 * Sections sorted by display order. Safe to call repeatedly — the
 * underlying array is already stably ordered but callers shouldn't
 * depend on that invariant.
 */
export function sortedSections() {
  return [...CARE_PLAN_SECTIONS].sort((a, b) => a.order - b.order);
}


/**
 * Does this section's content live in the care_plan_tasks table
 * rather than inline in version.data? Used by the editor and
 * read-only panel to route rendering.
 */
export function sectionUsesTasks(section) {
  return Boolean(section?.usesTasksTable);
}


/**
 * Human-readable category labels for the ADL/IADL task categories.
 * Matches the `category` column in `care_plan_tasks`.
 */
export const TASK_CATEGORIES = {
  'adl.ambulation':   { section: 'adlTasks',  label: 'Ambulation & Transfer' },
  'adl.bathing':      { section: 'adlTasks',  label: 'Bathing' },
  'adl.dressing':     { section: 'adlTasks',  label: 'Dressing & Grooming' },
  'adl.toileting':    { section: 'adlTasks',  label: 'Toileting' },
  'adl.transfers':    { section: 'adlTasks',  label: 'Transfers' },
  'adl.feeding':      { section: 'adlTasks',  label: 'Feeding' },
  'iadl.housework':   { section: 'iadlTasks', label: 'Housework' },
  'iadl.laundry':     { section: 'iadlTasks', label: 'Laundry' },
  'iadl.meal_prep':   { section: 'iadlTasks', label: 'Meal preparation' },
  'iadl.medication':  { section: 'iadlTasks', label: 'Medication support' },
  'iadl.errands':     { section: 'iadlTasks', label: 'Errands & transportation' },
  'iadl.observation': { section: 'iadlTasks', label: 'Observation & documentation' },
};


/**
 * Map a task category string back to its section id, or null if
 * the category isn't recognized.
 */
export function sectionIdForCategory(category) {
  const meta = TASK_CATEGORIES[category];
  return meta ? meta.section : null;
}
