// ═══════════════════════════════════════════════════════════════
// Care Plan — Section Metadata
//
// Canonical definition of the clinical care plan's structure. Every
// piece of UI (read-only panel, editor drawers, iPad intake wizard,
// caregiver app, AI context layer) reads section structure from this
// file — changing a label or order here propagates everywhere.
//
// Section shape:
//   {
//     id:               string, machine id (matches keys in version.data)
//     label:            string, human-readable section title
//     description:      string, one-line hint shown under the title
//     order:            number, display order (stable, low-first)
//     tiers:            string[], which audiences see this section.
//                       Any subset of ['admin', 'caregiver', 'family'].
//     isAutoGenerated:  bool,   if true, filled by AI (no manual entry)
//     usesTasksTable:   bool,   if true, content lives in care_plan_tasks
//                               (rendered as a task list, not fields)
//     fields:           Field[], field definitions for the editor
//   }
//
// Field shape:
//   {
//     id:          string, machine id (used as key in section data)
//     label:       string, human-readable field label
//     type:        FIELD_TYPES.<TYPE>
//     required?:   bool
//     readOnly?:   bool                 (for auto-generated fields)
//     cms485?:     bool                 (flags CMS-485 required fields)
//     help?:       string               (inline hint text)
//     placeholder?: string
//     options?:    string[]             (for select / multiselect / prn)
//     subfields?:  Field[]              (for list type — shape per row)
//     conditional?: { field, in? | equals? | notEquals? }
//                                       (hide unless sibling matches)
//     multiline?:  bool                 (for textarea — controls row count)
//   }
//
// Data storage:
//   `care_plan_versions.data` JSONB is shaped as
//     { [sectionId]: { [fieldId]: value, ... } }
//   Sections that aren't populated yet are simply missing from `data`.
//
// Visibility tiers:
//   - 'admin'     — office staff, full access (PR #164 RLS)
//   - 'caregiver' — in-home aide PWA (Phase 2d adds RLS + UI)
//   - 'family'    — via AI-generated digests in Communication Hub (Phase 3)
//
// CMS-485 compliance:
//   Fields marked `cms485: true` will be hydrated into CMS form 485
//   by a future export PR. No export logic yet — just the marking.
// ═══════════════════════════════════════════════════════════════


// ── Field type catalog ─────────────────────────────────────────

export const FIELD_TYPES = {
  TEXT: 'text',
  TEXTAREA: 'textarea',
  DATE: 'date',
  NUMBER: 'number',
  SELECT: 'select',
  MULTISELECT: 'multiselect',
  BOOLEAN: 'boolean',
  YN: 'yn',
  PHONE: 'phone',
  EMAIL: 'email',
  LIST: 'list',
  PRN: 'prn',
  LEVEL_PICK: 'levelPick',
};


// ── Visibility tiers ───────────────────────────────────────────

export const VISIBILITY_TIERS = {
  ADMIN: 'admin',
  CAREGIVER: 'caregiver',
  FAMILY: 'family',
};


// ── Shared option lists ────────────────────────────────────────
// Extracted to avoid drift across sections that ask similar things.

const ABILITY_LEVELS = ['Independent', 'Setup only', 'Partial assist', 'Full assist', 'Dependent'];
const RATING_GOOD_POOR = ['Good', 'Fair', 'Poor'];
const RATING_YNU = ['Yes', 'No', 'Unknown'];
const SEVERITY_MILD_SEVERE = ['Mild', 'Moderate', 'Severe'];

const COMMON_LANGUAGES = [
  'English', 'Spanish', 'Mandarin', 'Cantonese', 'Tagalog', 'Vietnamese',
  'Korean', 'Japanese', 'Hindi', 'Arabic', 'Russian', 'French', 'Portuguese',
  'German', 'Italian', 'Polish', 'ASL', 'Other',
];

const DAYS_OF_WEEK = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];


// ═══════════════════════════════════════════════════════════════
// Sections
// ═══════════════════════════════════════════════════════════════

export const CARE_PLAN_SECTIONS = [

  // ── 0. Snapshot (AI-generated) ───────────────────────────────
  {
    id: 'snapshot',
    label: 'Snapshot',
    description:
      'AI-generated summary of this client. Regenerated on publish. Read-only.',
    order: 0,
    tiers: ['admin', 'caregiver', 'family'],
    isAutoGenerated: true,
    fields: [
      {
        id: 'narrative',
        label: 'Narrative',
        type: FIELD_TYPES.TEXTAREA,
        readOnly: true,
        multiline: true,
      },
    ],
  },

  // ── 1. Who They Are ──────────────────────────────────────────
  {
    id: 'whoTheyAre',
    label: 'Who They Are',
    description:
      'The person, not the patient. Demographics, relationships, and the personal context a new caregiver needs.',
    order: 1,
    tiers: ['admin', 'caregiver', 'family'],
    fields: [
      // Identity
      { id: 'fullName', label: 'Full legal name', type: FIELD_TYPES.TEXT, required: true },
      { id: 'preferredName', label: 'Goes by', type: FIELD_TYPES.TEXT,
        placeholder: 'Nickname or preferred name' },
      { id: 'dateOfBirth', label: 'Date of birth', type: FIELD_TYPES.DATE, cms485: true },
      { id: 'gender', label: 'Gender', type: FIELD_TYPES.SELECT,
        options: ['Female', 'Male', 'Non-binary', 'Prefer not to say'] },
      { id: 'pronouns', label: 'Pronouns', type: FIELD_TYPES.TEXT,
        placeholder: 'she/her, he/him, they/them' },

      // Household
      { id: 'maritalStatus', label: 'Marital status', type: FIELD_TYPES.SELECT,
        options: ['Single', 'Married', 'Partnered', 'Widowed', 'Divorced', 'Separated'] },
      { id: 'spouseName', label: 'Spouse / partner name', type: FIELD_TYPES.TEXT,
        conditional: { field: 'maritalStatus', in: ['Married', 'Partnered'] } },
      { id: 'livesWith', label: 'Lives with', type: FIELD_TYPES.SELECT,
        options: ['Alone', 'Spouse or partner', 'Adult children', 'Extended family',
                  'Assisted living', 'Skilled nursing', 'Other'] },

      // Culture & identity
      { id: 'languages', label: 'Languages spoken', type: FIELD_TYPES.MULTISELECT,
        options: COMMON_LANGUAGES },
      { id: 'primaryLanguage', label: 'Primary language', type: FIELD_TYPES.SELECT,
        options: COMMON_LANGUAGES,
        help: 'The language they most prefer to speak.' },
      { id: 'religion', label: 'Religion / faith', type: FIELD_TYPES.TEXT,
        placeholder: 'Catholic, Jewish, Buddhist, none, etc.' },
      { id: 'attendsServices', label: 'Attends religious services', type: FIELD_TYPES.BOOLEAN },

      // Context
      { id: 'pastProfession', label: 'Past profession / career', type: FIELD_TYPES.TEXT,
        placeholder: 'Retired school teacher, Navy veteran, restaurant owner...' },
      { id: 'lifeContext', label: 'Life context',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        help: 'A sentence or two you\'d want a new caregiver to know before meeting them.',
        placeholder: 'e.g., "Retired Navy veteran, widowed 2019, grandfather of 4, proud of his woodworking."' },
      { id: 'interests', label: 'Interests & hobbies',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Woodworking, opera, bird watching, 49ers football, crosswords...' },
    ],
  },

  // ── 2. Health Profile ────────────────────────────────────────
  {
    id: 'healthProfile',
    label: 'Health Profile',
    description:
      'Diagnoses, medications, allergies, sensory status, and functional limitations. The medical picture.',
    order: 2,
    tiers: ['admin', 'caregiver'],
    fields: [
      // Diagnoses
      {
        id: 'primaryDiagnoses', label: 'Primary diagnoses', type: FIELD_TYPES.LIST,
        cms485: true,
        help: 'Current active diagnoses. Add one row per condition.',
        subfields: [
          { id: 'condition', label: 'Condition', type: FIELD_TYPES.TEXT, required: true },
          { id: 'yearDiagnosed', label: 'Year', type: FIELD_TYPES.TEXT, placeholder: '2019' },
          { id: 'status', label: 'Status', type: FIELD_TYPES.SELECT,
            options: ['Active', 'Stable', 'Resolved', 'Remission'] },
        ],
      },
      { id: 'otherConditions', label: 'Other conditions / history',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Prior surgeries, chronic conditions not listed above, family history worth noting.' },

      // Recent care
      { id: 'lastHospitalizationDate', label: 'Most recent hospitalization — date',
        type: FIELD_TYPES.DATE },
      { id: 'lastHospitalizationReason', label: 'Most recent hospitalization — reason',
        type: FIELD_TYPES.TEXT,
        conditional: { field: 'lastHospitalizationDate', notEquals: '' } },
      { id: 'lastHospitalizationOutcome', label: 'Outcome / discharge notes',
        type: FIELD_TYPES.TEXTAREA,
        conditional: { field: 'lastHospitalizationDate', notEquals: '' } },

      // Allergies (structured)
      {
        id: 'allergies', label: 'Allergies', type: FIELD_TYPES.LIST,
        help: 'Medications, foods, environmental. Severity helps caregivers know what to watch for.',
        subfields: [
          { id: 'allergen', label: 'Allergen', type: FIELD_TYPES.TEXT, required: true },
          { id: 'reaction', label: 'Reaction', type: FIELD_TYPES.TEXT,
            placeholder: 'Hives, anaphylaxis, GI upset...' },
          { id: 'severity', label: 'Severity', type: FIELD_TYPES.SELECT,
            options: SEVERITY_MILD_SEVERE },
        ],
      },

      // Medications (structured, first-class)
      {
        id: 'medications', label: 'Medications', type: FIELD_TYPES.LIST,
        cms485: true,
        help: 'Every medication the client takes, with dose and schedule.',
        subfields: [
          { id: 'name', label: 'Name', type: FIELD_TYPES.TEXT, required: true },
          { id: 'dose', label: 'Dose', type: FIELD_TYPES.TEXT, placeholder: '10 mg' },
          { id: 'route', label: 'Route', type: FIELD_TYPES.SELECT,
            options: ['PO (oral)', 'Topical', 'Injection', 'Inhaled', 'Sublingual',
                      'Rectal', 'Transdermal', 'Other'] },
          { id: 'frequency', label: 'Frequency', type: FIELD_TYPES.TEXT,
            placeholder: 'Once daily, BID, every 4 hours PRN...' },
          { id: 'prn', label: 'PRN (as needed)', type: FIELD_TYPES.BOOLEAN },
          { id: 'reason', label: 'Reason', type: FIELD_TYPES.TEXT },
          { id: 'prescriber', label: 'Prescriber', type: FIELD_TYPES.TEXT },
        ],
      },
      { id: 'medicationMeta', label: 'Medication management',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Who manages? Pill box used? Separate schedule sheet? Reminders needed?' },

      // Sensory status
      { id: 'hearing', label: 'Hearing', type: FIELD_TYPES.SELECT,
        options: ['Good', 'Impaired', 'Uses hearing aid', 'Profoundly impaired / Deaf'] },
      { id: 'vision', label: 'Vision', type: FIELD_TYPES.SELECT,
        options: ['Good', 'Impaired', 'Corrective lenses', 'Legally blind'] },
      { id: 'speech', label: 'Speech', type: FIELD_TYPES.SELECT,
        options: ['Normal', 'Impaired', 'Nonverbal', 'Uses device'] },
      { id: 'swallowing', label: 'Swallowing', type: FIELD_TYPES.SELECT,
        options: ['Normal', 'Mild difficulty', 'Dysphagia — modified diet', 'NPO / feeding tube'] },

      // Functional limitations
      { id: 'functionalLimitations', label: 'Functional limitations',
        type: FIELD_TYPES.MULTISELECT, cms485: true,
        options: ['Amputation', 'Hearing', 'Ambulation', 'Bowel / bladder incontinence',
                  'Paralysis', 'Speech', 'Contracture', 'Endurance', 'Legally blind',
                  'Dyspnea with minimal exertion', 'Cognitive impairment', 'Chronic pain'] },
      { id: 'otherHealthFlags', label: 'Other',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Smoker', 'Sensitive to smells', 'On oxygen', 'Colostomy bag', 'Feeding tube',
                  'Diabetes — insulin dependent', 'On blood thinners', 'Catheter'] },
    ],
  },

  // ── 3. Cognition & Behavior ──────────────────────────────────
  {
    id: 'cognitionBehavior',
    label: 'Cognition & Behavior',
    description:
      'Dementia level, mood, behavioral symptoms, triggers, and what calms them. Drives shift planning.',
    order: 3,
    tiers: ['admin', 'caregiver'],
    fields: [
      // Diagnosis & baseline
      { id: 'diagnosedDisorders', label: 'Diagnosed disorders / medications',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Dementia type, depression, anxiety, bipolar, etc. Plus any psychiatric medications.' },
      { id: 'dementiaLevel', label: 'Dementia level', type: FIELD_TYPES.SELECT,
        options: ['None', 'Mild', 'Moderate', 'Severe', 'End-stage', 'Unknown'] },
      { id: 'canBeLeftAlone', label: 'Can the client be left alone?',
        type: FIELD_TYPES.SELECT,
        options: ['Yes', 'Short periods only', 'No', 'Unknown'] },
      { id: 'leftAloneDuration', label: 'How long is safe?',
        type: FIELD_TYPES.TEXT, placeholder: '15 min, 1 hour, etc.',
        conditional: { field: 'canBeLeftAlone', equals: 'Short periods only' } },
      { id: 'wanderer', label: 'Is a wandering / elopement risk',
        type: FIELD_TYPES.SELECT, options: RATING_YNU },
      { id: 'wanderingHistory', label: 'Elopement history / precautions',
        type: FIELD_TYPES.TEXTAREA,
        conditional: { field: 'wanderer', equals: 'Yes' } },

      // Mood & baseline flags
      { id: 'moodFlags', label: 'Mood & mental-health flags',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Depression', 'Anxiety', 'Lethargy', 'Past / current substance abuse',
                  'Suicidal ideation history', 'Aggression history'] },

      // Symptoms
      { id: 'symptoms', label: 'Current symptoms',
        type: FIELD_TYPES.MULTISELECT,
        help: 'What the caregiver may observe.',
        options: ['Frequent mood changes', 'Short-term memory loss', 'Hallucinations',
                  'Problem solving difficulty', 'Spatial / visual relationship issues',
                  'Difficulty completing tasks', 'Sundowning', 'Speaking / conversing difficulty',
                  'Misplacing items', 'Poor eating', 'Anxiety', 'Poor judgment',
                  'Sleeping problems', 'Paranoia', 'Agitation', 'Fear', 'Confusion of time / place',
                  'Withdrawal', 'Aggression', 'Repetition', 'Suspicion', 'Depression',
                  'Wandering', 'Disorientation', 'Comatose'] },

      // Context for AI narratives + caregiver guidance
      { id: 'triggers', label: 'Known triggers',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        help: 'What upsets or agitates them?',
        placeholder: 'Loud noises in the afternoon; being rushed during dressing; unfamiliar faces.' },
      { id: 'calmingStrategies', label: 'What calms them',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        help: 'Gold for caregiver onboarding. What should the caregiver try first when things go sideways?',
        placeholder: 'Classical music; looking at photos of grandkids; a cup of tea and sitting by the window.' },
      { id: 'communicationStyle', label: 'Communication style',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Responds well to simple yes/no questions. Easily overwhelmed by long explanations.' },
    ],
  },

  // ── 4. Daily Living (ADLs) ───────────────────────────────────
  // Per-activity structured fields + a task list (stored in
  // care_plan_tasks). Field ids prefixed with the area so the editor
  // can visually group them (ambulation_*, bathing_*, etc.).
  {
    id: 'dailyLiving',
    label: 'Daily Living (ADLs)',
    description:
      'How they handle the activities of daily life — ambulation, bathing, dressing, toileting, meals. Current ability plus the tasks we do each shift.',
    order: 4,
    tiers: ['admin', 'caregiver', 'family'],
    usesTasksTable: true,
    fields: [
      // ── Ambulation & Transfers ──────────────────────────────
      { id: 'ambulation_mobilityLevel', label: 'Ambulation — mobility level',
        type: FIELD_TYPES.LEVEL_PICK },
      { id: 'ambulation_aids', label: 'Ambulation aids used',
        type: FIELD_TYPES.MULTISELECT,
        options: ['None', 'Cane', 'Walker', 'Rollator', 'Wheelchair', 'Geri-chair', 'Scooter',
                  'Crutches', 'Hospital bed', 'Lift chair', 'Mechanical lift'] },
      { id: 'ambulation_fallRisk', label: 'Fall risk', type: FIELD_TYPES.SELECT,
        options: ['None', 'History of falls', 'Current fall risk', 'Poor balance'] },
      { id: 'ambulation_useOfArms', label: 'Use of arms / hands',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Bilateral full use', 'Left impaired', 'Right impaired', 'Bilateral impaired',
                  'Fine motor difficulty'] },
      { id: 'ambulation_gaitBelt', label: 'Gait belt used',
        type: FIELD_TYPES.YN,
        help: 'If yes, note when it can be removed (e.g., while seated).' },
      { id: 'ambulation_transferRisks', label: 'Transfer risks / notes',
        type: FIELD_TYPES.TEXTAREA },

      // ── Bathing & Grooming ──────────────────────────────────
      { id: 'bathing_assistLevel', label: 'Bathing — assistance level',
        type: FIELD_TYPES.LEVEL_PICK },
      { id: 'bathing_method', label: 'Method',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Shower', 'Tub bath', 'Sponge bath', 'Bed bath'] },
      { id: 'bathing_frequency', label: 'Frequency',
        type: FIELD_TYPES.TEXT, placeholder: 'Daily, every other day, 3x/week...' },
      { id: 'bathing_resists', label: 'Resists bathing',
        type: FIELD_TYPES.YN },
      { id: 'bathing_usesShowerBench', label: 'Uses shower bench / chair',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'bathing_hygiene', label: 'Hygiene areas to watch',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Dental / dentures', 'Skin care', 'Nail care', 'Hair care', 'Shaving', 'Foot care'] },
      { id: 'bathing_notes', label: 'Bathing & grooming notes',
        type: FIELD_TYPES.TEXTAREA, multiline: true },

      // ── Dressing ────────────────────────────────────────────
      { id: 'dressing_assistLevel', label: 'Dressing — assistance level',
        type: FIELD_TYPES.LEVEL_PICK },
      { id: 'dressing_upperVsLower', label: 'Upper vs. lower body differences',
        type: FIELD_TYPES.TEXT,
        placeholder: 'e.g., Independent with tops, needs assist with pants.' },
      { id: 'dressing_notes', label: 'Dressing notes',
        type: FIELD_TYPES.TEXTAREA },

      // ── Toileting & Elimination ─────────────────────────────
      { id: 'toileting_assistLevel', label: 'Toileting — assistance level',
        type: FIELD_TYPES.LEVEL_PICK },
      { id: 'toileting_incontinence', label: 'Incontinence',
        type: FIELD_TYPES.MULTISELECT,
        options: ['None', 'Urinary', 'Bowel', 'Both'] },
      { id: 'toileting_wearsBriefs', label: 'Wears briefs / pull-ups',
        type: FIELD_TYPES.SELECT,
        options: ['No', 'Daytime only', 'Nighttime only', 'Always'] },
      { id: 'toileting_issues', label: 'Issues',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Constipation', 'Diarrhea', 'Urinary urgency', 'Urinary retention',
                  'Frequent UTIs', 'Frequent night urination'] },
      { id: 'toileting_devices', label: 'Devices',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Urinal', 'Bedside commode', 'Raised toilet seat', 'Grab bars',
                  'Catheter (indwelling)', 'Catheter (intermittent)', 'Colostomy bag'] },
      { id: 'toileting_notes', label: 'Toileting notes',
        type: FIELD_TYPES.TEXTAREA },

      // ── Nutrition & Meals ───────────────────────────────────
      { id: 'nutrition_diet', label: 'Diet type', type: FIELD_TYPES.MULTISELECT,
        options: ['Regular', 'Low sodium', 'Low fat', 'Low sugar / diabetic', 'High protein',
                  'High fiber', 'Low calorie', 'High calorie', 'Soft', 'Bland', 'Pureed',
                  'Mechanical soft', 'Thickened liquids', 'Encourage fluids', 'Restrict fluids'] },
      { id: 'nutrition_specialDiet', label: 'Special diet / allergies / preferences',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Kosher, vegetarian, lactose intolerant, strong food aversions...' },
      { id: 'nutrition_appetite', label: 'Appetite', type: FIELD_TYPES.SELECT,
        options: RATING_GOOD_POOR },
      { id: 'nutrition_feedingAssist', label: 'Feeding assistance',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Independent', 'Setup / cueing', 'Partial feeding assist', 'Full feeding assist',
                  'Swallowing precautions', 'Fluid encouragement'] },
      { id: 'nutrition_mealTimes_breakfast', label: 'Breakfast time',
        type: FIELD_TYPES.TEXT, placeholder: '7:30 am' },
      { id: 'nutrition_mealTimes_lunch', label: 'Lunch time',
        type: FIELD_TYPES.TEXT, placeholder: '12:30 pm' },
      { id: 'nutrition_mealTimes_dinner', label: 'Dinner time',
        type: FIELD_TYPES.TEXT, placeholder: '5:30 pm' },
      { id: 'nutrition_mealTimes_snacks', label: 'Snack times',
        type: FIELD_TYPES.TEXT, placeholder: 'Mid-morning, afternoon' },
      { id: 'nutrition_favorites_breakfast', label: 'Favorite breakfast foods',
        type: FIELD_TYPES.TEXTAREA },
      { id: 'nutrition_favorites_lunch', label: 'Favorite lunch foods',
        type: FIELD_TYPES.TEXTAREA },
      { id: 'nutrition_favorites_dinner', label: 'Favorite dinner foods',
        type: FIELD_TYPES.TEXTAREA },
      { id: 'nutrition_favorites_snack', label: 'Favorite snacks',
        type: FIELD_TYPES.TEXTAREA },
      { id: 'nutrition_dislikes', label: 'Dislikes / avoids',
        type: FIELD_TYPES.TEXTAREA },
      { id: 'nutrition_notes', label: 'Meal notes',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Prefers cold coffee with cream, always confirm meal preferences day-of.' },
    ],
  },

  // ── 5. Home & Life (IADLs) ───────────────────────────────────
  {
    id: 'homeAndLife',
    label: 'Home & Life (IADLs)',
    description:
      'Running the household — housekeeping, laundry, meals, medications, errands. Structured context plus the tasks we do each shift.',
    order: 5,
    tiers: ['admin', 'caregiver', 'family'],
    usesTasksTable: true,
    fields: [
      // ── Housekeeping ────────────────────────────────────────
      { id: 'housekeeping_scope', label: 'Housekeeping scope',
        type: FIELD_TYPES.SELECT,
        options: ['Light (dusting, dishes, tidying)', 'Medium (vacuuming, bathroom)',
                  'Heavy (scrubbing floors, deep clean)'] },
      { id: 'housekeeping_preferences', label: 'Housekeeping preferences / standards',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Prefers dusting Tuesdays; doesn\'t want the office touched; use only non-scented products.' },

      // ── Laundry ─────────────────────────────────────────────
      { id: 'laundry_frequency', label: 'Laundry frequency',
        type: FIELD_TYPES.TEXT, placeholder: 'Weekly, twice weekly, as needed' },
      { id: 'laundry_preferences', label: 'Laundry preferences',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Cold wash, no fabric softener, air-dry delicates.' },

      // ── Meal Prep ───────────────────────────────────────────
      { id: 'mealPrep_responsibilities', label: 'Meal prep responsibilities',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Shopping', 'Cooking', 'Heating only', 'Plating / serving',
                  'Feeding assistance', 'Clean up'] },
      { id: 'mealPrep_shoppingBy', label: 'Shopping done by',
        type: FIELD_TYPES.SELECT,
        options: ['Caregiver', 'Client', 'Family member', 'Delivery service', 'Mixed'] },
      { id: 'mealPrep_notes', label: 'Meal prep notes',
        type: FIELD_TYPES.TEXTAREA },

      // ── Medication Management ──────────────────────────────
      { id: 'medMgmt_needsReminders', label: 'Needs medication reminders',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'medMgmt_timesPerDay', label: 'How many times per day',
        type: FIELD_TYPES.NUMBER,
        conditional: { field: 'medMgmt_needsReminders', equals: true } },
      { id: 'medMgmt_managedBy', label: 'Who manages the medications',
        type: FIELD_TYPES.SELECT,
        options: ['Client', 'Caregiver', 'Family', 'Pharmacy service', 'Mixed'] },
      { id: 'medMgmt_pillBox', label: 'Medications set up in pill box',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'medMgmt_pillBoxWeeks', label: 'Pill box covers how many weeks',
        type: FIELD_TYPES.NUMBER,
        conditional: { field: 'medMgmt_pillBox', equals: true } },
      { id: 'medMgmt_separateSchedule', label: 'Separate medication schedule sheet',
        type: FIELD_TYPES.BOOLEAN },

      // ── Errands & Transportation ───────────────────────────
      { id: 'transport_clientDrives', label: 'Client drives',
        type: FIELD_TYPES.YN },
      { id: 'transport_needsCaregiverToDrive', label: 'Needs caregiver to drive',
        type: FIELD_TYPES.YN },
      { id: 'transport_vehicle', label: 'Vehicle used',
        type: FIELD_TYPES.SELECT,
        options: ['Client\'s car', 'Caregiver\'s car', 'Family car', 'Medical transport', 'Ride service'] },
      { id: 'transport_errands', label: 'Typical errands',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Grocery, pharmacy pickup, bank, post office, hair appointments.' },
      { id: 'transport_appointments', label: 'Doctor\'s appointments',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Who schedules? Who accompanies? Frequency?' },
    ],
  },

  // ── 6. Daily Rhythm ──────────────────────────────────────────
  {
    id: 'dailyRhythm',
    label: 'Daily Rhythm',
    description:
      'How their day flows — routines, activities, sleep, the people they love. This is what makes family narratives feel warm instead of clinical.',
    order: 6,
    tiers: ['admin', 'caregiver', 'family'],
    fields: [
      // Orders from clinician
      { id: 'activitiesPermitted', label: 'Activities permitted',
        type: FIELD_TYPES.MULTISELECT, cms485: true,
        options: ['Bedrest BRP', 'Up as tolerated', 'Transfer bed / chair',
                  'Exercises prescribed', 'Partial weight bearing', 'Cane', 'Walker',
                  'Wheelchair', 'Crutches', 'Independent at home', 'No restrictions'] },

      // Routine blocks
      { id: 'morningRoutine', label: 'Morning routine',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Waketime 7–8am, coffee with cream, reads the paper, takes morning meds with breakfast.' },
      { id: 'afternoonRoutine', label: 'Afternoon routine',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Lunch varies, likes to sit outside when the weather\'s nice, PT exercises Mon/Wed/Fri.' },
      { id: 'eveningRoutine', label: 'Evening routine',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Dinner 5:30–6pm, watches Jeopardy, bedtime 9–10pm.' },

      // Sleep
      { id: 'sleep_bedtime', label: 'Typical bedtime',
        type: FIELD_TYPES.TEXT, placeholder: '10 pm' },
      { id: 'sleep_waketime', label: 'Typical waketime',
        type: FIELD_TYPES.TEXT, placeholder: '7 am' },
      { id: 'sleep_nightWakings', label: 'Night wakings',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Wakes 1–2 times to use the bathroom; uses urinal at night.' },
      { id: 'sleep_naps', label: 'Naps',
        type: FIELD_TYPES.TEXT, placeholder: '30–45 min after lunch' },

      // Activities
      { id: 'activitiesAtHome', label: 'Activities at home',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Reading, crosswords, classical music, woodworking in the garage.' },
      { id: 'activitiesAway', label: 'Activities away from home',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        placeholder: 'Parks, lunch with friends on Fridays, Sunday church.' },
      { id: 'favoritePlaces', label: 'Favorite restaurants / shops',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Mel\'s Diner for Sunday brunch; Safeway on Geary; Book Passage.' },

      // People
      { id: 'familyFriendsNeighbors', label: 'Family, friends, neighbors who matter',
        type: FIELD_TYPES.TEXTAREA, multiline: true,
        help: 'The people who visit, call, or bring joy. Gold for family narratives.',
        placeholder: 'Daughter Karen visits Sundays; neighbor Bill walks the dog with him; grandson Jake calls Wednesdays.' },
    ],
  },

  // ── 7. Home Environment ──────────────────────────────────────
  {
    id: 'homeEnvironment',
    label: 'Home Environment',
    description:
      'Safety, equipment, pets, and the layout of where care happens.',
    order: 7,
    tiers: ['admin', 'caregiver'],
    fields: [
      // Home basics
      { id: 'homeType', label: 'Home type', type: FIELD_TYPES.SELECT,
        options: ['Single-family house', 'Apartment / condo', 'Duplex',
                  'Assisted living (ALF)', 'Independent living', 'Skilled nursing (SNF)',
                  'Family member\'s home', 'Other'] },
      { id: 'floors', label: 'Number of floors', type: FIELD_TYPES.NUMBER },
      { id: 'stairsCount', label: 'Stairs in home',
        type: FIELD_TYPES.TEXT,
        placeholder: '12-step staircase to bedrooms; 3 entry steps; none.' },

      // Safety Y/N grid
      { id: 'safety_stairsClear', label: 'Stairs / hallways / walkways free of clutter',
        type: FIELD_TYPES.YN },
      { id: 'safety_adequateLighting', label: 'Adequate lighting throughout',
        type: FIELD_TYPES.YN },
      { id: 'safety_looseCarpets', label: 'Loose carpets or rugs present',
        type: FIELD_TYPES.YN },
      { id: 'safety_stairHandrails', label: 'Stairs have handrails',
        type: FIELD_TYPES.YN },
      { id: 'safety_grabBars', label: 'Grab bars in shower / bathroom',
        type: FIELD_TYPES.YN },
      { id: 'safety_securitySystem', label: 'Security system',
        type: FIELD_TYPES.YN },
      { id: 'safety_smokingInHome', label: 'Client or others smoke in home',
        type: FIELD_TYPES.YN },
      { id: 'safety_substanceUse', label: 'Alcohol / substance use in home',
        type: FIELD_TYPES.YN },
      { id: 'safety_emergencyResponse', label: 'Emergency response system (Life Alert etc.)',
        type: FIELD_TYPES.YN },
      { id: 'safety_smokeDetectors', label: 'Working smoke detectors',
        type: FIELD_TYPES.YN },
      { id: 'safety_coDetectors', label: 'Working carbon monoxide detectors',
        type: FIELD_TYPES.YN },
      { id: 'safety_fireExtinguisher', label: 'Fire extinguisher',
        type: FIELD_TYPES.YN },
      { id: 'safety_abuseNeglectSigns', label: 'Any signs of abuse or neglect',
        type: FIELD_TYPES.YN,
        help: 'Must be flagged to the office immediately if yes.' },

      // Equipment
      { id: 'equipmentInHome', label: 'Equipment / assistive devices in home',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Corrective lenses', 'Hearing aids', 'Dentures', 'Cane', 'Walker',
                  'Wheelchair', 'Rollator', 'Grab bars', 'Hospital bed', 'Bedside commode',
                  'Raised toilet seat', 'Lift chair', 'Oxygen', 'Mechanical lift', 'Ramp',
                  'Shower bench', 'Handheld shower', 'Other'] },

      // Pets
      { id: 'pets', label: 'Pets in home',
        type: FIELD_TYPES.LIST,
        help: 'Caregiver match requirements cover whether a caregiver is comfortable with pets.',
        subfields: [
          { id: 'type', label: 'Type', type: FIELD_TYPES.SELECT,
            options: ['Dog', 'Cat', 'Bird', 'Rabbit', 'Fish', 'Reptile', 'Other'] },
          { id: 'name', label: 'Name', type: FIELD_TYPES.TEXT },
          { id: 'notes', label: 'Notes', type: FIELD_TYPES.TEXT,
            placeholder: 'Temperament, caregiver responsibilities, vet info.' },
        ],
      },

      // Freeform
      { id: 'environmentNotes', label: 'Environment notes',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Anything else about the home that matters for care.' },
    ],
  },

  // ── 8. Care Team ─────────────────────────────────────────────
  {
    id: 'careTeam',
    label: 'Care Team',
    description:
      'Everyone involved in this person\'s care — providers, responsible parties, emergency contacts, family support.',
    order: 8,
    tiers: ['admin', 'caregiver'],
    fields: [
      // Primary providers
      { id: 'pcpName', label: 'Primary care physician — name', type: FIELD_TYPES.TEXT, cms485: true },
      { id: 'pcpPhone', label: 'PCP phone', type: FIELD_TYPES.PHONE, cms485: true },
      { id: 'pcpAddress', label: 'PCP address', type: FIELD_TYPES.TEXT },

      { id: 'preferredHospital', label: 'Preferred hospital', type: FIELD_TYPES.TEXT },
      { id: 'preferredHospitalPhone', label: 'Hospital phone', type: FIELD_TYPES.PHONE },

      { id: 'homeHealthProvider', label: 'Home health provider', type: FIELD_TYPES.TEXT },
      { id: 'homeHealthPhone', label: 'Home health phone', type: FIELD_TYPES.PHONE },

      // Specialists
      {
        id: 'specialists', label: 'Specialists', type: FIELD_TYPES.LIST,
        subfields: [
          { id: 'name', label: 'Name', type: FIELD_TYPES.TEXT, required: true },
          { id: 'specialty', label: 'Specialty', type: FIELD_TYPES.TEXT,
            placeholder: 'Cardiologist, neurologist, PT...' },
          { id: 'phone', label: 'Phone', type: FIELD_TYPES.PHONE },
        ],
      },

      // Responsible Party — Primary
      { id: 'rpPrimary_name', label: 'Primary responsible party — name', type: FIELD_TYPES.TEXT },
      { id: 'rpPrimary_relationship', label: 'Relationship', type: FIELD_TYPES.TEXT,
        placeholder: 'Daughter, spouse, attorney-in-fact...' },
      { id: 'rpPrimary_phone', label: 'Phone', type: FIELD_TYPES.PHONE },
      { id: 'rpPrimary_email', label: 'Email', type: FIELD_TYPES.EMAIL },
      { id: 'rpPrimary_contactFor', label: 'Contact for',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Care concerns', 'Care decisions', 'Billing', 'Scheduling', 'Other'] },
      { id: 'rpPrimary_hipaaOnFile', label: 'HIPAA release on file',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'rpPrimary_financialPOA', label: 'Financial power of attorney',
        type: FIELD_TYPES.YN,
        help: 'If yes, copy should be on file.' },
      { id: 'rpPrimary_healthcarePOA', label: 'Healthcare power of attorney',
        type: FIELD_TYPES.YN,
        help: 'If yes, copy should be on file.' },

      // Responsible Party — Secondary
      { id: 'rpSecondary_name', label: 'Secondary responsible party — name', type: FIELD_TYPES.TEXT },
      { id: 'rpSecondary_relationship', label: 'Relationship', type: FIELD_TYPES.TEXT },
      { id: 'rpSecondary_phone', label: 'Phone', type: FIELD_TYPES.PHONE },
      { id: 'rpSecondary_email', label: 'Email', type: FIELD_TYPES.EMAIL },
      { id: 'rpSecondary_contactFor', label: 'Contact for',
        type: FIELD_TYPES.MULTISELECT,
        options: ['Care concerns', 'Care decisions', 'Billing', 'Scheduling', 'Other'] },
      { id: 'rpSecondary_hipaaOnFile', label: 'HIPAA release on file',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'rpSecondary_financialPOA', label: 'Financial power of attorney',
        type: FIELD_TYPES.YN },
      { id: 'rpSecondary_healthcarePOA', label: 'Healthcare power of attorney',
        type: FIELD_TYPES.YN },

      // Emergency contacts (non-RP family/friends who can help in a pinch)
      {
        id: 'emergencyContacts', label: 'Emergency contacts',
        type: FIELD_TYPES.LIST,
        help: 'People to reach outside the responsible parties — close neighbors, backup family.',
        subfields: [
          { id: 'name', label: 'Name', type: FIELD_TYPES.TEXT, required: true },
          { id: 'relationship', label: 'Relationship', type: FIELD_TYPES.TEXT },
          { id: 'phone', label: 'Phone', type: FIELD_TYPES.PHONE, required: true },
          { id: 'notes', label: 'Notes', type: FIELD_TYPES.TEXT },
        ],
      },
    ],
  },

  // ── 9. Goals & Orders ────────────────────────────────────────
  {
    id: 'goalsOrders',
    label: 'Goals & Orders',
    description:
      'The clinical plan of care header — goals, safety measures, activity restrictions, prognosis, and link to the service plan.',
    order: 9,
    tiers: ['admin', 'caregiver'],
    fields: [
      // Clinical narrative
      { id: 'careGoals', label: 'Care goals',
        type: FIELD_TYPES.TEXTAREA, multiline: true, cms485: true,
        help: 'What we\'re helping this client achieve. Short-term + long-term.',
        placeholder: 'Safely recover at home from surgery; rebuild strength; maintain independence with daily routines.' },
      { id: 'safetyMeasures', label: 'Safety measures',
        type: FIELD_TYPES.TEXTAREA, multiline: true, cms485: true,
        placeholder: 'Use of gait belt for transfers, two-person assist for stairs, call bell within reach.' },
      { id: 'activityRestrictions', label: 'Activity restrictions',
        type: FIELD_TYPES.TEXTAREA, multiline: true, cms485: true,
        placeholder: 'No lifting over 10 lbs, no stairs without assistance, weight-bearing as tolerated on right leg.' },

      // Dates
      { id: 'startOfCareDate', label: 'Start of care date',
        type: FIELD_TYPES.DATE, cms485: true },
      { id: 'certificationPeriodStart', label: 'Certification period — start',
        type: FIELD_TYPES.DATE, cms485: true },
      { id: 'certificationPeriodEnd', label: 'Certification period — end',
        type: FIELD_TYPES.DATE, cms485: true },

      // Status
      { id: 'prognosis', label: 'Prognosis',
        type: FIELD_TYPES.SELECT, cms485: true,
        options: ['Good', 'Guarded', 'Poor', 'Unknown'] },
      { id: 'dnrStatus', label: 'DNR status',
        type: FIELD_TYPES.SELECT,
        options: ['Yes', 'No', 'Unknown'] },
      { id: 'advanceDirectiveOnFile', label: 'Advance directive on file',
        type: FIELD_TYPES.SELECT,
        options: ['Yes', 'No', 'Unknown'] },
      { id: 'polstOnFile', label: 'POLST / MOLST on file',
        type: FIELD_TYPES.SELECT,
        options: ['Yes', 'No', 'Unknown', 'Not applicable'] },

      // Freeform
      { id: 'ordersNotes', label: 'Additional orders / notes',
        type: FIELD_TYPES.TEXTAREA,
        help: 'Anything else a clinician has specified that doesn\'t fit above.' },
    ],
  },

  // ── 10. Match Criteria (admin only) ──────────────────────────
  // Preserves the Wellsky P/R/N pattern because it maps cleanly to
  // our caregiver matching engine.
  {
    id: 'matchCriteria',
    label: 'Caregiver Match Criteria',
    description:
      'Preferences and requirements for matching caregivers. Admin-only — caregivers and family never see this.',
    order: 10,
    tiers: ['admin'],
    fields: [
      // General preferences (P/R/N)
      { id: 'match_gender', label: 'Gender preference',
        type: FIELD_TYPES.PRN,
        options: ['Female', 'Male', 'No preference'] },
      { id: 'match_languageRequired', label: 'Language required',
        type: FIELD_TYPES.MULTISELECT,
        options: COMMON_LANGUAGES },

      // Experience (each P/R/N)
      { id: 'match_exp_dementia', label: 'Dementia experience', type: FIELD_TYPES.PRN },
      { id: 'match_exp_hospice', label: 'Hospice experience', type: FIELD_TYPES.PRN },
      { id: 'match_exp_incontinence', label: 'Incontinence care', type: FIELD_TYPES.PRN },
      { id: 'match_exp_transfers', label: 'Transfer experience', type: FIELD_TYPES.PRN },
      { id: 'match_exp_gaitBelt', label: 'Gait belt experience', type: FIELD_TYPES.PRN },
      { id: 'match_exp_hoyer', label: 'Hoyer lift experience', type: FIELD_TYPES.PRN },
      { id: 'match_exp_weight', label: 'Can handle client\'s weight', type: FIELD_TYPES.PRN },

      // Certifications (each P/R/N)
      { id: 'match_cert_cna', label: 'CNA license', type: FIELD_TYPES.PRN },
      { id: 'match_cert_hha', label: 'HHA certification', type: FIELD_TYPES.PRN },
      { id: 'match_cert_lvn', label: 'LVN / LPN', type: FIELD_TYPES.PRN },
      { id: 'match_cert_rn', label: 'Registered nurse', type: FIELD_TYPES.PRN },

      // Pets (P/R)
      { id: 'match_okWithCats', label: 'OK with cats', type: FIELD_TYPES.PRN },
      { id: 'match_okWithDogs', label: 'OK with dogs', type: FIELD_TYPES.PRN },

      // Logistics / hard requirements
      { id: 'match_vehicleRequired', label: 'Caregiver must have vehicle',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'match_insuredAutoRequired', label: 'Caregiver must have insured auto',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'match_okWithClientSmoking', label: 'Caregiver must be OK with client smoking',
        type: FIELD_TYPES.BOOLEAN,
        conditional: { field: 'match_clientSmokes', equals: true } },
      { id: 'match_clientSmokes', label: 'Client smokes in home',
        type: FIELD_TYPES.BOOLEAN },
      { id: 'match_liveInShiftsOK', label: 'Caregiver must be OK with live-in shifts',
        type: FIELD_TYPES.BOOLEAN },

      // Freeform
      { id: 'match_notes', label: 'Match notes / soft preferences',
        type: FIELD_TYPES.TEXTAREA,
        placeholder: 'Prefers warm personality over formal; client bonded well with previous Filipino caregivers.' },
    ],
  },

];


// ═══════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════

/**
 * Look up a section definition by id. Returns undefined if the id
 * isn't known — callers should handle this (likely means stale data).
 */
export function getSectionById(id) {
  if (!id) return undefined;
  return CARE_PLAN_SECTIONS.find((s) => s.id === id);
}


/**
 * Sections sorted by display order.
 */
export function sortedSections() {
  return [...CARE_PLAN_SECTIONS].sort((a, b) => a.order - b.order);
}


/**
 * Does this section's content live in the care_plan_tasks table
 * rather than inline in version.data?
 */
export function sectionUsesTasks(section) {
  return Boolean(section?.usesTasksTable);
}


/**
 * Sections visible to a given audience tier. Used by the caregiver
 * PWA and the family digest AI to filter the plan.
 */
export function visibleSectionsForTier(tier) {
  if (!tier) return [];
  return sortedSections().filter((s) => Array.isArray(s.tiers) && s.tiers.includes(tier));
}


/**
 * Look up a field definition within a section. Returns undefined if
 * either the section or the field id is unknown. Used by change-event
 * logging to resolve human-readable field labels.
 */
export function getFieldById(sectionId, fieldId) {
  const section = getSectionById(sectionId);
  if (!section || !Array.isArray(section.fields)) return undefined;
  return section.fields.find((f) => f.id === fieldId);
}


/**
 * Human-readable category labels for the ADL/IADL task categories.
 * Matches the `category` column in `care_plan_tasks`. ADL categories
 * route to the 'dailyLiving' section; IADL categories route to
 * 'homeAndLife'. The legacy category strings ('adl.*', 'iadl.*')
 * are preserved so existing task rows route correctly.
 */
export const TASK_CATEGORIES = {
  'adl.ambulation':   { section: 'dailyLiving', label: 'Ambulation & Transfers' },
  'adl.transfers':    { section: 'dailyLiving', label: 'Transfers' },
  'adl.bathing':      { section: 'dailyLiving', label: 'Bathing' },
  'adl.dressing':     { section: 'dailyLiving', label: 'Dressing & Grooming' },
  'adl.toileting':    { section: 'dailyLiving', label: 'Toileting' },
  'adl.feeding':      { section: 'dailyLiving', label: 'Feeding' },
  'iadl.housework':   { section: 'homeAndLife', label: 'Housework' },
  'iadl.laundry':     { section: 'homeAndLife', label: 'Laundry' },
  'iadl.meal_prep':   { section: 'homeAndLife', label: 'Meal preparation' },
  'iadl.medication':  { section: 'homeAndLife', label: 'Medication support' },
  'iadl.errands':     { section: 'homeAndLife', label: 'Errands & transportation' },
};


/**
 * Map a task category string back to its section id, or null if
 * the category isn't recognized.
 */
export function sectionIdForCategory(category) {
  const meta = TASK_CATEGORIES[category];
  return meta ? meta.section : null;
}


/**
 * Shared day-of-week labels exported for UI use in TaskEditor etc.
 */
export { DAYS_OF_WEEK };
