-- BD Module — South OC research-import seed
--
-- Imports Amy Dutton's South Orange County referral-source list
-- (Word doc dated 2026-05-15) into bd_accounts. Generated by
-- scripts/bd-south-oc-research-import.py — do not edit by hand;
-- re-run the script with the updated doc instead.
--
-- Behavior:
--   * For each doc row whose (name, city) matches an existing
--     bd_accounts row via the alias table baked into the script,
--     we UPDATE the existing row to fill in address / phone
--     where currently NULL. The existing row's source stays as
--     'manual' or 'trello_import' — we don't overwrite provenance.
--   * For each doc row with no alias match, we INSERT a new
--     bd_accounts row with source='research_import' so the
--     'Prospect' badge surfaces it in the BD portal until Amy
--     logs her first activity against it.
--   * Re-runs are no-ops: the INSERT uses a partial unique index
--     on (org_id, lower(name), lower(coalesce(city,''))) WHERE
--     source='research_import', created in the same migration.
--     The UPDATE statements are idempotent by construction
--     (COALESCE preserves any value already present).
--
-- Production safety: pure additive. No DELETE, no DROP, no
-- destructive change to non-NULL columns on existing rows.
-- Tenant isolation: every INSERT carries org_id = default_org_id()
-- per Phase B locked decisions.
-- Rollback:
--   _rollback/<this-filename>_down.sql clears source='research_import'
--   rows it created, and unsets the address/phone overrides on the
--   aliased rows where the value matches what the up-migration set.

-- ─────────────────────────────────────────────────────────────
-- 1. Idempotency index
-- ─────────────────────────────────────────────────────────────

CREATE UNIQUE INDEX IF NOT EXISTS idx_bd_accounts_research_import_unique
  ON bd_accounts (org_id, lower(name), lower(coalesce(city, '')))
  WHERE source = 'research_import';

-- ─────────────────────────────────────────────────────────────
-- 2. Backfill address/phone on aliased existing rows
-- ─────────────────────────────────────────────────────────────
--
-- 38 rows from the doc map to existing accounts via the
-- alias table in scripts/bd-south-oc-research-import.py.

-- Hoag Hospital  →  existing id 47cbb432-6bfd-4f29-87e4-d52bbcd61378  (no address/phone in doc; nothing to update)

-- Crystal Cove Care Center  →  existing id 792b7c2d-6e6f-4a2c-9cae-e7b4f450ff20
UPDATE bd_accounts
   SET address = COALESCE(address, '1445 Superior Ave'),
       phone   = COALESCE(phone,   '+19495153930')
 WHERE id = '792b7c2d-6e6f-4a2c-9cae-e7b4f450ff20'::uuid;

-- Pelican Ridge Post-Acute  →  existing id 168a5e17-ef07-4f11-b13e-b1ce9d0b5331
UPDATE bd_accounts
   SET address = COALESCE(address, 'Flagship Rd'),
       phone   = COALESCE(phone,   '+19496428044')
 WHERE id = '168a5e17-ef07-4f11-b13e-b1ce9d0b5331'::uuid;

-- Newport Beach Memory Care  →  existing id bf18c6a7-ab5d-48fb-a572-6c2ca76e2297
UPDATE bd_accounts
   SET address = COALESCE(address, '1000 Halyard')
 WHERE id = 'bf18c6a7-ab5d-48fb-a572-6c2ca76e2297'::uuid;

-- Atria Newport Beach  →  existing id dfde6580-7254-434f-99da-5df9c5d6d9ff
UPDATE bd_accounts
   SET address = COALESCE(address, '393 Hospital Road')
 WHERE id = 'dfde6580-7254-434f-99da-5df9c5d6d9ff'::uuid;

-- Vivante Newport Center  →  existing id 1645ebe9-e1a7-4623-a234-d986d2266601
UPDATE bd_accounts
   SET address = COALESCE(address, '850 San Clemente Dr')
 WHERE id = '1645ebe9-e1a7-4623-a234-d986d2266601'::uuid;

-- Clearwater Newport Beach  →  existing id 3a58d9b7-e7f8-47c6-825f-4254b1abaa76
UPDATE bd_accounts
   SET address = COALESCE(address, '101 Bayview Pl'),
       phone   = COALESCE(phone,   '+19499426391')
 WHERE id = '3a58d9b7-e7f8-47c6-825f-4254b1abaa76'::uuid;

-- Hoag Hospital Irvine  →  existing id 2a3c0d15-35e5-4a08-8d18-d91dd13cf6a6
UPDATE bd_accounts
   SET address = COALESCE(address, '16200 Sand Canyon Ave'),
       phone   = COALESCE(phone,   '+19497644624')
 WHERE id = '2a3c0d15-35e5-4a08-8d18-d91dd13cf6a6'::uuid;

-- Windcrest at Regents Point  →  existing id 8fdefc8d-13d6-4812-ac5d-f5f3d08882e1
UPDATE bd_accounts
   SET address = COALESCE(address, '19191 Harvard Ave'),
       phone   = COALESCE(phone,   '+19495092298')
 WHERE id = '8fdefc8d-13d6-4812-ac5d-f5f3d08882e1'::uuid;

-- Regents Point (CCRC)  →  existing id cd92e7b6-403d-46ac-961f-ae5c3459083f
UPDATE bd_accounts
   SET address = COALESCE(address, '19191 Harvard Ave'),
       phone   = COALESCE(phone,   '+19498549500')
 WHERE id = 'cd92e7b6-403d-46ac-961f-ae5c3459083f'::uuid;

-- Woodbridge Terrace of Irvine  →  existing id 69d46477-df54-4274-a980-947c01505aab
UPDATE bd_accounts
   SET address = COALESCE(address, '1 Witherspoon'),
       phone   = COALESCE(phone,   '+19495229604')
 WHERE id = '69d46477-df54-4274-a980-947c01505aab'::uuid;

-- Atria Golden Creek  →  existing id 052b574b-06bb-4b5a-8746-dc864ac80ee5
UPDATE bd_accounts
   SET address = COALESCE(address, '33 Creek Rd'),
       phone   = COALESCE(phone,   '+19497865665')
 WHERE id = '052b574b-06bb-4b5a-8746-dc864ac80ee5'::uuid;

-- Trabuco Hills Post-Acute  →  existing id f5cff168-5ff9-4ced-b365-96834d079536
UPDATE bd_accounts
   SET address = COALESCE(address, '25652 Old Trabuco Rd, Lake Forest 92630'),
       phone   = COALESCE(phone,   '+19493809380')
 WHERE id = 'f5cff168-5ff9-4ced-b365-96834d079536'::uuid;

-- Freedom Village Retirement Community  →  existing id 34b13857-a8e6-4d9e-a6f6-8b02c2c3d4bd
UPDATE bd_accounts
   SET address = COALESCE(address, '23442 El Toro Rd, Lake Forest 92630'),
       phone   = COALESCE(phone,   '+19496872723')
 WHERE id = '34b13857-a8e6-4d9e-a6f6-8b02c2c3d4bd'::uuid;

-- Providence Mission Hospital Laguna Beach  →  existing id 95eb3fd0-861b-4d04-9290-7b99bcf3f899
UPDATE bd_accounts
   SET address = COALESCE(address, '31872 Coast Hwy, Laguna Beach'),
       phone   = COALESCE(phone,   '+19494991311')
 WHERE id = '95eb3fd0-861b-4d04-9290-7b99bcf3f899'::uuid;

-- MemorialCare Saddleback Medical Center  →  existing id b8871833-0396-46e4-a26d-ace0cd357882
UPDATE bd_accounts
   SET address = COALESCE(address, '24451 Health Center Dr, Laguna Hills'),
       phone   = COALESCE(phone,   '+19498374500')
 WHERE id = 'b8871833-0396-46e4-a26d-ace0cd357882'::uuid;

-- Villa Valencia Healthcare Center  →  existing id 57fde526-e604-4489-8ad6-cb74799fecbc
UPDATE bd_accounts
   SET address = COALESCE(address, '25000 Calle De Los Caballeros, Laguna Hills'),
       phone   = COALESCE(phone,   '+19496097540')
 WHERE id = '57fde526-e604-4489-8ad6-cb74799fecbc'::uuid;

-- Palm Terrace Healthcare & Rehab  →  existing id bb702366-f5e0-4553-90ef-fed9aa388c5a
UPDATE bd_accounts
   SET address = COALESCE(address, '24962 Calle Aragon, Laguna Hills/Woods border'),
       phone   = COALESCE(phone,   '+19495879000')
 WHERE id = 'bb702366-f5e0-4553-90ef-fed9aa388c5a'::uuid;

-- Laguna Hills Health & Rehabilitation  →  existing id c2884c89-9e7a-47e5-8eef-bcd64c02eda4
UPDATE bd_accounts
   SET address = COALESCE(address, '24452 Health Center Dr, Laguna Hills'),
       phone   = COALESCE(phone,   '+19498378000')
 WHERE id = 'c2884c89-9e7a-47e5-8eef-bcd64c02eda4'::uuid;

-- Watermark Laguna Niguel  →  existing id 570d72ee-dff7-4b59-ade1-fa46b829e70c
UPDATE bd_accounts
   SET address = COALESCE(address, '27762 Forbes Rd, Laguna Niguel'),
       phone   = COALESCE(phone,   '+18552017289')
 WHERE id = '570d72ee-dff7-4b59-ade1-fa46b829e70c'::uuid;

-- Crestavilla  →  existing id d726eaef-e357-4c2f-a677-8cd29cdb21eb
UPDATE bd_accounts
   SET address = COALESCE(address, '30111 Niguel Rd, Laguna Niguel'),
       phone   = COALESCE(phone,   '+19498445997')
 WHERE id = 'd726eaef-e357-4c2f-a677-8cd29cdb21eb'::uuid;

-- Meridian at Laguna Hills  →  existing id 81f5d5be-30fd-4987-a8a5-4cc49dbc9ddf
UPDATE bd_accounts
   SET address = COALESCE(address, '24552 Paseo De Valencia, Laguna Hills'),
       phone   = COALESCE(phone,   '+19499986296')
 WHERE id = '81f5d5be-30fd-4987-a8a5-4cc49dbc9ddf'::uuid;

-- ActivCare Laguna Hills  →  existing id c4e5cca5-9b0a-4074-9d3e-1c8eb13c9e17
UPDATE bd_accounts
   SET address = COALESCE(address, '25200 Paseo De Alicia, Laguna Hills'),
       phone   = COALESCE(phone,   '+19495706887')
 WHERE id = 'c4e5cca5-9b0a-4074-9d3e-1c8eb13c9e17'::uuid;

-- Aegis Living Laguna Niguel  →  existing id 2c35ad90-576f-440e-8f60-14d967183047
UPDATE bd_accounts
   SET address = COALESCE(address, '32170 Niguel Rd, Laguna Niguel'),
       phone   = COALESCE(phone,   '+19496763780')
 WHERE id = '2c35ad90-576f-440e-8f60-14d967183047'::uuid;

-- Ivy Park of Wellington  →  existing id bbe5e119-d990-45df-9edc-6d4e27eba0fc
UPDATE bd_accounts
   SET address = COALESCE(address, '24962 Calle Aragon, Laguna Woods'),
       phone   = COALESCE(phone,   '+19494036343')
 WHERE id = 'bbe5e119-d990-45df-9edc-6d4e27eba0fc'::uuid;

-- Belmont Village Senior Living Aliso Viejo  →  existing id 7f68fd6a-eec9-4adb-bf81-181231dd3f24
UPDATE bd_accounts
   SET address = COALESCE(address, '300 Freedom Ln'),
       phone   = COALESCE(phone,   '+19496494791')
 WHERE id = '7f68fd6a-eec9-4adb-bf81-181231dd3f24'::uuid;

-- Hoag Concierge Medicine – Aliso Viejo  →  existing id 7712de8a-60f9-453a-8ceb-798d650fbd0d
UPDATE bd_accounts
   SET address = COALESCE(address, '26671 Aliso Creek Rd #304'),
       phone   = COALESCE(phone,   '+19495563304')
 WHERE id = '7712de8a-60f9-453a-8ceb-798d650fbd0d'::uuid;

-- The Orchards Health Center  →  existing id 7d1c6c42-9ab5-4bc8-ae16-d4938526cb0a
UPDATE bd_accounts
   SET address = COALESCE(address, '1 Amistad Dr'),
       phone   = COALESCE(phone,   '+19495452260')
 WHERE id = '7d1c6c42-9ab5-4bc8-ae16-d4938526cb0a'::uuid;

-- Sunrise of Mission Viejo  →  existing id e8395783-f11c-4450-98f6-35e348c62518
UPDATE bd_accounts
   SET address = COALESCE(address, '26151 Country Club Dr'),
       phone   = COALESCE(phone,   '+19495822010')
 WHERE id = 'e8395783-f11c-4450-98f6-35e348c62518'::uuid;

-- Heritage Pointe  →  existing id 7fa154dd-7bf4-4143-b35b-31012279078e
UPDATE bd_accounts
   SET address = COALESCE(address, '27356 Bellogente'),
       phone   = COALESCE(phone,   '+19493649685')
 WHERE id = '7fa154dd-7bf4-4143-b35b-31012279078e'::uuid;

-- Park Terrace  →  existing id 4c4b5d8a-5080-49a3-b222-3f673eeaeb5c
UPDATE bd_accounts
   SET address = COALESCE(address, '21952 Buena Suerte'),
       phone   = COALESCE(phone,   '+19496198796')
 WHERE id = '4c4b5d8a-5080-49a3-b222-3f673eeaeb5c'::uuid;

-- San Juan Hills Healthcare Center  →  existing id 258d79f0-fa02-455f-a3aa-7cbd9f15651f
UPDATE bd_accounts
   SET address = COALESCE(address, '31741 Rancho Viejo Rd B'),
       phone   = COALESCE(phone,   '+19498681220')
 WHERE id = '258d79f0-fa02-455f-a3aa-7cbd9f15651f'::uuid;

-- Atria San Juan  →  existing id 87696222-9ada-4411-8e72-653feaa8d292
UPDATE bd_accounts
   SET address = COALESCE(address, '32353 San Juan Creek Rd'),
       phone   = COALESCE(phone,   '+19496611220')
 WHERE id = '87696222-9ada-4411-8e72-653feaa8d292'::uuid;

-- Capistrano Senior Living  →  existing id bd99c52d-80e2-40e6-8766-29bf7f68ec78
UPDATE bd_accounts
   SET address = COALESCE(address, '31741 Rancho Viejo Rd A'),
       phone   = COALESCE(phone,   '+19492488855')
 WHERE id = 'bd99c52d-80e2-40e6-8766-29bf7f68ec78'::uuid;

-- Capistrano Beach Care Center  →  existing id 85d9159e-40e6-4e37-be18-fabc3f983e63
UPDATE bd_accounts
   SET address = COALESCE(address, '35410 Del Rey, Dana Point 92624'),
       phone   = COALESCE(phone,   '+19494965786')
 WHERE id = '85d9159e-40e6-4e37-be18-fabc3f983e63'::uuid;

-- Sea Bluffs, Ivy Signature Living  →  existing id 956ca760-55a4-48bb-bb40-08930dc03de9
UPDATE bd_accounts
   SET address = COALESCE(address, '25411 Sea Bluffs Dr'),
       phone   = COALESCE(phone,   '+19492343000')
 WHERE id = '956ca760-55a4-48bb-bb40-08930dc03de9'::uuid;

-- Raya's Paradise  →  existing id 7f8c9961-caa8-44d6-a2d5-b8ea37ab2341
UPDATE bd_accounts
   SET address = COALESCE(address, '101 Avenida Calafia'),
       phone   = COALESCE(phone,   '+19494209898')
 WHERE id = '7f8c9961-caa8-44d6-a2d5-b8ea37ab2341'::uuid;

-- San Clemente Villas  →  existing id e580d9da-5c92-4da3-9212-a6c8107a5763
UPDATE bd_accounts
   SET address = COALESCE(address, '660 Camino De Los Mares'),
       phone   = COALESCE(phone,   '+19492087611')
 WHERE id = 'e580d9da-5c92-4da3-9212-a6c8107a5763'::uuid;

-- ─────────────────────────────────────────────────────────────
-- 3. Insert new prospect accounts
-- ─────────────────────────────────────────────────────────────
--
-- 167 new accounts from the doc.
--
-- ON CONFLICT DO NOTHING against the partial unique index above
-- so re-running this migration after the first apply is a no-op.

INSERT INTO bd_accounts (
  org_id, name, account_type, facility_subtype, professional_subtype,
  city, address, phone, source
)
VALUES
  (public.default_org_id(), 'Newport Nursing and Rehabilitation Center', 'facility', 'snf', NULL, 'Newport Beach', '1555 Superior Ave', '+19496467764', 'research_import'),
  (public.default_org_id(), 'Newport Nursing and Rehab', 'facility', 'alf', NULL, 'Newport Beach', '1555 Superior Ave, Newport Beach 92663', NULL, 'research_import'),
  (public.default_org_id(), 'Atria Newport Plaza', 'facility', 'alf', NULL, 'Newport Beach', '1455 Superior Ave', NULL, 'research_import'),
  (public.default_org_id(), 'Newport Senior Living', 'facility', 'alf', NULL, 'Newport Beach', '2412 Holly Ln', NULL, 'research_import'),
  (public.default_org_id(), 'Crown Cove', 'facility', 'alf', NULL, 'Newport Beach', '3901 E Coast Hwy, Corona Del Mar', '+19497602800', 'research_import'),
  (public.default_org_id(), 'OC Elder Law', 'professional', NULL, 'attorney', 'Newport Beach', '4425 Jamboree Rd #115', '+19496196778', 'research_import'),
  (public.default_org_id(), 'Meier Law Firm', 'professional', NULL, 'attorney', 'Newport Beach', '450 Newport Center Dr', '+19497180420', 'research_import'),
  (public.default_org_id(), 'Morgan Law Group', 'professional', NULL, 'attorney', 'Newport Beach', '1500 Quail St #540', '+19492601400', 'research_import'),
  (public.default_org_id(), 'Sandoval Legacy Group', 'professional', NULL, 'attorney', 'Newport Beach', '4940 Campus Dr #A', '+19497966500', 'research_import'),
  (public.default_org_id(), 'Soto Law Group', 'professional', NULL, 'attorney', 'Newport Beach', '4041 MacArthur Blvd #200', '+18887357686', 'research_import'),
  (public.default_org_id(), 'The Walker Law Firm', 'professional', NULL, 'attorney', 'Newport Beach', '1451 Quail St #104', '+18005925537', 'research_import'),
  (public.default_org_id(), 'Jasmine Gomez MacArthur Blvd #500', 'professional', NULL, 'attorney', 'Newport Beach', NULL, '+15622281535', 'research_import'),
  (public.default_org_id(), 'Miramontes Capital', 'professional', NULL, 'financial_planner', 'Newport Beach', '4701 Teller Ave', '+18004601595', 'research_import'),
  (public.default_org_id(), 'Tidecrest Wealth Management', 'professional', NULL, 'financial_planner', 'Newport Beach', '888 San Clemente Dr #130', '+19493355202', 'research_import'),
  (public.default_org_id(), 'Essential Trust Financial', 'professional', NULL, 'financial_planner', 'Newport Beach', '895 Dove St, 3rd Floor', '+19495020898', 'research_import'),
  (public.default_org_id(), 'Mercer Advisors', 'professional', NULL, 'financial_planner', 'Newport Beach', '620 Newport Center Dr #1030', '+18003943894', 'research_import'),
  (public.default_org_id(), 'Mariner Wealth Advisors', 'professional', NULL, 'financial_planner', 'Newport Beach', '5000 Birch St #505', '+19493235480', 'research_import'),
  (public.default_org_id(), 'Knightsbridge Wealth Management', 'professional', NULL, 'financial_planner', 'Newport Beach', '450 Newport Center Dr #625', '+19496444444', 'research_import'),
  (public.default_org_id(), 'Windfall Financial Advisors', 'professional', NULL, 'financial_planner', 'Newport Beach', '620 Newport Center Dr #1100', '+19492057002', 'research_import'),
  (public.default_org_id(), 'Beacon Pointe Advisors', 'professional', NULL, 'financial_planner', 'Newport Beach', '24 Corporate Plaza Dr #150', '+19497181600', 'research_import'),
  (public.default_org_id(), 'BNY Wealth Newport Beach', 'professional', NULL, 'financial_planner', 'Newport Beach', '1600 Newport Center Dr #200', '+19492535000', 'research_import'),
  (public.default_org_id(), 'Merrill Lynch Wealth Management', 'professional', NULL, 'financial_planner', 'Newport Beach', '520 Newport Center Dr', '+19497216100', 'research_import'),
  (public.default_org_id(), 'Pence Wealth Management', 'professional', NULL, 'financial_planner', 'Newport Beach', '5000 Birch St #8000', '+19496608777', 'research_import'),
  (public.default_org_id(), 'Concierge Senior Care Management Services', 'professional', NULL, 'gcm', 'Newport Beach', '4029 Westerly Pl #110', '+19495699100', 'research_import'),
  (public.default_org_id(), 'Optimal Senior Care Solutions', 'professional', NULL, 'gcm', 'Newport Beach', '895 Dove St #300', '+19495352211', 'research_import'),
  (public.default_org_id(), 'Dr. Tannaz Meisami, MD', 'professional', NULL, 'physician', 'Newport Beach', '520 Superior Ave #360', '+19496441025', 'research_import'),
  (public.default_org_id(), 'Dr. John D. Homan, MD', 'professional', NULL, 'physician', 'Newport Beach', '520 Superior Ave #255', '+19497209266', 'research_import'),
  (public.default_org_id(), 'Dr. Rena Ahuja, MD', 'professional', NULL, 'physician', 'Newport Beach', '355 Placentia Ave #209', '+19492092789', 'research_import'),
  (public.default_org_id(), 'Hoag Concierge Medicine – Newport Beach', 'professional', NULL, 'physician', 'Newport Beach', '500 Superior Ave #200', '+19496292600', 'research_import'),
  (public.default_org_id(), 'Private Physicians Medical Associates (PPMA)', 'professional', NULL, 'physician', 'Newport Beach', '520 Superior Ave', '+19495668179', 'research_import'),
  (public.default_org_id(), 'Dr. Sanaz Khorrami, MD', 'professional', NULL, 'physician', 'Newport Beach', '355 Placentia Ave #99', '+19496500616', 'research_import'),
  (public.default_org_id(), 'Newport Concierge Physicians', 'professional', NULL, 'physician', 'Newport Beach', '280 Newport Center Dr #120', '+19495936797', 'research_import'),
  (public.default_org_id(), 'Personal Concierge Physicians', 'professional', NULL, 'physician', 'Newport Beach', '2121 E Coast Hwy, Corona Del Mar', '+19497063300', 'research_import'),
  (public.default_org_id(), 'Dr. Ramin Alizadeh, MD', 'professional', NULL, 'physician', 'Newport Beach', '400 Newport Center Dr #601', '+19495207322', 'research_import'),
  (public.default_org_id(), 'Kaiser Permanente OC – Irvine Medical Center', 'facility', 'hospital', NULL, 'Irvine', '6640 Alton Pkwy', '+18335742273', 'research_import'),
  (public.default_org_id(), 'UCI Health', 'facility', 'hospital', NULL, 'Irvine', '19210 Jamboree Rd', '+16575797000', 'research_import'),
  (public.default_org_id(), 'UCI Health Gottschalk Medical Plaza', 'facility', 'hospital', NULL, 'Irvine', '1 Medical Plaza Dr', '+19498248600', 'research_import'),
  (public.default_org_id(), 'Brookdale Irvine', 'facility', 'alf', NULL, 'Irvine', '10 Marquette', '+19498543766', 'research_import'),
  (public.default_org_id(), 'Snyder Law, PC', 'professional', NULL, 'attorney', 'Irvine', '2 Park Plaza #480', NULL, 'research_import'),
  (public.default_org_id(), 'OC Wills & Trust Attorneys', 'professional', NULL, 'attorney', 'Irvine', '15635 Alton Pkwy #125', '+19497558334', 'research_import'),
  (public.default_org_id(), 'Law Stein Anderson, LLP', 'professional', NULL, 'attorney', 'Irvine', '2601 Main St #1200', '+19495014800', 'research_import'),
  (public.default_org_id(), 'Mortensen & Reinheimer, PC', 'professional', NULL, 'attorney', 'Irvine', '2855 Michelle Dr #120', '+17143846053', 'research_import'),
  (public.default_org_id(), 'Law Office of Jonathan Alexander', 'professional', NULL, 'attorney', 'Irvine', '300 Spectrum Center Dr #400', '+19493347823', 'research_import'),
  (public.default_org_id(), 'MKM Attorney at Law, P.C.', 'professional', NULL, 'attorney', 'Irvine', '8583 Irvine Center Dr #460', '+19496881693', 'research_import'),
  (public.default_org_id(), 'BML Wealth Management', 'professional', NULL, 'financial_planner', 'Irvine', '2 Park Plaza #800', '+19496829105', 'research_import'),
  (public.default_org_id(), 'Falcon Wealth Planning', 'professional', NULL, 'financial_planner', 'Irvine', '2030 Main St, 13th Floor', '+18559632526', 'research_import'),
  (public.default_org_id(), 'Clearview Wealth Management', 'professional', NULL, 'financial_planner', 'Irvine', '4 Venture #120', '+19493336394', 'research_import'),
  (public.default_org_id(), 'StrateFi Wealth Management', 'professional', NULL, 'financial_planner', 'Irvine', '18881 Von Karman Ave #410', '+19493458181', 'research_import'),
  (public.default_org_id(), 'Irvine Wealth Management', 'professional', NULL, 'financial_planner', 'Irvine', '9870 Research Dr', '+19497881828', 'research_import'),
  (public.default_org_id(), 'Pure Financial Advisors', 'professional', NULL, 'financial_planner', 'Irvine', '2020 Main St #690', '+19497774130', 'research_import'),
  (public.default_org_id(), 'Care Planning Institute', 'professional', NULL, 'gcm', 'Irvine', '7545 Irvine Center Dr #200', '+18774878166', 'research_import'),
  (public.default_org_id(), 'Arosa Orange County', 'professional', NULL, 'gcm', 'Irvine', '2151 Michelson Dr #160', '+19497949470', 'research_import'),
  (public.default_org_id(), 'Seniors Helping Seniors South OC', 'professional', NULL, 'gcm', 'Irvine', '16480 Bake Pkwy', '+19494293365', 'research_import'),
  (public.default_org_id(), 'Dr. Simin Torabzadeh, MD UCI Health', 'professional', NULL, 'physician', 'Irvine', '1 Medical Plaza Dr', '+19498248600', 'research_import'),
  (public.default_org_id(), 'Dr. Lynda Adrig, MD', 'professional', NULL, 'physician', 'Irvine', '3943 Irvine Blvd', '+17144179322', 'research_import'),
  (public.default_org_id(), 'Dr. Hamid Eskandari – Shafa Medical Center', 'professional', NULL, 'physician', 'Irvine', '26730 Towne Centre Dr, Foothill Ranch', '+19495595153', 'research_import'),
  (public.default_org_id(), 'Embrace Direct Primary Care – Dr. Jeffrey Young, DO', 'professional', NULL, 'physician', 'Irvine', '41 Creek Rd #310', '+19499904637', 'research_import'),
  (public.default_org_id(), 'Halcyon Health Direct Primary Care', 'professional', NULL, 'physician', 'Irvine', '19712 MacArthur Blvd #100', '+19494868530', 'research_import'),
  (public.default_org_id(), 'Portola Direct Primary Care – Dr. Johnny Tsai & Dr. Jennifer Dong', 'professional', NULL, 'physician', 'Irvine', '1190 Roosevelt #100', '+19493464456', 'research_import'),
  (public.default_org_id(), 'mdPersonal Concierge Functional Medicine', 'professional', NULL, 'physician', 'Irvine', '4980 Barranca Pkwy #207', '+19495025656', 'research_import'),
  (public.default_org_id(), 'Hoag Health Center – Foothill Ranch', 'facility', 'other', NULL, 'Foothill Ranch', '26672 Portola Pkwy, Foothill Ranch 92610', '+18004004624', 'research_import'),
  (public.default_org_id(), 'Kaiser Permanente – Foothill Ranch', 'facility', 'other', NULL, 'Foothill Ranch', '26882 Towne Centre Dr, Foothill Ranch 92610', '+18335742273', 'research_import'),
  (public.default_org_id(), 'Freedom Village Health Care Center', 'facility', 'snf', NULL, 'Lake Forest', '23442 El Toro Rd, Lake Forest', NULL, 'research_import'),
  (public.default_org_id(), 'Sacred Heart Senior Care', 'facility', 'alf', NULL, 'Lake Forest', '25602 Willow Bend, Lake Forest 92630', '+19496007009', 'research_import'),
  (public.default_org_id(), 'Respit Manor Senior Living', 'facility', 'alf', NULL, 'Lake Forest', '23255 Respit Dr, Lake Forest 92630', '+19497740262', 'research_import'),
  (public.default_org_id(), 'Villas by Doctor Roya', 'facility', 'alf', NULL, 'Lake Forest', '23232 La Vaca St, Lake Forest 92630', '+19498779070', 'research_import'),
  (public.default_org_id(), 'Wonder''s Years (Board and Care)', 'facility', 'alf', NULL, 'Lake Forest', '24301 Bark St, Lake Forest 92630', '+19492154087', 'research_import'),
  (public.default_org_id(), 'Otilia''s Board and Care', 'facility', 'alf', NULL, 'Lake Forest', '24251 Bark St, Lake Forest 92630', '+19494299155', 'research_import'),
  (public.default_org_id(), 'Reynolds & Powers', 'professional', NULL, 'attorney', 'Lake Forest', '23832 Rockfield Blvd #250, Lake Forest 92630', '+19495988888', 'research_import'),
  (public.default_org_id(), 'Sabeti Law & Associates', 'professional', NULL, 'attorney', 'Lake Forest', '23832 Rockfield Blvd #175, Lake Forest 92630', '+19493262626', 'research_import'),
  (public.default_org_id(), 'Daniel J. Cooper Law Offices', 'professional', NULL, 'attorney', 'Lake Forest', '23101 Lake Center Dr #320, Lake Forest 92630', '+19498598456', 'research_import'),
  (public.default_org_id(), 'Law Office of Jerome J. Carrasco', 'professional', NULL, 'attorney', 'Lake Forest', '26459 Rancho Pkwy S, Lake Forest 92630', '+19498309970', 'research_import'),
  (public.default_org_id(), 'Lee & Keary: Attorneys at Law', 'professional', NULL, 'attorney', 'Foothill Ranch', '26000 Towne Centre Dr N #200, Foothill Ranch 92610', '+19499161600', 'research_import'),
  (public.default_org_id(), 'Haussmann Financial', 'professional', NULL, 'financial_planner', 'Lake Forest', '23201 Lake Center Dr #300, Lake Forest 92630', '+18007738700', 'research_import'),
  (public.default_org_id(), 'Edward Jones – Mark Denali', 'professional', NULL, 'financial_planner', 'Foothill Ranch', '27042 Towne Centre Dr #205, Foothill Ranch 92610', '+19495972167', 'research_import'),
  (public.default_org_id(), 'Financial Professionals Group (FPG / Simplicity)', 'professional', NULL, 'financial_planner', 'Foothill Ranch', '26741 Portola Pkwy, Foothill Ranch 92610', '+19494550119', 'research_import'),
  (public.default_org_id(), 'Wealth Management Advisers', 'professional', NULL, 'financial_planner', 'Lake Forest', '1 Spectrum Pointe Dr #210, Lake Forest 92630', '+19496009900', 'research_import'),
  (public.default_org_id(), 'Balanced Wealth Management', 'professional', NULL, 'financial_planner', 'Lake Forest', '9 Orchard Rd #104, Lake Forest 92630', '+19496775707', 'research_import'),
  (public.default_org_id(), 'Monin Group – Raymond James', 'professional', NULL, 'financial_planner', 'Lake Forest', '1 Orchard Rd #130, Lake Forest 92630', '+19499750039', 'research_import'),
  (public.default_org_id(), 'Jones Associates / JW Cole Financial', 'professional', NULL, 'financial_planner', 'Lake Forest', '26477 Rancho Pkwy S, Lake Forest 92630', '+19496991660', 'research_import'),
  (public.default_org_id(), 'O''Neill Financial Management', 'professional', NULL, 'financial_planner', 'Lake Forest', '23201 Lake Center Dr #215, Lake Forest 92630', '+19495821577', 'research_import'),
  (public.default_org_id(), 'Home2HomeAgency', 'professional', NULL, 'gcm', 'Foothill Ranch', NULL, '+19498806464', 'research_import'),
  (public.default_org_id(), 'Dr. Hamid Eskandari – Shafa Medical Center', 'professional', NULL, 'physician', 'Foothill Ranch', '26730 Towne Centre Dr #102, Foothill Ranch 92610', '+19495595153', 'research_import'),
  (public.default_org_id(), 'Mission Heritage Family Medicine', 'professional', NULL, 'physician', 'Foothill Ranch', '26795 Portola Pkwy, Foothill Ranch 92610', '+19498299403', 'research_import'),
  (public.default_org_id(), 'Dr. Philip Cecchini, MD', 'professional', NULL, 'physician', 'Foothill Ranch', '26795 Portola Pkwy, Foothill Ranch 92610', '+19498299403', 'research_import'),
  (public.default_org_id(), 'Dr. Danette Taylor, MD', 'professional', NULL, 'physician', 'Foothill Ranch', '26672 Portola Pkwy #104, Foothill Ranch 92610', '+19495570750', 'research_import'),
  (public.default_org_id(), 'Mission Heritage Family Medicine', 'professional', NULL, 'physician', 'Lake Forest', '22621 Lake Forest Dr #D1, Lake Forest 92630', '+19492426902', 'research_import'),
  (public.default_org_id(), 'Lake Forest Medical Group', 'professional', NULL, 'physician', 'Lake Forest', '24401 Muirlands Blvd #A, Lake Forest 92630', '+19497701950', 'research_import'),
  (public.default_org_id(), 'Dels Haven Andrea Way, Laguna Beach', 'facility', 'alf', NULL, 'Laguna Beach', NULL, '+19494183222', 'research_import'),
  (public.default_org_id(), 'Schlau Rogers LLP', 'professional', NULL, 'attorney', 'Laguna Beach', '1968 S Coast Hwy #2498, Laguna Beach', '+19498730662', 'research_import'),
  (public.default_org_id(), 'Anderson Law Group', 'professional', NULL, 'attorney', 'Laguna Beach', '1000 N Coast Hwy, Laguna Beach', '+19497154303', 'research_import'),
  (public.default_org_id(), 'Estate Law & Estate Plan, Inc.', 'professional', NULL, 'attorney', 'Laguna Beach', '352 3rd St #301, Laguna Beach', '+19494243107', 'research_import'),
  (public.default_org_id(), 'Coast Counsel, APC', 'professional', NULL, 'attorney', 'Laguna Beach', '1000 N Coast Hwy #6, Laguna Beach', '+19497061470', 'research_import'),
  (public.default_org_id(), 'Law Offices of James LeBloch', 'professional', NULL, 'attorney', 'Laguna Beach', '422 Glenneyre St #1, Laguna Beach', '+19494991975', 'research_import'),
  (public.default_org_id(), 'WCM Investment Management', 'professional', NULL, 'financial_planner', 'Laguna Beach', '281 Brooks St, Laguna Beach', '+19493800200', 'research_import'),
  (public.default_org_id(), 'Sagent Wealth Management', 'professional', NULL, 'financial_planner', 'Laguna Beach', '1489 Glenneyre St, Laguna Beach', '+18337730041', 'research_import'),
  (public.default_org_id(), 'The Zandbergen Group', 'professional', NULL, 'financial_planner', 'Laguna Beach', '32322 Coast Hwy #D, Laguna Beach', '+19496680771', 'research_import'),
  (public.default_org_id(), 'Edward Jones – Maggie Klein, CFP®', 'professional', NULL, 'financial_planner', 'Laguna Beach', '32392 Coast Hwy #190, Laguna Beach', '+19494994028', 'research_import'),
  (public.default_org_id(), 'Dr. Jill M. Panitch, MD', 'professional', NULL, 'physician', 'Laguna Beach', '370 Ocean Ave, Laguna Beach', '+19495570610', 'research_import'),
  (public.default_org_id(), 'Dolce MD – Dr. John Sanguedolce', 'professional', NULL, 'physician', 'Laguna Beach', '310 Glenneyre St, Laguna Beach', '+19492099266', 'research_import'),
  (public.default_org_id(), 'Seasons at Laguna', 'facility', 'alf', NULL, 'Laguna Niguel', '28961 Paseo De Ocaso, Laguna Niguel', '+18003409704', 'research_import'),
  (public.default_org_id(), 'Signature Resident Care', 'facility', 'alf', NULL, 'Laguna Hills', '25002 Sausalito St, Laguna Hills', '+19492201412', 'research_import'),
  (public.default_org_id(), 'Ivy Park at Laguna Woods', 'facility', 'alf', NULL, 'Laguna Woods', '24441 C. Sonora, Laguna Woods', '+19493138668', 'research_import'),
  (public.default_org_id(), 'Whispering Fountains', 'facility', 'alf', NULL, 'Laguna Woods', '24300 El Toro Rd, Laguna Woods', '+19494570327', 'research_import'),
  (public.default_org_id(), 'Healthy Aging Center', 'facility', 'alf', NULL, 'Laguna Woods', '24260 El Toro Rd, Laguna Woods', '+19498559444', 'research_import'),
  (public.default_org_id(), 'Pevney Estate Planning', 'professional', NULL, 'attorney', 'Laguna Hills', '25201 Paseo De Alicia #140, Laguna Hills', '+19493772996', 'research_import'),
  (public.default_org_id(), 'Geiger Law Office', 'professional', NULL, 'attorney', 'Laguna Niguel', '32451 Golden Lantern #307, Laguna Niguel', '+19497692440', 'research_import'),
  (public.default_org_id(), 'Parker Law Offices', 'professional', NULL, 'attorney', 'Laguna Niguel', '28202 Cabot Rd, 3rd Floor, Laguna Niguel', '+19493853130', 'research_import'),
  (public.default_org_id(), 'Winstead Law Group', 'professional', NULL, 'attorney', 'Laguna Niguel', '28202 Cabot Rd #300, Laguna Niguel', '+19496399606', 'research_import'),
  (public.default_org_id(), 'Law Office of David Salvin', 'professional', NULL, 'attorney', 'Laguna Hills', '23276 S Pointe Dr #216, Laguna Hills', '+19493056400', 'research_import'),
  (public.default_org_id(), 'Law Office of Fay Blix', 'professional', NULL, 'attorney', 'Laguna Hills', '24031 El Toro Rd #301, Laguna Hills', '+19495447211', 'research_import'),
  (public.default_org_id(), 'The Law Offices of Brian S. Mandel', 'professional', NULL, 'attorney', 'Laguna Hills', '24031 El Toro Rd #210, Laguna Hills', '+19496600007', 'research_import'),
  (public.default_org_id(), 'The Financial Coaching Group', 'professional', NULL, 'financial_planner', 'Laguna Hills', '23332 Mill Creek Dr #105, Laguna Hills', '+19496006060', 'research_import'),
  (public.default_org_id(), 'Trusted Financial Advisors', 'professional', NULL, 'financial_planner', 'Laguna Niguel', '30101 Town Center Dr, Laguna Niguel', '+19492492057', 'research_import'),
  (public.default_org_id(), 'Align Wealth Advisors', 'professional', NULL, 'financial_planner', 'Laguna Hills', '24031 El Toro Rd #210, Laguna Hills', '+19497158585', 'research_import'),
  (public.default_org_id(), 'Laguna Financial Advisors', 'professional', NULL, 'financial_planner', 'Laguna Hills', '23101 Moulton Pkwy #108, Laguna Hills', '+19498558889', 'research_import'),
  (public.default_org_id(), 'MemorialCare Medical Group 55+', 'professional', NULL, 'physician', 'Laguna Woods', '24268 El Toro Rd, Laguna Woods', '+18776963622', 'research_import'),
  (public.default_org_id(), 'South Coast Family Medical Center – Dr. Lauren & Dr. Chris Davis', 'professional', NULL, 'physician', 'Laguna Niguel', '25500 Rancho Niguel Rd #100, Laguna Niguel', '+19496430500', 'research_import'),
  (public.default_org_id(), 'Dr. Patrick Thompson, MD', 'professional', NULL, 'physician', 'Laguna Hills', '26538 Moulton Pkwy #38E, Laguna Hills', '+18776963622', 'research_import'),
  (public.default_org_id(), 'Dr. Haleh Khoshreza, MD', 'professional', NULL, 'physician', 'Laguna Hills', '26538 Moulton Pkwy #38E, Laguna Hills', '+18776963622', 'research_import'),
  (public.default_org_id(), 'Dr. Brian A. Leish, MD', 'professional', NULL, 'physician', 'Laguna Hills', '24411 Health Center Dr #460, Laguna Hills', '+19493737799', 'research_import'),
  (public.default_org_id(), 'Dr. Roger N. Tran, MD', 'professional', NULL, 'physician', 'Laguna Hills', '24411 Health Center Dr, Laguna Hills', '+19493737799', 'research_import'),
  (public.default_org_id(), 'Harbor Direct Primary Care – Dr. Jihan Ansari', 'professional', NULL, 'physician', 'Laguna Hills', '24953 Paseo De Valencia Bldg B, Laguna Hills', '+19497994786', 'research_import'),
  (public.default_org_id(), 'OC House Calls – Dr. Khaneki', 'professional', NULL, 'physician', 'Laguna Hills', NULL, '+19492041334', 'research_import'),
  (public.default_org_id(), 'Hoag Urgent Care Aliso Viejo', 'facility', 'other', NULL, 'Aliso Viejo', '26671 Aliso Creek Rd #101', '+19497913107', 'research_import'),
  (public.default_org_id(), 'Marque Urgent Care', 'facility', 'other', NULL, 'Aliso Viejo', '26831 Aliso Creek Rd #200', '+19497609222', 'research_import'),
  (public.default_org_id(), 'Law Office of James Burns 6B Liberty #130', 'professional', NULL, 'attorney', 'Aliso Viejo', NULL, '+19493058642', 'research_import'),
  (public.default_org_id(), 'Estate Law, Inc.', 'professional', NULL, 'attorney', 'Aliso Viejo', '120 Vantis Dr #300', '+19494243107', 'research_import'),
  (public.default_org_id(), 'Law Office of Deborah Coel', 'professional', NULL, 'attorney', 'Aliso Viejo', '33 Brookline', '+19496828019', 'research_import'),
  (public.default_org_id(), 'Heritage Law, LLP', 'professional', NULL, 'attorney', 'Aliso Viejo', '120 Vantis Dr #300', '+19493826400', 'research_import'),
  (public.default_org_id(), 'Eden Financial', 'professional', NULL, 'financial_planner', 'Aliso Viejo', '26895 Aliso Creek Rd #B-237', '+19498007835', 'research_import'),
  (public.default_org_id(), 'Pacific Coast Wealth Management', 'professional', NULL, 'financial_planner', 'Aliso Viejo', '120 Vantis Dr #300', '+13108791563', 'research_import'),
  (public.default_org_id(), 'Focus Wealth Advisors – Ken Franklin, CFP® 6B Liberty #225', 'professional', NULL, 'financial_planner', 'Aliso Viejo', NULL, '+19496600088', 'research_import'),
  (public.default_org_id(), 'Dr. Morris Hasson, MD', 'professional', NULL, 'physician', 'Aliso Viejo', '5 Journey #240', '+19493822050', 'research_import'),
  (public.default_org_id(), 'OC House Calls – Dr. Khaneki', 'professional', NULL, 'physician', 'Aliso Viejo', NULL, '+19492041334', 'research_import'),
  (public.default_org_id(), 'Reata Glen (CCRC)', 'facility', 'snf', NULL, 'Mission Viejo', '2 Las Estrellas Loop, Rancho Mission Viejo', '+19495452200', 'research_import'),
  (public.default_org_id(), 'Ohana Care', 'facility', 'alf', NULL, 'Mission Viejo', '24352 Augustin St', '+19495472217', 'research_import'),
  (public.default_org_id(), 'Active Senior Home Care', 'facility', 'alf', NULL, 'Mission Viejo', '26771 Via Victoria', '+19493801143', 'research_import'),
  (public.default_org_id(), 'Law Offices of Joseph P. Foley', 'professional', NULL, 'attorney', 'Mission Viejo', '23312 Madero #F', '+19497709949', 'research_import'),
  (public.default_org_id(), 'Gipe Law, P.C.', 'professional', NULL, 'attorney', 'Mission Viejo', '27201 Puerta Real #300', '+19497994774', 'research_import'),
  (public.default_org_id(), 'Fenelli Law Firm', 'professional', NULL, 'attorney', 'Mission Viejo', '24800 Chrisanta Dr #110', '+19496990000', 'research_import'),
  (public.default_org_id(), 'Laguna Legal', 'professional', NULL, 'attorney', 'Mission Viejo', '24800 Chrisanta Dr #200', '+19494979800', 'research_import'),
  (public.default_org_id(), 'Progressive Strategies Financial Group', 'professional', NULL, 'financial_planner', 'Mission Viejo', '27281 Las Ramblas #138', '+19492043800', 'research_import'),
  (public.default_org_id(), 'Strivent Financial', 'professional', NULL, 'financial_planner', 'Mission Viejo', '27201 Puerta Real #300', '+18008936783', 'research_import'),
  (public.default_org_id(), 'Senior Life Management, Inc.', 'professional', NULL, 'financial_planner', 'Mission Viejo', '27001 La Paz Rd #201', '+19497161266', 'research_import'),
  (public.default_org_id(), 'Dr. Saghi Rokhshadfar, MD', 'professional', NULL, 'physician', 'Mission Viejo', '23512 Madero', '+18776963622', 'research_import'),
  (public.default_org_id(), 'Regina Baldo, NP', 'professional', NULL, 'physician', 'Mission Viejo', '23512 Madero', '+18776963622', 'research_import'),
  (public.default_org_id(), 'Dr. Marjan Pedarsani, MD', 'professional', NULL, 'physician', 'Mission Viejo', '23512 Madero', '+18776963622', 'research_import'),
  (public.default_org_id(), 'Dr. Ian Bare, MD', 'professional', NULL, 'physician', 'Mission Viejo', '30492 Gateway Pl #110', '+18776963622', 'research_import'),
  (public.default_org_id(), 'Coastal Concierge Primary Care', 'professional', NULL, 'physician', 'Mission Viejo', '26732 Crown Valley Pkwy #571', '+19495246200', 'research_import'),
  (public.default_org_id(), 'Law Office of David S. Rubalcava Oso Pkwy, RSM', 'professional', NULL, 'attorney', 'Rancho Santa Margarita', NULL, '+19493151692', 'research_import'),
  (public.default_org_id(), 'Edward Jones – Jeff Albert, CRPS®', 'professional', NULL, 'financial_planner', 'Rancho Santa Margarita', '22342 Avenida Empresa #240', '+19498581006', 'research_import'),
  (public.default_org_id(), 'Law Office of Timothy Cahill Pickart', 'professional', NULL, 'attorney', 'Ladera Ranch', '999 Corporate Dr #100, Ladera Ranch', '+19494003183', 'research_import'),
  (public.default_org_id(), 'Silverado San Juan Capistrano Memory Care', 'facility', 'memory_care', NULL, 'San Juan Capistrano', '30311 Camino Capistrano', '+19492400550', 'research_import'),
  (public.default_org_id(), 'Ivy Park at San Juan Capistrano', 'facility', 'alf', NULL, 'San Juan Capistrano', '32200 Del Obispo St', '+19495183161', 'research_import'),
  (public.default_org_id(), 'Serra Sol Memory Care', 'facility', 'memory_care', NULL, 'San Juan Capistrano', '31451 Avenida Los Cerritos', '+19494852022', 'research_import'),
  (public.default_org_id(), 'Law Office of Cheryl L. Walsh', 'professional', NULL, 'attorney', 'San Juan Capistrano', '27282 Calle Arroyo', '+19492409003', 'research_import'),
  (public.default_org_id(), 'Williams Financial Advisors', 'professional', NULL, 'financial_planner', 'San Juan Capistrano', '30200 Rancho Viejo Rd #G', '+19494962521', 'research_import'),
  (public.default_org_id(), 'Edward Jones – Mahnaz Nouri', 'professional', NULL, 'financial_planner', 'San Juan Capistrano', '29122 Rancho Viejo Rd #113', '+19493470049', 'research_import'),
  (public.default_org_id(), 'Aegis Living Dana Point', 'facility', 'alf', NULL, 'Dana Point', '26922 Camino De Estrella, Dana Point 92624', '+19497398530', 'research_import'),
  (public.default_org_id(), 'Meyer Estate Law, P.C. – Jan Meyer Dana Point', 'professional', NULL, 'attorney', 'Dana Point', NULL, '+19496079412', 'research_import'),
  (public.default_org_id(), 'KMH Law Group – Katherine Harrington', 'professional', NULL, 'attorney', 'Dana Point', '34204 Pacific Coast Hwy', '+19493570757', 'research_import'),
  (public.default_org_id(), 'The Clark Group Asset Management', 'professional', NULL, 'financial_planner', 'Dana Point', '24941 Dana Point Harbor Dr #C210', '+19495583898', 'research_import'),
  (public.default_org_id(), 'Laguna Wealth Advisors', 'professional', NULL, 'financial_planner', 'Dana Point', '24551 Del Prado Ave', '+19494644466', 'research_import'),
  (public.default_org_id(), 'The Seville', 'facility', 'alf', NULL, 'San Clemente', '2421 Calle Frontera', '+19492366135', 'research_import'),
  (public.default_org_id(), 'Jeffrey R. Hartman', 'professional', NULL, 'attorney', 'San Clemente', '501 N El Camino Real #200', '+19494292578', 'research_import'),
  (public.default_org_id(), 'Law Offices of J. Sean Dumm', 'professional', NULL, 'attorney', 'San Clemente', '665 Camino De Los Mares #204a', '+18882123866', 'research_import')
ON CONFLICT (org_id, lower(name), lower(coalesce(city, '')))
  WHERE source = 'research_import'
DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- 4. Hoag named contacts
-- ─────────────────────────────────────────────────────────────
--
-- Five named Hoag contacts from the doc. All land under the
-- Newport Beach Hoag account. The DO block does an exists-check
-- per contact (case-insensitive name) so re-runs do not create
-- duplicates and we do not need to add a unique constraint on
-- bd_account_contacts (which may have legitimate same-name rows
-- across different accounts).

DO $$
DECLARE
  v_org_id      uuid := public.default_org_id();
  v_account_id  uuid;
BEGIN
  -- Resolve the Newport Beach Hoag account by uuid; this is the
  -- strategic-shared row seeded in 20260513140100. Bail silently
  -- if it doesn't exist (e.g. fresh dev DB without the seed).
  SELECT id INTO v_account_id FROM bd_accounts
    WHERE id = '47cbb432-6bfd-4f29-87e4-d52bbcd61378'::uuid
    LIMIT 1;
  IF v_account_id IS NULL THEN
    RAISE NOTICE 'Newport Beach Hoag account not found; skipping contact seed.';
    RETURN;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM bd_account_contacts
                  WHERE account_id = v_account_id
                    AND lower(name) = lower('Amy Robinson')) THEN
    INSERT INTO bd_account_contacts (
      org_id, account_id, name, role, email, phone_office, notes
    ) VALUES (
      v_org_id, v_account_id, 'Amy Robinson', 'social_worker',
      NULL, NULL, 'Hoag Hospice Liaison.'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM bd_account_contacts
                  WHERE account_id = v_account_id
                    AND lower(name) = lower('Arnetta Robinson')) THEN
    INSERT INTO bd_account_contacts (
      org_id, account_id, name, role, email, phone_office, notes
    ) VALUES (
      v_org_id, v_account_id, 'Arnetta Robinson', 'social_worker',
      'arnetta.robinson@hoag.org', '+19492301155', 'Hoag Hospice Liaison.'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM bd_account_contacts
                  WHERE account_id = v_account_id
                    AND lower(name) = lower('Brittany Carrillo')) THEN
    INSERT INTO bd_account_contacts (
      org_id, account_id, name, role, email, phone_office, notes
    ) VALUES (
      v_org_id, v_account_id, 'Brittany Carrillo', 'social_worker',
      NULL, NULL, 'Palliative Care.'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM bd_account_contacts
                  WHERE account_id = v_account_id
                    AND lower(name) = lower('Jenna Gailani, LCSW')) THEN
    INSERT INTO bd_account_contacts (
      org_id, account_id, name, role, email, phone_office, notes
    ) VALUES (
      v_org_id, v_account_id, 'Jenna Gailani, LCSW', 'social_worker',
      NULL, NULL, 'Fudge Family Acute Rehab.'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM bd_account_contacts
                  WHERE account_id = v_account_id
                    AND lower(name) = lower('Madeline Conrado, LCSW')) THEN
    INSERT INTO bd_account_contacts (
      org_id, account_id, name, role, email, phone_office, notes
    ) VALUES (
      v_org_id, v_account_id, 'Madeline Conrado, LCSW', 'social_worker',
      NULL, NULL, 'Neurology.'
    );
  END IF;

END $$;
