-- Paychex integration Phase 1: timesheets table.
--
-- One row per caregiver per pay period. The source of truth for what
-- gets paid. Drafts are generated by a Phase 3 cron, edited and
-- approved by back office in the Phase 4 UI, then exported (CSV) or
-- submitted (Phase 5 API) to Paychex.
--
-- This table is born multi-tenant: org_id NOT NULL from creation, RLS
-- enabled with a tenant-isolation policy. Phase B of the SaaS retrofit
-- does NOT need to retrofit this table — it ships correct.
--
-- See: docs/plans/2026-04-25-paychex-integration-plan.md
--      ("Data model" → "New tables" → "timesheets").

CREATE TABLE IF NOT EXISTS timesheets (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
  caregiver_id          text NOT NULL REFERENCES caregivers(id) ON DELETE RESTRICT,
  pay_period_start      date NOT NULL,
  pay_period_end        date NOT NULL,
  status                text NOT NULL DEFAULT 'draft'
                          CHECK (status IN (
                            'draft', 'pending_approval', 'approved',
                            'exported', 'submitted', 'paid',
                            'rejected', 'blocked'
                          )),
  regular_hours         numeric(6,2)  NOT NULL DEFAULT 0,
  overtime_hours        numeric(6,2)  NOT NULL DEFAULT 0,
  double_time_hours     numeric(6,2)  NOT NULL DEFAULT 0,
  mileage_total         numeric(8,2)  NOT NULL DEFAULT 0,
  mileage_reimbursement numeric(10,2) NOT NULL DEFAULT 0,
  gross_pay             numeric(10,2) NOT NULL DEFAULT 0,
  -- Approval audit
  approved_by           text,
  approved_at           timestamptz,
  -- Lifecycle markers; both are set independently because a run can
  -- be exported (Phase 4 CSV path) AND/OR submitted (Phase 5 API path)
  -- in different cycles.
  exported_at           timestamptz,
  submitted_at          timestamptz,
  -- Paychex check identifier (Phase 5 only); stays null indefinitely
  -- if TC sticks to the CSV path.
  paychex_check_id      text,
  -- Populated when status = 'blocked' (e.g., caregiver not in Paychex,
  -- rate mismatch, missing clock-out).
  block_reason          text,
  notes                 text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  -- Org-scoped uniqueness: one timesheet per caregiver per period per
  -- org. Stays correct after multi-org expansion.
  CONSTRAINT timesheets_unique_per_period UNIQUE (org_id, caregiver_id, pay_period_start)
);

CREATE INDEX IF NOT EXISTS idx_timesheets_org_period
  ON timesheets (org_id, pay_period_start DESC);

CREATE INDEX IF NOT EXISTS idx_timesheets_caregiver_period
  ON timesheets (caregiver_id, pay_period_start DESC);

-- Phase 4 ThisWeekView reads "what needs review?" — restrict the index
-- to actionable statuses to keep it small.
CREATE INDEX IF NOT EXISTS idx_timesheets_actionable_status
  ON timesheets (org_id, status)
  WHERE status IN ('draft', 'pending_approval', 'blocked');

ALTER TABLE timesheets ENABLE ROW LEVEL SECURITY;

-- Tenant isolation: every authenticated user sees only their org's
-- rows. The JWT carries org_id as a string claim (set by
-- public.custom_access_token_hook). Wrapping auth.jwt() in a SELECT
-- triggers the InitPlan optimization documented in
-- 20260214201225_harden_rls_policies.sql.
CREATE POLICY "tenant_isolation_timesheets"
  ON timesheets FOR ALL
  TO authenticated
  USING      (((SELECT auth.jwt()) ->> 'org_id')::uuid = org_id)
  WITH CHECK (((SELECT auth.jwt()) ->> 'org_id')::uuid = org_id);

-- Edge functions write via the service role key, which bypasses RLS
-- by default at the postgres layer. Explicit policy here keeps the
-- intent visible if RLS bypass behavior ever changes.
CREATE POLICY "service_role_full_access_timesheets"
  ON timesheets FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
