-- User-created follow-up tasks v1 — additive schema for ad-hoc tasks
--
-- Background: migration 20260525000000 built `follow_up_tasks` as a
-- template-driven table. Every row is a concrete instance of a
-- `follow_up_templates` row, anchored to a caregiver+client+shift.
-- That covered the "first-day check-in / 7-day / 14-day / monthly"
-- automation case but left no surface for the office to capture
-- ad-hoc reminders ("call Maria Friday 9am about the I-9", "renew
-- Paychex API key Dec 1", "follow up with the Riverside lead Tue").
--
-- Design (locked with owner 2026-05-27, see docs/TASKS_AND_FOLLOWUPS.md):
--
--   We extend the SAME table rather than build a parallel user_tasks
--   table. One table for template/user/ai → one dashboard, one
--   notification path, one RLS surface, one realtime channel.
--
--   New `source` column distinguishes the three lanes:
--     • 'template' — system-generated by triggers (the existing path)
--     • 'user'     — manually created by a staff member (this PR)
--     • 'ai'       — proposed by the AI assistant and accepted (Phase 3)
--
--   Other new columns:
--     • title        — required for user/ai (template tasks keep using
--                      the joined template name and leave this NULL)
--     • description  — optional freeform body
--     • created_by   — email of the creator (NULL for system rows)
--     • notified_at  — set by the Phase 2 dispatcher cron; the index
--                      below makes the dispatcher's scan O(open due)
--
--   Three previously-NOT-NULL columns become nullable:
--     • template_id  — NULL for user/ai
--     • caregiver_id — NULL when not entity-linked
--     • client_id    — NULL when not entity-linked
--
--   A shape CHECK constraint enforces validity per source:
--     • source='template' must keep today's exact shape
--     • source IN ('user','ai') must carry a title and may link to at
--       most ONE entity (caregiver xor client xor neither)
--
-- Production safety (CLAUDE.md → Prime Directives):
--   • Purely additive. No DROPs of columns/tables/data.
--   • Existing rows logically have source='template' via the column
--     default — Postgres' fast default-fill handles the backfill
--     without rewriting the table.
--   • The CHECK constraint is satisfied by every existing row (all
--     four required template-shape fields are already populated).
--   • RLS unchanged — the existing four staff_select/insert/update/
--     delete policies cover the new rows via the same predicate.
--
-- Idempotent: every ALTER uses IF NOT EXISTS / IF EXISTS guards so
-- the Deploy Database Migrations workflow can re-run safely.

-- ────────────────────────────────────────────────────────────────────
-- 1. New columns
-- ────────────────────────────────────────────────────────────────────

ALTER TABLE public.follow_up_tasks
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'template',
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS created_by text,
  ADD COLUMN IF NOT EXISTS notified_at timestamptz;

-- CHECK constraint on the source column. Done as a separate
-- ADD CONSTRAINT so the column-add stays fast (Postgres won't
-- re-scan to validate the default value), and so a re-run can
-- drop+add the constraint cleanly if we later widen the enum.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'follow_up_tasks_source_check'
      AND conrelid = 'public.follow_up_tasks'::regclass
  ) THEN
    ALTER TABLE public.follow_up_tasks
      ADD CONSTRAINT follow_up_tasks_source_check
      CHECK (source IN ('template', 'user', 'ai'));
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────
-- 2. Relax NOT NULLs that no longer apply to user/ai rows
-- ────────────────────────────────────────────────────────────────────
-- These columns stay required for source='template' via the shape
-- CHECK below, so the existing automation path is unchanged.

ALTER TABLE public.follow_up_tasks
  ALTER COLUMN template_id  DROP NOT NULL,
  ALTER COLUMN caregiver_id DROP NOT NULL,
  ALTER COLUMN client_id    DROP NOT NULL;

-- ────────────────────────────────────────────────────────────────────
-- 3. Shape CHECK — every row must be valid under exactly one source
-- ────────────────────────────────────────────────────────────────────
-- Existing rows (all source='template' via default) satisfy this:
-- they were inserted with NOT NULL template_id+caregiver_id+client_id
-- and have title=NULL (column just added with no value).
--
-- New user/ai rows must provide a non-empty title and may link to at
-- most one entity. "Neither entity" is also valid — supports tasks
-- like "renew Paychex API key" that have no caregiver/client.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'follow_up_tasks_shape_check'
      AND conrelid = 'public.follow_up_tasks'::regclass
  ) THEN
    ALTER TABLE public.follow_up_tasks
      ADD CONSTRAINT follow_up_tasks_shape_check CHECK (
        (
          source = 'template'
          AND template_id  IS NOT NULL
          AND caregiver_id IS NOT NULL
          AND client_id    IS NOT NULL
          AND title        IS NULL
        )
        OR
        (
          source IN ('user', 'ai')
          AND title IS NOT NULL
          AND length(btrim(title)) > 0
          AND template_id IS NULL
          AND NOT (caregiver_id IS NOT NULL AND client_id IS NOT NULL)
        )
      );
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────
-- 4. Indexes for new access patterns
-- ────────────────────────────────────────────────────────────────────

-- Phase 2 dispatcher hot-path: "scan all pending tasks with due_at
-- in the past and notified_at IS NULL". Partial index keeps the
-- working set tiny even as the table grows historically.
CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_dispatch
  ON public.follow_up_tasks (due_at)
  WHERE status = 'pending' AND notified_at IS NULL;

-- "Show me my open tasks" — the future "My Day" filter and the
-- per-user inbox. assigned_to is already populated by user-created
-- tasks (created_by = assigned_to per the locked decision); existing
-- template tasks have assigned_to = NULL today so they're filtered
-- out, which is the intended behavior until a templating decision is
-- made about default assignees.
CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_assigned
  ON public.follow_up_tasks (assigned_to, status, due_at);

-- ────────────────────────────────────────────────────────────────────
-- 5. Sanity check — fail loudly if the columns and constraints didn't land
-- ────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  v_cols integer;
BEGIN
  SELECT count(*) INTO v_cols
    FROM information_schema.columns
   WHERE table_schema = 'public'
     AND table_name   = 'follow_up_tasks'
     AND column_name IN ('source', 'title', 'description', 'created_by', 'notified_at');

  IF v_cols <> 5 THEN
    RAISE EXCEPTION
      'follow_up_tasks user_source migration: expected 5 new columns, found %', v_cols;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'follow_up_tasks_shape_check'
      AND conrelid = 'public.follow_up_tasks'::regclass
  ) THEN
    RAISE EXCEPTION 'follow_up_tasks user_source migration: shape CHECK missing';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'follow_up_tasks_source_check'
      AND conrelid = 'public.follow_up_tasks'::regclass
  ) THEN
    RAISE EXCEPTION 'follow_up_tasks user_source migration: source CHECK missing';
  END IF;
END $$;
