-- Follow-up tasks v1 — concrete, scheduled, completable work items
-- generated automatically when a caregiver-client match first appears
-- in the schedule.
--
-- Office-coordinator feedback (Juliana, 2026-05-22), items #8 + #10:
--   "Create a task dashboard with automated follow-up reminders for
--    both clients and caregivers, including: First day check-in,
--    First week follow-up, Second week follow-up, Monthly check-ins."
--   "Add an option for the system to automatically generate follow-up
--    tasks whenever a caregiver is matched with a new client."
--
-- Design (locked with the owner 2026-05-23):
--
--   1. Two-layer model:
--      • follow_up_templates — configurable cadences (org-scoped).
--        Seeded with 4 defaults: 0d / 7d / 14d / 30d-monthly.
--      • follow_up_tasks — concrete instances generated by triggers.
--
--   2. Anchor: "day of the client's first scheduled shift with this
--      caregiver." NOT "first completed shift" — long shifts ending
--      at 8pm would miss the same-day reminder window. Due-time is
--      09:00 local on the calculated date so the task lands on the
--      Tasks dashboard at the start of business hours.
--
--   3. Triggers:
--      • shifts (AFTER INSERT/UPDATE): if (cg, client) first appears
--        in the schedule, generate instances anchored to NEW.start_time.
--      • caregiver_assignments (AFTER UPDATE): if status flips to
--        'ended', cancel any pending follow-ups for that match.
--
--   4. Recurrence: a cron job (added in a follow-up migration with
--      the edge function) auto-spawns the next instance of a recurring
--      template when the prior one is completed. v1 ships the schema;
--      cron wiring lands when the dispatcher edge function does.
--
--   5. Backfill: NONE. Only new matches going forward get follow-ups.
--      Avoids dropping a backlog of overdue tasks on launch day.
--
-- Multi-tenancy (CLAUDE.md → Prime Directives):
--   • Both tables NOT NULL org_id DEFAULT public.default_org_id().
--   • RLS staff-only (admin + member), org-scoped, via public.is_staff().
--   • No caregiver access in v1 — the PWA does not surface tasks.
--
-- Idempotent: every CREATE / DROP POLICY / DROP TRIGGER uses
-- IF [NOT] EXISTS so the Deploy Database Migrations workflow can
-- re-run safely.

-- ────────────────────────────────────────────────────────────────────
-- 1. follow_up_templates
-- ────────────────────────────────────────────────────────────────────
-- Configurable cadences. Slug + org_id is UNIQUE so the seed and any
-- subsequent edits-by-slug stay coherent across re-runs.
--
-- anchor_event is a CHECK enum so v2 can add new sources (e.g.
-- 'assignment_started', 'phase_change') without code surgery.
--
-- recurring_interval_days NULL means "one-shot". Non-null means the
-- next instance is auto-spawned that many days after the prior is
-- marked done (handled by the cron in a follow-up migration).

CREATE TABLE IF NOT EXISTS public.follow_up_templates (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                   uuid NOT NULL DEFAULT public.default_org_id()
                             REFERENCES public.organizations(id) ON DELETE CASCADE,
  slug                     text NOT NULL,
  name                     text NOT NULL,
  description              text,
  guidance                 text,
  anchor_event             text NOT NULL DEFAULT 'first_scheduled_shift_day'
                             CHECK (anchor_event IN (
                               'first_scheduled_shift_day',
                               'assignment_started'
                             )),
  offset_days              integer NOT NULL DEFAULT 0
                             CHECK (offset_days >= 0),
  recurring_interval_days  integer
                             CHECK (recurring_interval_days IS NULL
                                    OR recurring_interval_days > 0),
  target_type              text NOT NULL DEFAULT 'both'
                             CHECK (target_type IN ('caregiver', 'client', 'both')),
  default_urgency          text NOT NULL DEFAULT 'warning'
                             CHECK (default_urgency IN ('critical', 'warning', 'info')),
  default_assignee_email   text,
  enabled                  boolean NOT NULL DEFAULT true,
  sort_order               integer NOT NULL DEFAULT 0,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_follow_up_templates_org
  ON public.follow_up_templates (org_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_templates_enabled
  ON public.follow_up_templates (org_id, enabled, anchor_event)
  WHERE enabled;

DROP TRIGGER IF EXISTS follow_up_templates_touch_updated_at
  ON public.follow_up_templates;
CREATE TRIGGER follow_up_templates_touch_updated_at
  BEFORE UPDATE ON public.follow_up_templates
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ────────────────────────────────────────────────────────────────────
-- 2. follow_up_tasks
-- ────────────────────────────────────────────────────────────────────
-- Concrete instances. UNIQUE (template_id, caregiver_id, client_id,
-- anchor_shift_id) is the idempotency key — if the trigger fires twice
-- for the same shift, the second insert is rejected cleanly via ON
-- CONFLICT DO NOTHING.
--
-- Status state machine:
--   pending → done (via mark-complete)
--   pending → snoozed (with snoozed_until) → pending (when snooze expires; not enforced at DB layer)
--   pending → cancelled (when assignment ends)
--
-- assigned_to / completed_by are text (matches existing convention —
-- e.g. caregivers.id is text, the events table actor is text).

CREATE TABLE IF NOT EXISTS public.follow_up_tasks (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id              uuid NOT NULL DEFAULT public.default_org_id()
                        REFERENCES public.organizations(id) ON DELETE CASCADE,
  template_id         uuid NOT NULL REFERENCES public.follow_up_templates(id) ON DELETE CASCADE,
  caregiver_id        text NOT NULL REFERENCES public.caregivers(id) ON DELETE CASCADE,
  client_id           text NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  anchor_shift_id     uuid REFERENCES public.shifts(id) ON DELETE SET NULL,
  due_at              timestamptz NOT NULL,
  status              text NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'done', 'snoozed', 'cancelled')),
  urgency             text NOT NULL DEFAULT 'warning'
                        CHECK (urgency IN ('critical', 'warning', 'info')),
  assigned_to         text,
  snoozed_until       timestamptz,
  completed_at        timestamptz,
  completed_by        text,
  completion_note     text,
  cancellation_reason text,
  generated_at        timestamptz NOT NULL DEFAULT now(),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  -- Idempotency key: never two of the same template for the same
  -- match anchored to the same shift. Recurring templates use
  -- anchor_shift_id = NULL for spawned instances, so the partial
  -- unique index below covers them separately.
  UNIQUE (template_id, caregiver_id, client_id, anchor_shift_id)
);

-- For recurring templates, anchor_shift_id is NULL on spawned
-- instances. UNIQUE (template_id, cg, client, NULL) treats NULL as
-- distinct so we still need a guard against duplicate pending
-- recurring instances. Partial unique index on the pending state.
CREATE UNIQUE INDEX IF NOT EXISTS uq_follow_up_tasks_pending_recurring
  ON public.follow_up_tasks (template_id, caregiver_id, client_id)
  WHERE anchor_shift_id IS NULL AND status = 'pending';

-- Hot path: "what's due today across all assignees" — Tasks dashboard.
CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_due_at
  ON public.follow_up_tasks (org_id, due_at)
  WHERE status = 'pending';

-- "Show me follow-ups for this caregiver" / "for this client" — the
-- inline panels on detail pages.
CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_caregiver
  ON public.follow_up_tasks (caregiver_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_client
  ON public.follow_up_tasks (client_id, status, due_at);

CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_org
  ON public.follow_up_tasks (org_id);

DROP TRIGGER IF EXISTS follow_up_tasks_touch_updated_at
  ON public.follow_up_tasks;
CREATE TRIGGER follow_up_tasks_touch_updated_at
  BEFORE UPDATE ON public.follow_up_tasks
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ────────────────────────────────────────────────────────────────────
-- 3. RLS — staff-only, org-scoped
-- ────────────────────────────────────────────────────────────────────
-- Tasks are office-staff territory. Caregivers do not see them in v1
-- (the PWA still uses CarePlanChecklist for client-care tasks).
-- Both templates and instances use the same is_staff() gate.

ALTER TABLE public.follow_up_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follow_up_tasks     ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
  cmd text;
  full_check text;
BEGIN
  full_check := 'public.is_staff() AND org_id = nullif((auth.jwt() ->> ''org_id''), '''')::uuid';
  FOR t IN SELECT unnest(ARRAY['follow_up_templates', 'follow_up_tasks']) LOOP
    FOR cmd IN SELECT unnest(ARRAY['select', 'insert', 'update', 'delete']) LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I',
                     t || '_staff_' || cmd, t);
    END LOOP;
  END LOOP;
END $$;

CREATE POLICY follow_up_templates_staff_select ON public.follow_up_templates
  FOR SELECT TO authenticated
  USING (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);
CREATE POLICY follow_up_templates_staff_insert ON public.follow_up_templates
  FOR INSERT TO authenticated
  WITH CHECK (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);
CREATE POLICY follow_up_templates_staff_update ON public.follow_up_templates
  FOR UPDATE TO authenticated
  USING (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid)
  WITH CHECK (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);
CREATE POLICY follow_up_templates_staff_delete ON public.follow_up_templates
  FOR DELETE TO authenticated
  USING (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);

CREATE POLICY follow_up_tasks_staff_select ON public.follow_up_tasks
  FOR SELECT TO authenticated
  USING (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);
CREATE POLICY follow_up_tasks_staff_insert ON public.follow_up_tasks
  FOR INSERT TO authenticated
  WITH CHECK (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);
CREATE POLICY follow_up_tasks_staff_update ON public.follow_up_tasks
  FOR UPDATE TO authenticated
  USING (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid)
  WITH CHECK (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);
CREATE POLICY follow_up_tasks_staff_delete ON public.follow_up_tasks
  FOR DELETE TO authenticated
  USING (public.is_staff() AND org_id = nullif((auth.jwt() ->> 'org_id'), '')::uuid);

-- ────────────────────────────────────────────────────────────────────
-- 4. Seed default templates per organization
-- ────────────────────────────────────────────────────────────────────
-- Four cadences: 0d / 7d / 14d / 30d-monthly. The 0d offset means
-- "land on the dashboard on the morning of the first scheduled shift."
-- SELECT-FROM-organizations so future orgs auto-receive them on signup.
-- ON CONFLICT DO NOTHING via UNIQUE (org_id, slug) makes the seed
-- idempotent and safe to re-run.

INSERT INTO public.follow_up_templates
  (org_id, slug, name, description, guidance, anchor_event,
   offset_days, recurring_interval_days, default_urgency, sort_order)
SELECT o.id, 'first_day_checkin',
       'First-day check-in',
       'Check in with the caregiver and client on the day the match starts.',
       'Call the caregiver before or after their first shift. Ask: How are you feeling about the client? Any access or supply issues? Anything we should know? Then call the client/RP: Did the caregiver arrive on time? How did the first shift go?',
       'first_scheduled_shift_day', 0, NULL, 'critical', 10
FROM public.organizations o
ON CONFLICT (org_id, slug) DO NOTHING;

INSERT INTO public.follow_up_templates
  (org_id, slug, name, description, guidance, anchor_event,
   offset_days, recurring_interval_days, default_urgency, sort_order)
SELECT o.id, 'first_week_followup',
       'First-week follow-up',
       'Check in one week after the match starts.',
       'Call the caregiver: How is the rhythm settling in? Any concerns about the client''s health, mobility, or behavior? Call the client/RP: Are you happy with the caregiver? Anything you want adjusted?',
       'first_scheduled_shift_day', 7, NULL, 'warning', 20
FROM public.organizations o
ON CONFLICT (org_id, slug) DO NOTHING;

INSERT INTO public.follow_up_templates
  (org_id, slug, name, description, guidance, anchor_event,
   offset_days, recurring_interval_days, default_urgency, sort_order)
SELECT o.id, 'two_week_followup',
       'Two-week follow-up',
       'Check in two weeks after the match starts.',
       'Confirm the schedule is working as expected. Identify any patterns: missed shifts, frequent reschedules, complaints from either side. Last chance to course-correct before the match is considered stable.',
       'first_scheduled_shift_day', 14, NULL, 'warning', 30
FROM public.organizations o
ON CONFLICT (org_id, slug) DO NOTHING;

INSERT INTO public.follow_up_templates
  (org_id, slug, name, description, guidance, anchor_event,
   offset_days, recurring_interval_days, default_urgency, sort_order)
SELECT o.id, 'monthly_checkin',
       'Monthly check-in',
       'Recurring 30-day touch-base.',
       'Quick relationship check. Caregiver: still happy with hours and client? Client/RP: any changes in care needs, family contacts, or finances? Update the care plan if anything has changed.',
       'first_scheduled_shift_day', 30, 30, 'info', 40
FROM public.organizations o
ON CONFLICT (org_id, slug) DO NOTHING;

-- ────────────────────────────────────────────────────────────────────
-- 5. Trigger: generate follow-ups on first-match shift
-- ────────────────────────────────────────────────────────────────────
-- Fires AFTER INSERT or UPDATE on shifts. Only generates instances
-- when this is the very first shift with a non-null caregiver+client
-- combo for that pair — verified via a NOT EXISTS check across the
-- shifts table (excluding the current row).
--
-- Why "first appearance in the schedule" not "first completed shift":
-- a long first shift might run 10am→8pm; the office needs the check-in
-- task in the morning, not at 8pm. So we anchor on start_time::date,
-- not on completion.
--
-- The function is SECURITY DEFINER so it can bypass RLS during the
-- INSERT — the calling code (an office user inserting a shift) might
-- not have direct INSERT rights to follow_up_tasks until the policy
-- check completes; the SECURITY DEFINER runs as the function owner,
-- which already holds the right grants. search_path is pinned to
-- prevent search-path-based privilege escalation.

CREATE OR REPLACE FUNCTION public.generate_follow_ups_on_first_shift()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_due_date      date;
  v_first_shift   boolean;
BEGIN
  -- Only fire when both caregiver_id and client_id are populated.
  IF NEW.assigned_caregiver_id IS NULL OR NEW.client_id IS NULL THEN
    RETURN NEW;
  END IF;

  -- On UPDATE, skip if the (caregiver, client) pair is unchanged.
  -- An UPDATE that doesn't change the pair is just an admin edit,
  -- not a new match.
  IF TG_OP = 'UPDATE' THEN
    IF OLD.assigned_caregiver_id IS NOT DISTINCT FROM NEW.assigned_caregiver_id
       AND OLD.client_id IS NOT DISTINCT FROM NEW.client_id THEN
      RETURN NEW;
    END IF;
  END IF;

  -- Is this the first shift this caregiver has ever had with this
  -- client? Cancelled / no_show shifts still count — the match was
  -- established when the office scheduled it. Excluding the current
  -- row so an UPDATE on the same shift doesn't disqualify itself.
  SELECT NOT EXISTS (
    SELECT 1 FROM shifts s
     WHERE s.id <> NEW.id
       AND s.assigned_caregiver_id = NEW.assigned_caregiver_id
       AND s.client_id = NEW.client_id
  ) INTO v_first_shift;

  IF NOT v_first_shift THEN
    RETURN NEW;
  END IF;

  v_due_date := (NEW.start_time AT TIME ZONE 'UTC')::date;

  -- Generate one instance per enabled template for this org with
  -- anchor_event = 'first_scheduled_shift_day'. due_at is the start
  -- of the shift's date plus offset_days, fixed at 09:00 UTC. (Org
  -- timezone selection is a Phase D concern; for now Tremendous Care
  -- and acme-test both run on US Pacific which is UTC-7/8 — 09:00 UTC
  -- = 1-2am Pacific. That's too early. Use the shift's start_time
  -- directly truncated to date instead so the dashboard groups it
  -- under "today" relative to the office's actual clock.)
  --
  -- Concretely: due_at = (NEW.start_time::date + offset_days) at the
  -- shift's local clock-zero. Approximation that works for v1: use
  -- NEW.start_time directly (preserves the timezone) but truncate to
  -- date and add 9 hours of wall-clock. Postgres handles this via
  -- date_trunc + interval arithmetic.
  INSERT INTO public.follow_up_tasks
    (org_id, template_id, caregiver_id, client_id, anchor_shift_id,
     due_at, urgency, assigned_to)
  SELECT
    t.org_id,
    t.id,
    NEW.assigned_caregiver_id,
    NEW.client_id,
    NEW.id,
    -- 09:00 UTC on (shift_start_date + offset). v2 will respect the
    -- org's configured timezone via organizations.settings.
    (date_trunc('day', NEW.start_time) + (t.offset_days || ' days')::interval + interval '9 hours'),
    t.default_urgency,
    t.default_assignee_email
  FROM public.follow_up_templates t
  WHERE t.enabled
    AND t.anchor_event = 'first_scheduled_shift_day'
    AND t.org_id = NEW.org_id
  ON CONFLICT (template_id, caregiver_id, client_id, anchor_shift_id) DO NOTHING;

  RETURN NEW;
END
$$;

REVOKE ALL ON FUNCTION public.generate_follow_ups_on_first_shift() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_follow_ups_on_first_shift() TO authenticated, service_role;

DROP TRIGGER IF EXISTS shifts_generate_follow_ups ON public.shifts;
CREATE TRIGGER shifts_generate_follow_ups
  AFTER INSERT OR UPDATE OF assigned_caregiver_id, client_id ON public.shifts
  FOR EACH ROW EXECUTE FUNCTION public.generate_follow_ups_on_first_shift();

-- ────────────────────────────────────────────────────────────────────
-- 6. Trigger: cancel pending follow-ups when assignment ends
-- ────────────────────────────────────────────────────────────────────
-- When a caregiver_assignment flips to status='ended', any pending
-- follow-ups for that match are no longer actionable. Mark them
-- cancelled with an audit reason so the dashboard doesn't keep
-- nagging staff about a relationship that's over.

CREATE OR REPLACE FUNCTION public.cancel_follow_ups_on_assignment_end()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  IF NEW.status <> 'ended' THEN
    RETURN NEW;
  END IF;
  IF OLD.status IS NOT DISTINCT FROM NEW.status THEN
    RETURN NEW;
  END IF;

  UPDATE public.follow_up_tasks
     SET status = 'cancelled',
         cancellation_reason = 'assignment_ended',
         updated_at = now()
   WHERE caregiver_id = NEW.caregiver_id
     AND client_id    = NEW.client_id
     AND status       = 'pending';

  RETURN NEW;
END
$$;

REVOKE ALL ON FUNCTION public.cancel_follow_ups_on_assignment_end() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cancel_follow_ups_on_assignment_end() TO authenticated, service_role;

DROP TRIGGER IF EXISTS caregiver_assignments_cancel_follow_ups
  ON public.caregiver_assignments;
CREATE TRIGGER caregiver_assignments_cancel_follow_ups
  AFTER UPDATE OF status ON public.caregiver_assignments
  FOR EACH ROW EXECUTE FUNCTION public.cancel_follow_ups_on_assignment_end();

-- ────────────────────────────────────────────────────────────────────
-- 7. Realtime
-- ────────────────────────────────────────────────────────────────────
-- The Tasks dashboard subscribes to follow_up_tasks so staff see
-- newly-generated tasks the moment a shift is scheduled, and so
-- "task marked done" reflects across tabs.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'follow_up_tasks'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.follow_up_tasks;
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────
-- 8. Sanity check
-- ────────────────────────────────────────────────────────────────────
-- Fail loudly if the trigger wiring or the seed didn't land.

DO $$
DECLARE
  v_template_count integer;
  v_tc_org_id      uuid;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'shifts_generate_follow_ups'
      AND tgrelid = 'public.shifts'::regclass
  ) THEN
    RAISE EXCEPTION 'follow-up tasks: shifts_generate_follow_ups trigger missing after migration';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'caregiver_assignments_cancel_follow_ups'
      AND tgrelid = 'public.caregiver_assignments'::regclass
  ) THEN
    RAISE EXCEPTION 'follow-up tasks: caregiver_assignments_cancel_follow_ups trigger missing after migration';
  END IF;

  v_tc_org_id := public.default_org_id();
  IF v_tc_org_id IS NULL THEN
    RAISE NOTICE 'follow-up tasks: default_org_id() returned NULL; skipping seed sanity check';
    RETURN;
  END IF;

  SELECT count(*) INTO v_template_count
    FROM public.follow_up_templates
   WHERE org_id = v_tc_org_id
     AND slug IN ('first_day_checkin', 'first_week_followup', 'two_week_followup', 'monthly_checkin');

  IF v_template_count <> 4 THEN
    RAISE EXCEPTION
      'follow-up tasks: expected 4 seeded templates for default org, found %', v_template_count;
  END IF;
END $$;
