-- Phase 1.1.B fix — strict-ordering column for the chain walk.
--
-- Codex P1 on PR #302: the verifier walks `(created_at ASC, id ASC)`,
-- but two rows written in the same millisecond can have ambiguous
-- ordering — `created_at` ties (millisecond precision from the
-- writer's `new Date().toISOString()`) and `id` is a random UUID,
-- so the smaller-uuid row sorts first even if it was inserted
-- second. Result: false `broken_chain_link` reports.
--
-- The RPC's per-org advisory lock makes INSERTs strictly ordered,
-- but that order is invisible to the verifier without a stable
-- column to read it back from. `chain_seq` is `GENERATED BY
-- DEFAULT AS IDENTITY`, which assigns a monotonically increasing
-- bigint at INSERT time inside the locked section. Walking by
-- chain_seq ASC matches insertion order exactly — no tie-breaker
-- ambiguity.
--
-- Why not signed: chain_seq is not part of `row_hash`. If it were,
-- the writer would need to know the value before INSERT (it's
-- assigned by Postgres at INSERT time). chain_seq is purely an
-- ordering hint for read-back; the cryptographic chain (via
-- prev_hash + row_hash + signature) catches any tampering with
-- chain_seq because the prev_hash linkage would no longer match
-- and signatures would no longer verify.
--
-- Safe on the existing empty table (PR #301 deployed but no
-- writes yet). If rows existed, the IDENTITY column would still
-- fill them with the sequence starting at 1 in some arbitrary
-- order — fine, because there are no existing rows.

ALTER TABLE public.agent_actions
  ADD COLUMN chain_seq bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY;

-- Explicit UNIQUE — IDENTITY guarantees uniqueness per default but
-- declaring the constraint makes the contract visible in \d output
-- and enforces it even if a future migration accidentally re-uses
-- a sequence value.
ALTER TABLE public.agent_actions
  ADD CONSTRAINT agent_actions_chain_seq_unique UNIQUE (chain_seq);

-- Per-org chain walk index. The verifier's read query becomes
--   SELECT ... WHERE org_id = $1 ORDER BY chain_seq ASC
-- which uses this composite index for a single-pass scan.
CREATE INDEX IF NOT EXISTS idx_agent_actions_org_chain_seq
  ON public.agent_actions (org_id, chain_seq ASC);

-- Update record_agent_action_v1 to also read "latest" via chain_seq
-- for consistency. Under the advisory lock the previous (created_at,
-- id) ordering produced correct results because there was only one
-- "latest" row per lock acquisition, but using chain_seq makes the
-- contract obvious from the function body.
CREATE OR REPLACE FUNCTION public.record_agent_action_v1(
  p_org_id              uuid,
  p_agent_id            uuid,
  p_agent_version       integer,
  p_action_type         text,
  p_phase               text,
  p_entity_type         text,
  p_entity_id           uuid,
  p_actor               text,
  p_payload             jsonb,
  p_outcome_id          uuid,
  p_created_at          timestamptz,
  p_claimed_prev_hash   text,
  p_row_hash            text,
  p_signature           text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_jwt_org_id     uuid;
  v_actual_prev    text;
  v_inserted_id    uuid;
  v_lock_key       bigint;
BEGIN
  IF p_org_id IS NULL OR p_agent_id IS NULL THEN
    RAISE EXCEPTION 'org_id and agent_id are required' USING ERRCODE = '22023';
  END IF;
  IF p_phase NOT IN ('suggested', 'confirmed', 'executed', 'auto_executed', 'rejected', 'expired', 'shadow') THEN
    RAISE EXCEPTION 'invalid phase: %', p_phase USING ERRCODE = '22023';
  END IF;
  IF p_action_type IS NULL OR length(p_action_type) = 0 THEN
    RAISE EXCEPTION 'action_type required' USING ERRCODE = '22023';
  END IF;
  IF p_row_hash IS NULL OR length(p_row_hash) = 0
     OR p_signature IS NULL OR length(p_signature) = 0
     OR p_claimed_prev_hash IS NULL THEN
    RAISE EXCEPTION 'row_hash, signature, and claimed_prev_hash are required' USING ERRCODE = '22023';
  END IF;
  IF p_created_at IS NULL THEN
    RAISE EXCEPTION 'p_created_at is required (must equal the timestamp used to compute row_hash)'
      USING ERRCODE = '22023';
  END IF;
  IF abs(extract(epoch from (now() - p_created_at))) > 300 THEN
    RAISE EXCEPTION 'p_created_at out of range (>5 min from server now())'
      USING ERRCODE = '22023';
  END IF;

  v_jwt_org_id := nullif(auth.jwt() ->> 'org_id', '')::uuid;
  IF v_jwt_org_id IS NOT NULL AND v_jwt_org_id <> p_org_id THEN
    RAISE EXCEPTION 'permission denied: JWT org_id does not match p_org_id'
      USING ERRCODE = '42501';
  END IF;

  v_lock_key := hashtext(p_org_id::text);
  PERFORM pg_advisory_xact_lock(v_lock_key);

  -- Read the most-recently-inserted row for this org by chain_seq.
  -- chain_seq is a strictly monotonic IDENTITY column, so this is
  -- unambiguous even when two rows share a millisecond timestamp.
  SELECT row_hash INTO v_actual_prev
    FROM public.agent_actions
   WHERE org_id = p_org_id
   ORDER BY chain_seq DESC
   LIMIT 1;
  IF v_actual_prev IS NULL THEN
    v_actual_prev := '';
  END IF;

  IF v_actual_prev <> p_claimed_prev_hash THEN
    RAISE EXCEPTION
      'agent_actions_chain_conflict: claimed prev_hash % does not match actual %',
      p_claimed_prev_hash, v_actual_prev
      USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.agent_actions (
    org_id, agent_id, agent_version, action_type, phase,
    entity_type, entity_id, actor, payload, outcome_id,
    created_at, prev_hash, row_hash, signature
  ) VALUES (
    p_org_id, p_agent_id, p_agent_version, p_action_type, p_phase,
    p_entity_type, p_entity_id, p_actor, COALESCE(p_payload, '{}'::jsonb), p_outcome_id,
    p_created_at, p_claimed_prev_hash, p_row_hash, p_signature
  )
  RETURNING id INTO v_inserted_id;

  RETURN v_inserted_id;
END;
$$;

-- Sanity: confirm column + index landed.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'agent_actions'
      AND column_name = 'chain_seq'
  ) THEN
    RAISE EXCEPTION 'chain_seq column missing on public.agent_actions';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public'
      AND tablename = 'agent_actions'
      AND indexname = 'idx_agent_actions_org_chain_seq'
  ) THEN
    RAISE EXCEPTION 'idx_agent_actions_org_chain_seq missing on public.agent_actions';
  END IF;
END
$$;
