// Phase 1.1.B — structural assertions for the new migrations.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(__dirname, '../../../supabase/migrations');
const rollbackDir = join(migrationsDir, '_rollback');

const anonSql = readFileSync(join(migrationsDir, '20260510070000_agent_platform_phase_1_1_b_anon_privilege_cleanup.sql'), 'utf-8');
const anonDownSql = readFileSync(join(rollbackDir, '20260510070000_agent_platform_phase_1_1_b_anon_privilege_cleanup_down.sql'), 'utf-8');
const cronSql = readFileSync(join(migrationsDir, '20260510080000_agent_platform_phase_1_1_b_verify_cron.sql'), 'utf-8');
const cronDownSql = readFileSync(join(rollbackDir, '20260510080000_agent_platform_phase_1_1_b_verify_cron_down.sql'), 'utf-8');
const chainSeqSql = readFileSync(join(migrationsDir, '20260510090000_agent_platform_phase_1_1_b_chain_seq.sql'), 'utf-8');
const chainSeqDownSql = readFileSync(join(rollbackDir, '20260510090000_agent_platform_phase_1_1_b_chain_seq_down.sql'), 'utf-8');

describe('Phase 1.1.B — anon privilege cleanup migration', () => {
  const tables = ['agents', 'agent_versions', 'agent_actions'];
  const privileges = ['INSERT', 'UPDATE', 'DELETE'];

  for (const table of tables) {
    for (const priv of privileges) {
      it(`revokes ${priv} on public.${table} from anon`, () => {
        expect(anonSql).toMatch(
          new RegExp(`REVOKE[^;]*\\b${priv}\\b[^;]*ON public\\.${table}\\b[^;]*FROM anon`, 'i')
        );
      });
    }
  }

  it('does NOT revoke SELECT (anon read still possible; RLS denies the rows)', () => {
    expect(anonSql).not.toMatch(/REVOKE[^;]*\bSELECT\b[^;]*ON public\.agents/i);
    expect(anonSql).not.toMatch(/REVOKE[^;]*\bSELECT\b[^;]*ON public\.agent_versions/i);
    expect(anonSql).not.toMatch(/REVOKE[^;]*\bSELECT\b[^;]*ON public\.agent_actions/i);
  });

  it('has a sanity DO block that aborts deploy if REVOKE failed', () => {
    expect(anonSql).toMatch(/information_schema\.table_privileges/);
    expect(anonSql).toMatch(/grantee = 'anon'/);
    expect(anonSql).toMatch(/RAISE EXCEPTION/);
  });

  it('rollback re-grants the three privileges on all three tables', () => {
    for (const table of tables) {
      for (const priv of privileges) {
        expect(anonDownSql).toMatch(
          new RegExp(`GRANT[^;]*\\b${priv}\\b[^;]*ON public\\.${table}\\b[^;]*TO anon`, 'i')
        );
      }
    }
  });
});

describe('Phase 1.1.B — agent-actions-verify cron migration', () => {
  it('schedules a job named agent-actions-verify', () => {
    expect(cronSql).toMatch(/cron\.schedule\(\s*'agent-actions-verify'/);
  });

  it('runs daily at 13:30 UTC', () => {
    expect(cronSql).toMatch(/'30 13 \* \* \*'/);
  });

  it('POSTs to /functions/v1/agent-actions-verify via pg_net', () => {
    expect(cronSql).toMatch(/net\.http_post/);
    expect(cronSql).toMatch(/\/functions\/v1\/agent-actions-verify/);
  });

  it('uses Vault-stored project_url + publishable_key (matches existing cron pattern)', () => {
    expect(cronSql).toMatch(/vault\.decrypted_secrets[\s\S]*?'project_url'/);
    expect(cronSql).toMatch(/vault\.decrypted_secrets[\s\S]*?'publishable_key'/);
  });

  it('rollback unschedules the job', () => {
    expect(cronDownSql).toMatch(/cron\.unschedule\(\s*'agent-actions-verify'\s*\)/);
  });
});

describe('Phase 1.1.B — chain_seq fix migration (Codex P1 #1 on PR #302)', () => {
  it('adds chain_seq as a GENERATED IDENTITY bigint NOT NULL column', () => {
    expect(chainSeqSql).toMatch(
      /ALTER TABLE public\.agent_actions[\s\S]*?ADD COLUMN chain_seq bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY/
    );
  });

  it('adds an explicit UNIQUE constraint on chain_seq', () => {
    expect(chainSeqSql).toMatch(/ADD CONSTRAINT agent_actions_chain_seq_unique UNIQUE \(chain_seq\)/);
  });

  it('creates a per-org chain walk index (org_id, chain_seq ASC)', () => {
    expect(chainSeqSql).toMatch(/idx_agent_actions_org_chain_seq[\s\S]*?\(org_id,\s*chain_seq ASC\)/);
  });

  it('replaces record_agent_action_v1 to read latest by chain_seq DESC', () => {
    // The whole-function CREATE OR REPLACE in the migration must
    // include the chain_seq DESC ordering for the latest-row read.
    expect(chainSeqSql).toMatch(/CREATE OR REPLACE FUNCTION public\.record_agent_action_v1/);
    expect(chainSeqSql).toMatch(/ORDER BY chain_seq DESC/);
  });

  it('has a sanity DO block confirming column + index landed', () => {
    expect(chainSeqSql).toMatch(/column_name = 'chain_seq'/);
    expect(chainSeqSql).toMatch(/indexname = 'idx_agent_actions_org_chain_seq'/);
    expect(chainSeqSql).toMatch(/RAISE EXCEPTION/);
  });

  describe('rollback', () => {
    it('drops the index, constraint, and column (in that order)', () => {
      const idxIdx = chainSeqDownSql.indexOf('DROP INDEX');
      const constraintIdx = chainSeqDownSql.indexOf('DROP CONSTRAINT');
      const colIdx = chainSeqDownSql.indexOf('DROP COLUMN');
      expect(idxIdx).toBeGreaterThanOrEqual(0);
      expect(constraintIdx).toBeGreaterThan(idxIdx);
      expect(colIdx).toBeGreaterThan(constraintIdx);
    });

    it('restores the prior record_agent_action_v1 body (created_at-based ORDER BY)', () => {
      expect(chainSeqDownSql).toMatch(/CREATE OR REPLACE FUNCTION public\.record_agent_action_v1/);
      expect(chainSeqDownSql).toMatch(/ORDER BY created_at DESC, id DESC/);
    });
  });
});
