import { describe, it, expect } from 'vitest';
import {
  EXCLUDED_DRAFT_SECTION_IDS,
  eligibleAssessmentSections,
  claimsToFieldPatch,
  taskClaimToCreateInput,
  summarizeDraftResult,
  describeDraftSummary,
  describeDraftOutcome,
} from '../assessmentCarePlan';

describe('eligibleAssessmentSections', () => {
  const sections = [
    { id: 'snapshot', order: 0, isAutoGenerated: true },
    { id: 'matchCriteria', order: 10 },
    { id: 'healthProfile', order: 2 },
    { id: 'whoTheyAre', order: 1 },
  ];
  it('drops auto-generated and excluded sections, sorts by order', () => {
    const out = eligibleAssessmentSections(sections).map((s) => s.id);
    expect(out).toEqual(['whoTheyAre', 'healthProfile']);
  });
  it('excludes matchCriteria explicitly', () => {
    expect(EXCLUDED_DRAFT_SECTION_IDS.has('matchCriteria')).toBe(true);
  });
  it('tolerates empty/nullish input', () => {
    expect(eligibleAssessmentSections(null)).toEqual([]);
    expect(eligibleAssessmentSections([])).toEqual([]);
  });
});

describe('claimsToFieldPatch', () => {
  it('builds a fieldId→value patch from accepted claims', () => {
    const patch = claimsToFieldPatch([
      { id: 'primaryLanguage', value: 'Spanish', confidence: 'high' },
      { id: 'hearing', value: 'Impaired (left)', confidence: 'medium' },
    ]);
    expect(patch).toEqual({ primaryLanguage: 'Spanish', hearing: 'Impaired (left)' });
  });
  it('preserves falsy/array values and last-wins on dup id', () => {
    const patch = claimsToFieldPatch([
      { id: 'needsReminders', value: false },
      { id: 'meds', value: [{ name: 'Lisinopril' }] },
      { id: 'needsReminders', value: true },
    ]);
    expect(patch.needsReminders).toBe(true);
    expect(patch.meds).toEqual([{ name: 'Lisinopril' }]);
  });
  it('ignores malformed claims', () => {
    expect(claimsToFieldPatch([null, {}, { value: 'x' }])).toEqual({});
    expect(claimsToFieldPatch(undefined)).toEqual({});
  });
});

describe('taskClaimToCreateInput', () => {
  it('maps snake_case claim to camelCase createTask input', () => {
    const out = taskClaimToCreateInput({
      category: 'adl.bathing',
      task_name: 'Assist with shower',
      description: 'Uses a shower chair',
      shifts: ['morning'],
      days_of_week: ['Mon', 'Wed', 'Fri'],
      priority: 'critical',
      safety_notes: 'Non-slip mat',
    });
    expect(out).toEqual({
      category: 'adl.bathing',
      taskName: 'Assist with shower',
      description: 'Uses a shower chair',
      shifts: ['morning'],
      daysOfWeek: [1, 3, 5], // Mon/Wed/Fri → integer day-of-week (int[] column)
      priority: 'critical',
      safetyNotes: 'Non-slip mat',
    });
  });
  it('applies safe defaults for missing optional fields', () => {
    const out = taskClaimToCreateInput({ category: 'iadl.housework', task_name: 'Tidy kitchen' });
    expect(out.shifts).toEqual([]);
    expect(out.daysOfWeek).toEqual([]);
    expect(out.priority).toBe('standard');
    expect(out.safetyNotes).toBeNull();
    expect(out.description).toBeNull();
  });
});

describe('summarizeDraftResult / describeDraftSummary', () => {
  const results = [
    { sectionId: 'healthProfile', extracted: [{ id: 'a' }, { id: 'b' }], proposedTasks: [] },
    { sectionId: 'dailyLiving', extracted: [{ id: 'c' }], proposedTasks: [{ category: 'adl.bathing' }] },
    { sectionId: 'careTeam', extracted: [], proposedTasks: [] },
  ];
  it('counts sections-with-content, fields, and tasks', () => {
    expect(summarizeDraftResult(results)).toEqual({ sectionsWithContent: 2, fields: 3, tasks: 1 });
  });
  it('describes a non-empty draft', () => {
    expect(describeDraftSummary({ sectionsWithContent: 2, fields: 3, tasks: 1 }))
      .toBe('Draft updated with 3 fields and 1 task across 2 sections.');
  });
  it('handles singular field and zero tasks', () => {
    expect(describeDraftSummary({ sectionsWithContent: 1, fields: 1, tasks: 0 }))
      .toBe('Draft updated with 1 field across 1 section.');
  });
  it('describes an empty result', () => {
    expect(describeDraftSummary({ sectionsWithContent: 0, fields: 0, tasks: 0 }))
      .toBe('No new care-plan details were found in this assessment.');
  });
});

describe('describeDraftOutcome', () => {
  it('reports a clean apply with no skips (no failure clause)', () => {
    const msg = describeDraftOutcome({
      applied: { sections: 2, fields: 3, tasks: 1 },
      skipped: [],
    });
    expect(msg).toBe('Draft updated with 3 fields and 1 task across 2 sections.');
    expect(msg).not.toMatch(/couldn't/);
  });

  it('names skipped items specifically and loudly', () => {
    const msg = describeDraftOutcome({
      applied: { sections: 5, fields: 34, tasks: 9 },
      skipped: [
        { label: 'Assist with shower (dailyLiving)', reason: 'x' },
        { label: 'Drive to appointment (homeAndLife)', reason: 'y' },
      ],
    });
    expect(msg).toContain('Draft updated with 34 fields and 9 tasks across 5 sections.');
    expect(msg).toContain("2 items couldn't be applied automatically");
    expect(msg).toContain('Assist with shower (dailyLiving)');
    expect(msg).toContain('add them manually');
  });

  it('truncates a long skip list to 3 names + "and N more"', () => {
    const skipped = ['a', 'b', 'c', 'd', 'e'].map((label) => ({ label, reason: 'r' }));
    const msg = describeDraftOutcome({ applied: { sections: 1, fields: 1, tasks: 0 }, skipped });
    expect(msg).toContain('(a, b, c and 2 more)');
  });

  it('uses singular phrasing for a single skipped item', () => {
    const msg = describeDraftOutcome({
      applied: { sections: 1, fields: 2, tasks: 0 },
      skipped: [{ label: 'Tidy kitchen (homeAndLife)', reason: 'r' }],
    });
    expect(msg).toContain("1 item couldn't be applied automatically");
  });

  it('handles nothing-applied-but-some-skipped distinctly from nothing-found', () => {
    expect(describeDraftOutcome({ applied: { sections: 0, fields: 0, tasks: 0 }, skipped: [] }))
      .toBe('No new care-plan details were found in this assessment.');
    const allFailed = describeDraftOutcome({
      applied: { sections: 0, fields: 0, tasks: 0 },
      skipped: [{ label: 'Task A', reason: 'r' }],
    });
    expect(allFailed).toContain('No care-plan details could be applied');
    expect(allFailed).toContain("1 item couldn't be applied");
  });

  it('tolerates missing/empty input', () => {
    expect(describeDraftOutcome()).toBe('No new care-plan details were found in this assessment.');
    expect(describeDraftOutcome({})).toBe('No new care-plan details were found in this assessment.');
  });
});
