import { describe, it, expect } from 'vitest';
import {
  CARE_PLAN_SECTIONS,
  TASK_CATEGORIES,
  getSectionById,
  sectionIdForCategory,
  sectionUsesTasks,
  sortedSections,
} from '../../features/care-plans/sections';

// ─── Section catalog ────────────────────────────────────────────

describe('CARE_PLAN_SECTIONS', () => {
  it('defines 16 sections matching the Phase 2 design', () => {
    expect(CARE_PLAN_SECTIONS).toHaveLength(16);
  });

  it('every section has id, label, description, and order', () => {
    for (const section of CARE_PLAN_SECTIONS) {
      expect(section.id).toBeTruthy();
      expect(section.label).toBeTruthy();
      expect(section.description).toBeTruthy();
      expect(typeof section.order).toBe('number');
    }
  });

  it('section ids are unique', () => {
    const ids = CARE_PLAN_SECTIONS.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('section order values are unique and form a contiguous 1..N range', () => {
    const orders = CARE_PLAN_SECTIONS.map((s) => s.order).sort((a, b) => a - b);
    for (let i = 0; i < orders.length; i++) {
      expect(orders[i]).toBe(i + 1);
    }
  });

  it('snapshot section is flagged as AI-generated', () => {
    const snapshot = CARE_PLAN_SECTIONS.find((s) => s.id === 'snapshot');
    expect(snapshot?.isAutoGenerated).toBe(true);
  });

  it('ADL and IADL sections are the only ones that use the tasks table', () => {
    const taskSections = CARE_PLAN_SECTIONS.filter((s) => s.usesTasksTable);
    expect(taskSections.map((s) => s.id).sort()).toEqual(['adlTasks', 'iadlTasks']);
  });
});

// ─── getSectionById ─────────────────────────────────────────────

describe('getSectionById', () => {
  it('returns the matching section', () => {
    const s = getSectionById('demographics');
    expect(s?.label).toMatch(/Demographics/);
  });

  it('returns undefined for an unknown id', () => {
    expect(getSectionById('totally-not-a-section')).toBeUndefined();
  });

  it('returns undefined for a missing id', () => {
    expect(getSectionById(null)).toBeUndefined();
    expect(getSectionById(undefined)).toBeUndefined();
    expect(getSectionById('')).toBeUndefined();
  });
});

// ─── sortedSections ─────────────────────────────────────────────

describe('sortedSections', () => {
  it('returns sections ordered by .order ascending', () => {
    const list = sortedSections();
    for (let i = 1; i < list.length; i++) {
      expect(list[i].order).toBeGreaterThan(list[i - 1].order);
    }
  });

  it('does not mutate the underlying CARE_PLAN_SECTIONS array', () => {
    const snapshotBefore = [...CARE_PLAN_SECTIONS];
    sortedSections();
    expect(CARE_PLAN_SECTIONS).toEqual(snapshotBefore);
  });
});

// ─── sectionUsesTasks ───────────────────────────────────────────

describe('sectionUsesTasks', () => {
  it('returns true for adlTasks', () => {
    expect(sectionUsesTasks(getSectionById('adlTasks'))).toBe(true);
  });

  it('returns true for iadlTasks', () => {
    expect(sectionUsesTasks(getSectionById('iadlTasks'))).toBe(true);
  });

  it('returns false for non-task sections', () => {
    expect(sectionUsesTasks(getSectionById('demographics'))).toBe(false);
    expect(sectionUsesTasks(getSectionById('medications'))).toBe(false);
    expect(sectionUsesTasks(getSectionById('routines'))).toBe(false);
  });

  it('returns false for null / undefined', () => {
    expect(sectionUsesTasks(null)).toBe(false);
    expect(sectionUsesTasks(undefined)).toBe(false);
  });
});

// ─── TASK_CATEGORIES ────────────────────────────────────────────

describe('TASK_CATEGORIES', () => {
  it('every category maps to a section that exists', () => {
    for (const [category, meta] of Object.entries(TASK_CATEGORIES)) {
      expect(getSectionById(meta.section)).toBeDefined();
      expect(meta.label).toBeTruthy();
      expect(category).toMatch(/^(adl|iadl)\./);
    }
  });

  it('only routes to adlTasks or iadlTasks sections', () => {
    const targets = new Set(Object.values(TASK_CATEGORIES).map((m) => m.section));
    expect(targets).toEqual(new Set(['adlTasks', 'iadlTasks']));
  });

  it('adl.* categories route to adlTasks', () => {
    for (const [category, meta] of Object.entries(TASK_CATEGORIES)) {
      if (category.startsWith('adl.')) {
        expect(meta.section).toBe('adlTasks');
      }
    }
  });

  it('iadl.* categories route to iadlTasks', () => {
    for (const [category, meta] of Object.entries(TASK_CATEGORIES)) {
      if (category.startsWith('iadl.')) {
        expect(meta.section).toBe('iadlTasks');
      }
    }
  });
});

// ─── sectionIdForCategory ───────────────────────────────────────

describe('sectionIdForCategory', () => {
  it('returns adlTasks for adl.bathing', () => {
    expect(sectionIdForCategory('adl.bathing')).toBe('adlTasks');
  });

  it('returns iadlTasks for iadl.housework', () => {
    expect(sectionIdForCategory('iadl.housework')).toBe('iadlTasks');
  });

  it('returns null for an unknown category', () => {
    expect(sectionIdForCategory('bogus.category')).toBeNull();
    expect(sectionIdForCategory('')).toBeNull();
    expect(sectionIdForCategory(null)).toBeNull();
  });
});
