import { describe, it, expect } from 'vitest';
import {
  CARE_PLAN_SECTIONS,
  FIELD_TYPES,
  VISIBILITY_TIERS,
  TASK_CATEGORIES,
  getSectionById,
  sectionIdForCategory,
  sectionUsesTasks,
  sortedSections,
  visibleSectionsForTier,
  getFieldById,
} from '../../features/care-plans/sections';

// ═══════════════════════════════════════════════════════════════
// Section catalog
// ═══════════════════════════════════════════════════════════════

describe('CARE_PLAN_SECTIONS', () => {
  it('defines 11 sections (Phase 2b taxonomy)', () => {
    expect(CARE_PLAN_SECTIONS).toHaveLength(11);
  });

  it('every section has id, label, description, order, tiers', () => {
    for (const section of CARE_PLAN_SECTIONS) {
      expect(section.id).toBeTruthy();
      expect(section.label).toBeTruthy();
      expect(section.description).toBeTruthy();
      expect(typeof section.order).toBe('number');
      expect(Array.isArray(section.tiers)).toBe(true);
      expect(section.tiers.length).toBeGreaterThan(0);
    }
  });

  it('section ids are unique', () => {
    const ids = CARE_PLAN_SECTIONS.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('section order values form a contiguous 0..N range', () => {
    const orders = CARE_PLAN_SECTIONS.map((s) => s.order).sort((a, b) => a - b);
    for (let i = 0; i < orders.length; i++) {
      expect(orders[i]).toBe(i);
    }
  });

  it('snapshot is at order 0 and is flagged as AI-generated', () => {
    const snapshot = CARE_PLAN_SECTIONS.find((s) => s.id === 'snapshot');
    expect(snapshot).toBeDefined();
    expect(snapshot.order).toBe(0);
    expect(snapshot.isAutoGenerated).toBe(true);
  });

  it('dailyLiving and homeAndLife are the only task-table sections', () => {
    const taskSections = CARE_PLAN_SECTIONS.filter((s) => s.usesTasksTable);
    expect(taskSections.map((s) => s.id).sort()).toEqual(['dailyLiving', 'homeAndLife']);
  });

  it('matchCriteria is admin-only (no caregiver or family visibility)', () => {
    const match = getSectionById('matchCriteria');
    expect(match?.tiers).toEqual(['admin']);
  });

  it('expected family-visible sections are tagged for family tier', () => {
    const familySections = CARE_PLAN_SECTIONS
      .filter((s) => s.tiers.includes('family'))
      .map((s) => s.id)
      .sort();
    expect(familySections).toEqual(
      ['dailyLiving', 'dailyRhythm', 'homeAndLife', 'whoTheyAre'].sort(),
    );
  });
});

// ═══════════════════════════════════════════════════════════════
// Field definitions
// ═══════════════════════════════════════════════════════════════

describe('Section fields', () => {
  it('every field has an id, label, and type', () => {
    for (const section of CARE_PLAN_SECTIONS) {
      for (const field of section.fields) {
        expect(field.id, `${section.id}.${field.id} id`).toBeTruthy();
        expect(field.label, `${section.id}.${field.id} label`).toBeTruthy();
        expect(field.type, `${section.id}.${field.id} type`).toBeTruthy();
      }
    }
  });

  it('field ids are unique within each section', () => {
    for (const section of CARE_PLAN_SECTIONS) {
      const ids = section.fields.map((f) => f.id);
      expect(new Set(ids).size, `duplicate field ids in ${section.id}`).toBe(ids.length);
    }
  });

  it('every field.type is one of FIELD_TYPES', () => {
    const validTypes = new Set(Object.values(FIELD_TYPES));
    for (const section of CARE_PLAN_SECTIONS) {
      for (const field of section.fields) {
        expect(validTypes.has(field.type), `bad type on ${section.id}.${field.id}: ${field.type}`).toBe(true);
      }
    }
  });

  it('select / multiselect / prn fields have non-empty options (or prn uses default)', () => {
    const typesRequiringOptions = [FIELD_TYPES.SELECT, FIELD_TYPES.MULTISELECT];
    for (const section of CARE_PLAN_SECTIONS) {
      for (const field of section.fields) {
        if (typesRequiringOptions.includes(field.type)) {
          expect(
            Array.isArray(field.options) && field.options.length > 0,
            `${section.id}.${field.id} missing options`,
          ).toBe(true);
        }
        if (field.type === FIELD_TYPES.PRN && field.options) {
          expect(field.options.length).toBeGreaterThan(0);
        }
      }
    }
  });

  it('list fields define subfields with valid types', () => {
    const validTypes = new Set(Object.values(FIELD_TYPES));
    for (const section of CARE_PLAN_SECTIONS) {
      for (const field of section.fields) {
        if (field.type === FIELD_TYPES.LIST) {
          expect(Array.isArray(field.subfields), `${section.id}.${field.id} missing subfields`).toBe(true);
          expect(field.subfields.length).toBeGreaterThan(0);
          for (const sub of field.subfields) {
            expect(sub.id).toBeTruthy();
            expect(sub.label).toBeTruthy();
            expect(validTypes.has(sub.type)).toBe(true);
          }
        }
      }
    }
  });

  it('conditional fields reference a sibling field that exists in the same section', () => {
    for (const section of CARE_PLAN_SECTIONS) {
      const fieldIds = new Set(section.fields.map((f) => f.id));
      for (const field of section.fields) {
        if (field.conditional) {
          expect(
            fieldIds.has(field.conditional.field),
            `${section.id}.${field.id} conditional references missing sibling '${field.conditional.field}'`,
          ).toBe(true);
        }
      }
    }
  });

  it('snapshot section has exactly one readonly field (the narrative)', () => {
    const snapshot = getSectionById('snapshot');
    expect(snapshot.fields).toHaveLength(1);
    expect(snapshot.fields[0].id).toBe('narrative');
    expect(snapshot.fields[0].readOnly).toBe(true);
  });

  it('tiers values are all from VISIBILITY_TIERS', () => {
    const validTiers = new Set(Object.values(VISIBILITY_TIERS));
    for (const section of CARE_PLAN_SECTIONS) {
      for (const tier of section.tiers) {
        expect(validTiers.has(tier), `${section.id} has invalid tier: ${tier}`).toBe(true);
      }
    }
  });
});

describe('CMS-485 flagged fields', () => {
  it('tags date of birth (whoTheyAre)', () => {
    const dob = getFieldById('whoTheyAre', 'dateOfBirth');
    expect(dob?.cms485).toBe(true);
  });

  it('tags primary diagnoses (healthProfile)', () => {
    const dx = getFieldById('healthProfile', 'primaryDiagnoses');
    expect(dx?.cms485).toBe(true);
  });

  it('tags start of care date (goalsOrders)', () => {
    const soc = getFieldById('goalsOrders', 'startOfCareDate');
    expect(soc?.cms485).toBe(true);
  });

  it('tags safety measures (goalsOrders)', () => {
    const sm = getFieldById('goalsOrders', 'safetyMeasures');
    expect(sm?.cms485).toBe(true);
  });

  it('tags PCP name + phone (careTeam)', () => {
    expect(getFieldById('careTeam', 'pcpName')?.cms485).toBe(true);
    expect(getFieldById('careTeam', 'pcpPhone')?.cms485).toBe(true);
  });
});

// ═══════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════

describe('getSectionById', () => {
  it('returns the matching section', () => {
    expect(getSectionById('healthProfile')?.label).toBe('Health Profile');
  });

  it('returns undefined for an unknown id', () => {
    expect(getSectionById('totally-not-a-section')).toBeUndefined();
  });

  it('returns undefined for a missing id', () => {
    expect(getSectionById(null)).toBeUndefined();
    expect(getSectionById(undefined)).toBeUndefined();
    expect(getSectionById('')).toBeUndefined();
  });
});

describe('sortedSections', () => {
  it('returns sections ordered by .order ascending', () => {
    const list = sortedSections();
    for (let i = 1; i < list.length; i++) {
      expect(list[i].order).toBeGreaterThan(list[i - 1].order);
    }
  });

  it('does not mutate the underlying array', () => {
    const before = [...CARE_PLAN_SECTIONS];
    sortedSections();
    expect(CARE_PLAN_SECTIONS).toEqual(before);
  });

  it('puts snapshot first', () => {
    expect(sortedSections()[0].id).toBe('snapshot');
  });
});

describe('sectionUsesTasks', () => {
  it('returns true for dailyLiving', () => {
    expect(sectionUsesTasks(getSectionById('dailyLiving'))).toBe(true);
  });

  it('returns true for homeAndLife', () => {
    expect(sectionUsesTasks(getSectionById('homeAndLife'))).toBe(true);
  });

  it('returns false for non-task sections', () => {
    expect(sectionUsesTasks(getSectionById('whoTheyAre'))).toBe(false);
    expect(sectionUsesTasks(getSectionById('healthProfile'))).toBe(false);
    expect(sectionUsesTasks(getSectionById('dailyRhythm'))).toBe(false);
  });

  it('returns false for null / undefined', () => {
    expect(sectionUsesTasks(null)).toBe(false);
    expect(sectionUsesTasks(undefined)).toBe(false);
  });
});

describe('visibleSectionsForTier', () => {
  it('returns only admin-visible sections for admin tier', () => {
    const admin = visibleSectionsForTier('admin').map((s) => s.id);
    expect(admin).toContain('matchCriteria');
    expect(admin).toContain('healthProfile');
    expect(admin).toContain('snapshot');
  });

  it('caregiver tier excludes admin-only matchCriteria', () => {
    const caregiver = visibleSectionsForTier('caregiver').map((s) => s.id);
    expect(caregiver).not.toContain('matchCriteria');
    expect(caregiver).toContain('healthProfile');
  });

  it('family tier only includes sections tagged for family', () => {
    const family = visibleSectionsForTier('family').map((s) => s.id).sort();
    expect(family).toEqual(
      ['dailyLiving', 'dailyRhythm', 'homeAndLife', 'whoTheyAre'].sort(),
    );
  });

  it('returns empty array for unknown or missing tier', () => {
    expect(visibleSectionsForTier('nope')).toEqual([]);
    expect(visibleSectionsForTier(null)).toEqual([]);
    expect(visibleSectionsForTier(undefined)).toEqual([]);
  });

  it('results are sorted by order', () => {
    const list = visibleSectionsForTier('caregiver');
    for (let i = 1; i < list.length; i++) {
      expect(list[i].order).toBeGreaterThan(list[i - 1].order);
    }
  });
});

describe('getFieldById', () => {
  it('returns the matching field within a section', () => {
    const f = getFieldById('whoTheyAre', 'fullName');
    expect(f?.label).toBe('Full legal name');
  });

  it('returns undefined for an unknown field', () => {
    expect(getFieldById('whoTheyAre', 'nonsense')).toBeUndefined();
  });

  it('returns undefined for an unknown section', () => {
    expect(getFieldById('nonsense', 'fullName')).toBeUndefined();
  });

  it('returns undefined for missing args', () => {
    expect(getFieldById(null, 'fullName')).toBeUndefined();
    expect(getFieldById('whoTheyAre', null)).toBeUndefined();
    expect(getFieldById(null, null)).toBeUndefined();
  });
});

// ═══════════════════════════════════════════════════════════════
// TASK_CATEGORIES (updated routing)
// ═══════════════════════════════════════════════════════════════

describe('TASK_CATEGORIES', () => {
  it('every category maps to a section that exists', () => {
    for (const [category, meta] of Object.entries(TASK_CATEGORIES)) {
      expect(getSectionById(meta.section)).toBeDefined();
      expect(meta.label).toBeTruthy();
      expect(category).toMatch(/^(adl|iadl)\./);
    }
  });

  it('only routes to dailyLiving or homeAndLife sections', () => {
    const targets = new Set(Object.values(TASK_CATEGORIES).map((m) => m.section));
    expect(targets).toEqual(new Set(['dailyLiving', 'homeAndLife']));
  });

  it('adl.* categories route to dailyLiving', () => {
    for (const [category, meta] of Object.entries(TASK_CATEGORIES)) {
      if (category.startsWith('adl.')) {
        expect(meta.section).toBe('dailyLiving');
      }
    }
  });

  it('iadl.* categories route to homeAndLife', () => {
    for (const [category, meta] of Object.entries(TASK_CATEGORIES)) {
      if (category.startsWith('iadl.')) {
        expect(meta.section).toBe('homeAndLife');
      }
    }
  });
});

describe('sectionIdForCategory', () => {
  it('returns dailyLiving for adl.bathing', () => {
    expect(sectionIdForCategory('adl.bathing')).toBe('dailyLiving');
  });

  it('returns homeAndLife for iadl.housework', () => {
    expect(sectionIdForCategory('iadl.housework')).toBe('homeAndLife');
  });

  it('returns null for an unknown category', () => {
    expect(sectionIdForCategory('bogus.category')).toBeNull();
    expect(sectionIdForCategory('')).toBeNull();
    expect(sectionIdForCategory(null)).toBeNull();
  });
});
