import { describe, it, expect } from 'vitest';
import {
  buildVoiceFieldSchema,
  sectionSupportsVoiceCapture,
  describeConditional,
} from '../../features/care-plans/voice/voiceFieldSchema';
import { FIELD_TYPES, getSectionById, CARE_PLAN_SECTIONS } from '../../features/care-plans/sections';


// ─── sectionSupportsVoiceCapture ───────────────────────────────

describe('sectionSupportsVoiceCapture', () => {
  it('returns false for null/undefined', () => {
    expect(sectionSupportsVoiceCapture(null)).toBe(false);
    expect(sectionSupportsVoiceCapture(undefined)).toBe(false);
  });

  it('returns false for the auto-generated Snapshot section', () => {
    expect(sectionSupportsVoiceCapture(getSectionById('snapshot'))).toBe(false);
  });

  it('returns false for grouped task-driven sections (ADLs)', () => {
    expect(sectionSupportsVoiceCapture(getSectionById('dailyLiving'))).toBe(false);
  });

  it('returns false for grouped task-driven sections (IADLs)', () => {
    expect(sectionSupportsVoiceCapture(getSectionById('homeAndLife'))).toBe(false);
  });

  it('returns true for narrative editable sections', () => {
    expect(sectionSupportsVoiceCapture(getSectionById('whoTheyAre'))).toBe(true);
    expect(sectionSupportsVoiceCapture(getSectionById('cognitionBehavior'))).toBe(true);
    expect(sectionSupportsVoiceCapture(getSectionById('dailyRhythm'))).toBe(true);
  });

  it('returns true for structured editable sections (Health Profile, Care Team, etc.)', () => {
    expect(sectionSupportsVoiceCapture(getSectionById('healthProfile'))).toBe(true);
    expect(sectionSupportsVoiceCapture(getSectionById('careTeam'))).toBe(true);
    expect(sectionSupportsVoiceCapture(getSectionById('goalsOrders'))).toBe(true);
    expect(sectionSupportsVoiceCapture(getSectionById('homeEnvironment'))).toBe(true);
    expect(sectionSupportsVoiceCapture(getSectionById('matchCriteria'))).toBe(true);
  });

  it('every section is consistently classified (every section is either supported or skipped, no surprises)', () => {
    // This guards future section additions — if someone adds a new
    // section type that doesn't fit either bucket, we'll catch it here
    // and make a deliberate decision rather than silently breaking voice.
    for (const section of CARE_PLAN_SECTIONS) {
      const supported = sectionSupportsVoiceCapture(section);
      const expectedSkip = section.isAutoGenerated
        || section.usesTasksTable
        || (Array.isArray(section.groups) && section.groups.length > 0);
      expect(supported).toBe(!expectedSkip);
    }
  });
});


// ─── buildVoiceFieldSchema ─────────────────────────────────────

describe('buildVoiceFieldSchema', () => {
  it('returns null for null/undefined input', () => {
    expect(buildVoiceFieldSchema(null)).toBeNull();
    expect(buildVoiceFieldSchema(undefined)).toBeNull();
  });

  it('passes through section identity (id, label, description)', () => {
    const section = getSectionById('whoTheyAre');
    const schema = buildVoiceFieldSchema(section);
    expect(schema.sectionId).toBe('whoTheyAre');
    expect(schema.sectionLabel).toBe('Who They Are');
    expect(schema.sectionDescription).toContain('person');
  });

  it('emits one field entry per editable field, in declaration order', () => {
    const section = getSectionById('whoTheyAre');
    const schema = buildVoiceFieldSchema(section);
    // section.fields is the source of truth — schema should mirror it
    // (minus readOnly fields, which whoTheyAre has none of)
    expect(schema.fields.map((f) => f.id))
      .toEqual(section.fields.map((f) => f.id));
  });

  it('excludes readOnly fields (e.g., Snapshot.narrative)', () => {
    const section = getSectionById('snapshot');
    const schema = buildVoiceFieldSchema(section);
    // Snapshot only has one field and it's readOnly, so schema is empty.
    expect(schema.fields).toEqual([]);
  });

  it('preserves enum options for select fields', () => {
    const section = getSectionById('whoTheyAre');
    const schema = buildVoiceFieldSchema(section);
    const gender = schema.fields.find((f) => f.id === 'gender');
    expect(gender.type).toBe(FIELD_TYPES.SELECT);
    expect(gender.options).toEqual(['Female', 'Male', 'Non-binary', 'Prefer not to say']);
  });

  it('preserves enum options for multiselect fields', () => {
    const section = getSectionById('whoTheyAre');
    const schema = buildVoiceFieldSchema(section);
    const languages = schema.fields.find((f) => f.id === 'languages');
    expect(languages.type).toBe(FIELD_TYPES.MULTISELECT);
    expect(languages.options).toContain('English');
    expect(languages.options).toContain('Spanish');
  });

  it('emits the 5-step ability scale for LEVEL_PICK fields', () => {
    // matchCriteria's PRN fields aren't LEVEL_PICK; daily living has
    // them but is excluded. Build a synthetic section to exercise the
    // LEVEL_PICK projection.
    const synth = {
      id: 'x', label: 'X', fields: [
        { id: 'lvl', label: 'L', type: FIELD_TYPES.LEVEL_PICK },
      ],
    };
    const schema = buildVoiceFieldSchema(synth);
    expect(schema.fields[0].options).toEqual(
      ['Independent', 'Setup only', 'Partial assist', 'Full assist', 'Dependent'],
    );
  });

  it('treats AUTOCOMPLETE fields as plain text with a suggestionsKey hint', () => {
    const section = getSectionById('healthProfile');
    const schema = buildVoiceFieldSchema(section);
    const meds = schema.fields.find((f) => f.id === 'medications');
    // medications is a LIST whose first subfield is autocomplete (name)
    expect(meds.type).toBe(FIELD_TYPES.LIST);
    const nameSub = meds.subfields.find((s) => s.id === 'name');
    expect(nameSub.type).toBe(FIELD_TYPES.TEXT);
    expect(nameSub.suggestionsKey).toBe('commonMedications');
  });

  it('recurses into LIST subfields', () => {
    const section = getSectionById('healthProfile');
    const schema = buildVoiceFieldSchema(section);
    const meds = schema.fields.find((f) => f.id === 'medications');
    expect(meds.subfields.map((s) => s.id))
      .toEqual(['name', 'dose', 'route', 'frequency', 'prn', 'reason', 'prescriber']);
    const route = meds.subfields.find((s) => s.id === 'route');
    expect(route.type).toBe(FIELD_TYPES.SELECT);
    expect(route.options).toContain('PO (oral)');
  });

  it('emits a plain-English conditionalHint for conditional fields', () => {
    const section = getSectionById('whoTheyAre');
    const schema = buildVoiceFieldSchema(section);
    const spouse = schema.fields.find((f) => f.id === 'spouseName');
    expect(spouse.conditionalHint).toContain('Marital status');
    expect(spouse.conditionalHint).toContain('Married');
    expect(spouse.conditionalHint).toContain('Partnered');
  });

  it('preserves help text for the LLM to read', () => {
    const section = getSectionById('cognitionBehavior');
    const schema = buildVoiceFieldSchema(section);
    const calming = schema.fields.find((f) => f.id === 'calmingStrategies');
    expect(calming.help).toContain('caregiver');
  });
});


// ─── describeConditional ───────────────────────────────────────

describe('describeConditional', () => {
  const synthSection = {
    fields: [
      { id: 'sib', label: 'Sibling field' },
    ],
  };

  it('returns empty string for null/undefined', () => {
    expect(describeConditional(null, synthSection)).toBe('');
    expect(describeConditional(undefined, synthSection)).toBe('');
  });

  it('describes `in` rules', () => {
    const out = describeConditional({ field: 'sib', in: ['A', 'B'] }, synthSection);
    expect(out).toContain("'Sibling field'");
    expect(out).toContain('A, B');
  });

  it('describes `equals` rules', () => {
    const out = describeConditional({ field: 'sib', equals: 'Yes' }, synthSection);
    expect(out).toContain("'Yes'");
  });

  it('describes `notEquals: ""` as "is set"', () => {
    const out = describeConditional({ field: 'sib', notEquals: '' }, synthSection);
    expect(out).toMatch(/is set/);
  });

  it('describes `notEquals` with a value', () => {
    const out = describeConditional({ field: 'sib', notEquals: 'None' }, synthSection);
    expect(out).toContain('not');
    expect(out).toContain("'None'");
  });

  it('falls back to the raw field id if the sibling isn\'t in the section', () => {
    const out = describeConditional({ field: 'ghost', equals: 'X' }, synthSection);
    expect(out).toContain("'ghost'");
  });
});
